### ISSUE TITLE
sccache server fails to start with caused by: Server startup failed: 1

### ISSUE THREAD

**Issue by AnishAnil** [mozilla/sccache#1005]
Hello sccache,

OS: Ubuntu 20:04
Preinstalled with icecream

I'm installing it for the first time and saw we can do it through snap Ubuntu Documentation and installed it

https://snapcraft.io/install/sccache/ubuntu

root@ip-172-31-41-131:/data/kernel/linux-5.12.2# sccache -V
sccache 0.2.2

sccache --show-stats
Compile requests                 2
Compile requests executed        0
Cache hits                       0
Cache misses                     0
Cache timeouts                   0
Cache read errors                0
Forced recaches                  0
Cache write errors               0
Compilation failures             0
Cache errors                     0
Non-cacheable compilations       0
Non-cacheable calls              0
Non-compilation calls            0
Unsupported compiler calls       2
Average cache write          0.000 s
Average cache read miss      0.000 s
Average cache read hit       0.000 s
Cache location             Local disk: "/var/snap/sccache/common/cache"
Cache size                       0 bytes
Max cache size                  10 GiB

Now I wanted to stop and start the server and it fails with the below error.
I cant find any logs on the system either.

 sccache --start-server
Starting sccache server...
error: Server startup error
caused by: Server startup failed: 1

Could you please help me identify the logs or even why it fails to start on Ubuntu 20:04
Also, Can i get some guidance on using it with make. As i run a make just hangs the command

 sccache make -j6

Thank you,
Anish

**Comment by jmakov** [comment]
Have the same problem.

**Comment by Xuanwo** [comment]
> Have the same problem.

Please create a new issue instead of replying to one that was raised in 2021.
