### ISSUE TITLE
Add support for rust coverage (-Z profile)

### ISSUE THREAD

**Issue by pyoor** [mozilla/sccache#1021]
As with #258, it would be great to have support for rust coverage output (gcno).

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1712751

**Comment by sylvestre** [comment]
Seems that it isn't fully fixed:
https://github.com/mozilla/sccache/pull/1052#issuecomment-970217403

**Comment by softmoth** [comment]
This can be closed again (see #1068).
