### ISSUE TITLE
Compile errors hidden because of return code not equal zero of (C) compiler invocation

### ISSUE THREAD

**Issue by flxo** [mozilla/sccache#103]
When a compile error with e.g `gcc` happens it returns with something != 0. The `clang` and `gcc` implementations use `utils::run_input_output` for compilation. The check for the result is 

```
    Box::new(future::result(child)
             .and_then(|child| {
                 wait_with_input_output(child, input).and_then(|output| {
                     if output.status.success() {
                         f_ok(output)
                     } else {
                         f_err(ErrorKind::ProcessError(output))
                     }
                 })
             }))
```

which ends up in treating the result as an error in `server::start_compile_task` (the match in [server.rs:538](https://github.com/mozilla/sccache/blob/master/src/server.rs#L538)). The `stdout` and `stderr` are [discarded and never shown somewhere](https://github.com/mozilla/sccache/blob/master/src/server.rs#L592-L603). The return code is also discarded and the client exits with -2.

**Comment by luser** [comment]
Ah shoot, I guess I broke this in https://github.com/mozilla/sccache/commit/5092b94f29ec6b8b63c09b1d4860073f59bd02a4 . That match needs a branch [like this one](https://github.com/mozilla/sccache/blob/5092b94f29ec6b8b63c09b1d4860073f59bd02a4/src/compiler/compiler.rs#L118) to handle that case.
