### ISSUE TITLE
Support wrapping clang-tidy as well

### ISSUE THREAD

**Issue by mathstuf** [mozilla/sccache#1033]
`clang-tidy` is used in CI and being able to have its linting be cached would help immensely with its turnaround times. Currently, the compilation can be cached, but it'd be nice to have `tidy` output be cached as well.

Of note for the implementation:

  - no `-o` object artifact applies
  - implicit `.clang-tidy` files need to be considered in the hash since these affect what flags are being used internally

**Comment by mathstuf** [comment]
I've checked out `clang-tidy-cache` and submitted some changes. However, I believe that the project is currently targeting a very narrow use case and is not as sophisticated (e.g., when not using `--export-fixes`, it can only cache either the stdout or stderr; a new cache format would be necessary to store and reproduce both). However, I think I can make it work for now. I still think there would be benefits to implementing it here.

**Comment by marcsanfacon** [comment]
I am interested in this one also. I added the support for S3 on clang-tidy-cache and that works well on our case. But when calling clang-tidy, we also call clang++ to compile the code. Being able to have a cache in both level would accelerate things a lot.

**Comment by tojocky** [comment]
Any progress on this item?

**Comment by sylvestre** [comment]
No progress @tojocky

If someone is interested, someone should propose a PR, it isn't part of our priorities/roadmap

**Comment by sylvestre** [comment]
please reopen when a PR is ready

**Comment by mathstuf** [comment]
Can issues being closed this way be labeled so that they can be distinguished from closed-as-fixed and closed-as-rejected issues?

**Comment by sylvestre** [comment]
@mathstuf already the case, I closed them with the "Not planned" tag

**Comment by mathstuf** [comment]
Thanks; the filter predicate is `reason:"not planned"` for anyone curious.
