### ISSUE TITLE
Consider switching out OpenSSL for Rustls

### ISSUE THREAD

**Issue by TobiasDeBruijn** [mozilla/sccache#1065]
Hi,

Thanks for the hard work!

Just an idea, would it be worth it to switch out OpenSSL for Rustls? This would allow for easier portable binaries among other features. `reqwest` can easily be made to use `rustls` rather than `native-tls` (i.e openssl) by disabling the default features and enabling the `rustls-tls` feature.

I noticed that `sccache` also directly depends on Openssl, but I have not checked how and why.

Thanks!

**Comment by drahnr** [comment]
Ref #879 #272
