### ISSUE TITLE
session feature: allow clients to set options for multiple compile jobs

### ISSUE THREAD

**Issue by milahu** [mozilla/sccache#1100]
* client requests a new session from server
* server returns session ID
* client sets compiler options for this session = session options
* client sends compile requests
* session expires after 10 minutes of inactivity

use case: #1091 - session options: list of search-replace strings

benefits:

* no need to set options for every compile job
* server can cache the compiled regex-es

**Comment by luser** [comment]
This would complicate the existing request/response model quite a bit. I don't think I find the use case particularly compelling.

**Comment by milahu** [comment]
another reason: avoid using environment variables for fine-grained/complex configs, since the size of env-vars is limited
