### ISSUE TITLE
Benchmark `v0.3.0` prior to release

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/sccache#1130]
Check that we don't have performance regressions, or that they're manageable.
`cargo bench` may be helpful here, though an end-to-end test can also happen against Firefox CI for a real FF build.

**Comment by luser** [comment]
Historically, "push a try build with the new revision" was the only real performance testing we ever did, but it's a fairly intensive real-world workload so it's not terrible. Testing the actual performance of builds when caching involved is extremely tricky, but @glandium can advise.

**Comment by FooBarWidget** [comment]
How can others help with this issue?

**Comment by mitchhentges** [comment]
I appreciate it, but I'll tackle this one, as it requires some Mozilla CI permissions :)

**Comment by FooBarWidget** [comment]
@mitchhentges Then is there anything else I can do to help 0.3 get released faster?

**Comment by mitchhentges** [comment]
Negative, I'm currently waiting on some CI builds to complete. This is actively being worked on.

**Comment by mitchhentges** [comment]
[Perfherder results can be found here](https://treeherder.mozilla.org/perfherder/compare?originalProject=try&originalRevision=de1e1793af754126dba5bd640ce20665213decc8&newProject=try&newRevision=040eaf16c6aae5e3a793497eaeecd5dabb9c4f76&framework=2&page=1).

I'm seeing a lower cache hit rate, but that's probably because the existing sccache version is leveraging artifacts from other `try` runs.
I think we're good for a release.
