### ISSUE TITLE
Building webrender with sccache doesn't always hit the cache

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/sccache#114]
Doing:
$ cd webrender
$ cargo build
$ cargo clean
$ cargo build

I would expect the second cargo build to hit the cache for everything. This does not appear to be the case. Even more strange is the crates that aren't in the cache changes across runs.

**Comment by luser** [comment]
Whatever the underlying issue here is it's probably the same as #97.

**Comment by jrmuizel** [comment]
Is there a way to do dump all of the inputs to the hash?

**Comment by luser** [comment]
I had a local branch with extra logging for that purpose, I just pushed it: https://github.com/luser/sccache/tree/servo-build-logging

You can start sccache with `RUST_LOG=sccache=trace SCCACHE_ERROR_LOG=sccache.log` to get the log output.

**Comment by luser** [comment]
Let's deal with this in https://github.com/mozilla/sccache/issues/97
