### ISSUE TITLE
Non-cacheable reasons: "-std" (spike in non-cacheable calls for MSVC)

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/sccache#1150]
In [benchmarking sccache `v0.3.0`](https://github.com/mozilla/sccache/issues/1130), I'm seeing [a big jump in "non-cacheable" calls](https://treeherder.mozilla.org/logviewer?job_id=372232397&repo=try&lineNumber=67191).

Looks like the reason is that `-std` is now being considered non-cacheable.
If I were to guess, it's because of [this change](https://github.com/mozilla/sccache/commit/d435d12b112f09c09c45022dfcdd01c4ceae73a0#diff-da7fa688de141fae3e6e48ed82ee4e6f6df5925cdbc0299d5a4e79b6f8775b3aR587).

**Comment by mitchhentges** [comment]
A couple notes:
* Out of all the different build types I tested, this regression [only affected `build-win64/opt`](https://treeherder.mozilla.org/jobs?repo=try&revision=ba74b070e031a92c0a0c7b6645bb9ef1c705cc96&selectedTaskRun=dcqQkcFAS1qs3cxl3fCoEg.0)
* Despite being in docker, doing a `build-win64/opt` build locally is a pain due to using "internal/private" artifacts (VS 15.9.6). However, yesterday I was able to do a full build and whittle down the reproduce criteria
* The current status is that I can repro locally on my host machine (outside of docker) with `sccache clang-cl -Xclang -std=gnu99 <minimal-c-file> -c`, verifying the "uncacheable" results by following up with `sccache --stop-server`.

**Comment by mistmist** [comment]
oh it's likely you identified the right commit - i don't remember why i added it in this place.

[src/compiler/msvc.rs](https://github.com/mozilla/sccache/commit/d435d12b112f09c09c45022dfcdd01c4ceae73a0#diff-da7fa688de141fae3e6e48ed82ee4e6f6df5925cdbc0299d5a4e79b6f8775b3a)
@@ -584,8 +584,8 @@ pub fn parse_arguments(
            use crate::compiler::gcc::ArgData::*;
            let args = match arg.get_data() {
                Some(SplitDwarf) | Some(TestCoverage) | Some(Coverage) | Some(DoCompilation)
-                | Some(Language(_)) | Some(Output(_)) | Some(TooHardFlag) | Some(XClang(_))
-                | Some(TooHard(_)) => cannot_cache!(arg
+               | Some(PedanticFlag) | Some(Standard(_)) | Some(Language(_)) | Some(Output(_))
+               | Some(TooHardFlag) | Some(XClang(_)) | Some(TooHard(_)) => cannot_cache!(arg
                    .flag_str()
                    .unwrap_or("Can't handle complex arguments through clang",)),
                None => match arg {

probably what happened is that there was a warning about new unhandled cases, and i thought "Standard" is similar to "Language", so let's add it to the same case - but this case does "cannot_cache".

guessing, probably before it was UnknownArg and added to common_args?

the same is in gcc.rs - for the extra clang arguments.

so with gcc.rs "clang -std=foo" is cacheable, but "clang -Xclang -std=foo" is not cacheable - but nobody uses the latter form.

so i don't think there's a reason why it's cannot_cache - i'd just move it to another case/common_args.
