### ISSUE TITLE
MSVC preprocessor behaves differently compiling vs. preprocessing only.

### ISSUE THREAD

**Issue by fxb** [mozilla/sccache#116]
This is rather informational, since the actual bug is in MSVC, not sccache. I figured it could be valuable to track this here anyway.

Issue on Microsoft Connect: https://connect.microsoft.com/VisualStudio/feedback/details/3133388

I ran into an issue with builds producing failing unit-test binaries. The resulting binaries from a build using sccache were different than from a build without.

I tracked it down to the following problem with C++11 raw string literals and the MSVC preprocessor:

    static const char *str = R"("//Hello World)";

If compiled, everything will be fine, but if preprocessed only, the above will turn into:

    static const char *str = R"("

This will obviously not compile, but if you have a multiline raw string literal, it will instead have unexpected contents, which is what happened in the unit-test I was debugging.

It seems that the preprocessor is aware of raw string literals when compiling, but won't handle them correctly when preprocessing only. I tried forcing the source file type to C++ using the **/TP** switch, as well as forcing the language standard using the **/std:c++14** and **/std:c++latest** switches, but neither of them fixed the problem.

I tried the same with gcc and clang (**-E** switch). gcc seems to always handle raw string literals, clang will only do it when supplied with **-std=c++11** (or higher).

**Comment by luser** [comment]
I think this should be fixed as of https://github.com/mozilla/sccache/commit/47c08c595c86469756070eb758ac0927bb8690bd since we no longer attempt to compile from the preprocessor output. Thanks for the bug report!
