### ISSUE TITLE
when scheduler is unreachable, sccache panics with "thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/runtime/enter.rs:39:9

### ISSUE THREAD

**Issue by dholbert** [mozilla/sccache#1161]
I'm using a local release build of sccache tip-of-tree (ec1457e8cb508c12d9f177074e20ca89f790489e).  I've got a scheduler configured in my ~/.config/sccache/config, like so:
```
[dist]
scheduler_url = "http://10.0.32.3:10600"
```

My scheduler is usually offline, which is supposed to cause sccache to fall back to a local-only configuration (and indeed that's what happens with e.g. the version of sccache that's bundled with mozilla-central).  But in my own local build of sccache trunk, when I build Firefox while my remote sccache scheduler is offline, I quickly get build failures due to sccache panicking, with logging like this:
> [2022-04-19T20:00:45Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
> 
> thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/runtime/enter.rs:39:9

I'll post a full backtrace in a bit.

**Comment by dholbert** [comment]
I ran this command to start my local `sccache` instance, with loggingg:
```
RUST_BACKTRACE=full SCCACHE_LOG=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 \
 sccache 2>&1 | tee -a /tmp/sccache-with-scheduler.txt
```

And here's the full output that I got:
```
[2022-04-19T20:25:21Z DEBUG sccache::config] Attempting to read config file at "/home/dholbert/.config/sccache/config"
[2022-04-19T20:25:21Z INFO  sccache::server] start_server: port: 4226
[2022-04-19T20:25:21Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
[2022-04-19T20:25:21Z DEBUG reqwest::connect] starting new connection: http://10.0.32.3:10600/
[2022-04-19T20:25:21Z DEBUG hyper::client::connect::http] connecting to 10.0.32.3:10600
[2022-04-19T20:25:21Z WARN  sccache::server] Scheduler address configured, but could not communicate with scheduler
[2022-04-19T20:25:21Z INFO  sccache::cache::cache] No configured caches successful, falling back to default
[2022-04-19T20:25:21Z INFO  sccache::server] server started, listening on port 4226
[2022-04-19T20:25:54Z DEBUG sccache::server] handle_client: compile
[2022-04-19T20:25:54Z INFO  sccache::server] Attempting to recreate the dist client
[2022-04-19T20:25:54Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/dholbert/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/runtime/enter.rs:39:9
stack backtrace:
   0:     0x55ecb37782bd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ecb37782bd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ecb37782bd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ecb37782bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ecb37a352c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55ecb376ede8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55ecb377af67 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ecb377af67 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ecb377af67 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55ecb377ac30 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x55ecb377b6b9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x55ecb364235b - std::panicking::begin_panic::{{closure}}::haa7fc18912ab58d9
  12:     0x55ecb3641ec4 - std::sys_common::backtrace::__rust_end_short_backtrace::h7b2843097b423db3
  13:     0x55ecb303002c - std::panicking::begin_panic::h4f44243796a8604d
  14:     0x55ecb361962c - tokio::runtime::enter::enter::h991c47bab24f7223
  15:     0x55ecb30427d2 - sccache::server::DistClientContainer::create_state::h987681c21a45563a
  16:     0x55ecb3041d84 - sccache::server::DistClientContainer::get_client::h66140863498ae33f
  17:     0x55ecb309238c - sccache::server::SccacheService<C>::handle_compile::{{closure}}::h1edd1c928f8e8911
  18:     0x55ecb30e2a55 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb53c1e2218b1c831
  19:     0x55ecb3272d9d - <futures_util::stream::try_stream::try_flatten::TryFlatten<St> as futures_core::stream::Stream>::poll_next::h030d60d61b60ceb8
  20:     0x55ecb314b8dd - <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll::he87b0d551644b411
  21:     0x55ecb3274a20 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hc4e5824947103208
  22:     0x55ecb3057202 - tokio::runtime::task::harness::poll_future::hc801559f52bdac6e
  23:     0x55ecb304e209 - tokio::runtime::task::harness::Harness<T,S>::poll::h9e53559a8ecd13f5
  24:     0x55ecb363aa00 - std::thread::local::LocalKey<T>::with::hf331564c2ac5c07a
  25:     0x55ecb363152f - tokio::runtime::thread_pool::worker::Context::run_task::h22fa251e6dbaec4a
  26:     0x55ecb3630a30 - tokio::runtime::thread_pool::worker::Context::run::h656a6a68595b6ff7
  27:     0x55ecb364052b - tokio::macros::scoped_tls::ScopedKey<T>::set::h4beeae98c0c9b23a
  28:     0x55ecb363041c - tokio::runtime::thread_pool::worker::run::hbb28ff8921cb0d5d
  29:     0x55ecb361eb61 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h8df13ceb4393ebb5
  30:     0x55ecb3622890 - tokio::runtime::task::harness::Harness<T,S>::poll::hc34ac26f7cc492bc
  31:     0x55ecb3628689 - tokio::runtime::blocking::pool::Inner::run::h4ea432342bda19a2
  32:     0x55ecb3641d76 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1674435625173b1b
  33:     0x55ecb36174ba - core::ops::function::FnOnce::call_once{{vtable.shim}}::h082e3fb090f69957
  34:     0x55ecb3783803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  35:     0x55ecb3783803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  36:     0x55ecb3783803 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7fb678bcd947 - start_thread
                               at ./nptl/./nptl/pthread_create.c:435:8
  38:     0x7fb678c5da44 - __GI___clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
  39:                0x0 - <unknown>
```

**Comment by dholbert** [comment]
Note that the logging does show "connecting to 10.0.32.3:10600" (my scheduler) followed by "Scheduler address configured, but could not communicate with scheduler", so we're picking up on the fact that it's down, which is good.

But then we seem to violate some sort of tokio synchronization invariant the next time we check the scheduler, when we're trying to perform an actual compile job.

**Comment by dholbert** [comment]
For comparison: when I build with the sccache binary that's provided via `./mach bootstrap`, everything is fine.  I do see this snippet of logging periodically in my sccache output, but it seems to be handled properly ("could not communicate with scheduler") each time, with no panics:
```
[2022-04-19T20:31:52Z DEBUG sccache::server] handle_client: compile
[2022-04-19T20:31:52Z INFO  sccache::server] Attempting to recreate the dist client
[2022-04-19T20:31:52Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
[2022-04-19T20:31:52Z DEBUG hyper::client::connect::http] connecting to 10.0.32.3:10600
[2022-04-19T20:31:52Z DEBUG tokio_reactor] adding I/O source: 0
[2022-04-19T20:31:52Z DEBUG tokio_reactor::registration] scheduling Write for: 0
[2022-04-19T20:31:52Z DEBUG tokio_reactor] dropping I/O source: 0
[2022-04-19T20:31:52Z WARN  sccache::server] Scheduler address configured, but could not communicate with scheduler
[2022-04-19T20:31:52Z DEBUG sccache::server] check_compiler: Supported compiler
```

**Comment by dholbert** [comment]
I bisected this this using `git bisect`, and identified the first-bad commit within the sccache repo.

e7099d6c8ad05b7a3994698ca0da92bd8452d687 is the first bad commit -- its commit message is "Migrate to stable Future trait and Tokio 0.2"

This commit involved some changes to sccache's `tokio` dependency.  It seems believable that this would've been where this panic started happening, since the panic is happening in tokio code.

**Comment by mitchhentges** [comment]
Hmm, I can't reproduce this :pensive: 

```
sccache(main) ~/d/sccache % git rev-parse HEAD                                      
ec1457e8cb508c12d9f177074e20ca89f790489e
sccache(main) ~/d/sccache % cargo --version
cargo 1.60.0 (d1fd9fe 2022-03-01)
sccache(main) ~/d/sccache % cat ~/.config/sccache/config 
[dist]
scheduler_url = "http://192.168.1.200:10600"
sccache(main) ~/d/sccache % RUST_BACKTRACE=full SCCACHE_LOG=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 cargo run --bin sccache
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/sccache`
[2022-04-21T17:15:51Z DEBUG sccache::config] Attempting to read config file at "/home/mitch/.config/sccache/config"
[2022-04-21T17:15:51Z INFO  sccache::server] start_server: port: 4226
[2022-04-21T17:15:51Z INFO  sccache::server] Enabling distributed sccache to http://192.168.1.200:10600/
[2022-04-21T17:15:51Z DEBUG reqwest::connect] starting new connection: http://192.168.1.200:10600/
[2022-04-21T17:15:51Z DEBUG hyper::client::connect::http] connecting to 192.168.1.200:10600
[2022-04-21T17:15:56Z WARN  sccache::server] Scheduler address configured, but could not communicate with scheduler
[2022-04-21T17:15:56Z INFO  sccache::cache::cache] No configured caches successful, falling back to default
[2022-04-21T17:15:56Z INFO  sccache::server] server started, listening on port 4226
[2022-04-21T17:16:04Z DEBUG sccache::server] handle_client: compile
[2022-04-21T17:16:04Z DEBUG sccache::compiler::compiler] Found clang
[2022-04-21T17:16:04Z DEBUG sccache::server] check_compiler: Supported compiler
[2022-04-21T17:16:04Z DEBUG sccache::server] parse_arguments: CannotCache(-E): ["--sysroot", "/home/mitch/.mozbuild/sysroot-x86_64-linux-gnu", "/tmp/conftest.jejjusc7.c", "-E"]
...
-----

~/d/firefox % cat mozconfig 
ac_add_options CCACHE=$HOME/dev/sccache/target/release/sccache
~/d/firefox % hg --debug id .                                                   
c95859201259666efcd49533fe7cca1ddea5ab24 tip
~/d/firefox % ./mach configure
 0:01.00 Using Python 3.6.14 from /home/mitch/dev/firefox/obj-x86_64-pc-linux-gnu/_virtualenvs/build/bin/python
 0:01.00 Adding configure options from /home/mitch/dev/firefox/mozconfig
 0:01.00   CCACHE=/home/mitch/dev/sccache/target/release/sccache
 0:01.00 checking for vcs source checkout... hg
 0:01.04 checking for a shell... /usr/bin/sh
 0:01.07 checking for host system type... x86_64-pc-linux-gnu
 0:01.07 checking for target system type... x86_64-pc-linux-gnu
 0:01.45 checking whether cross compiling... no
 0:01.61 checking for Python 3... /home/mitch/dev/firefox/obj-x86_64-pc-linux-gnu/_virtualenvs/build/bin/python (3.6.14)
 0:01.61 checking for hg... /home/mitch/.local/bin/hg
 0:01.72 checking for Mercurial version... 6.1.1
 0:01.89 checking for sparse checkout... no
 0:04.41 checking for wget... /usr/bin/wget
 0:04.41 checking for ccache... /home/mitch/dev/sccache/target/release/sccache
 0:04.43 Using target sysroot in /home/mitch/.mozbuild/sysroot-x86_64-linux-gnu
 0:04.43 Using host sysroot in /home/mitch/.mozbuild/sysroot-x86_64-linux-gnu
 0:04.43 checking for the target C compiler... /home/mitch/.mozbuild/clang/bin/clang
 0:04.48 checking whether the target C compiler can be used... yes
```

-----

Do you have other tricks you can recommend for reproing this?

**Comment by dholbert** [comment]
My .sccache/config:
```
[dist]
scheduler_url = "http://10.0.32.3:10600"

# Used for mapping local toolchains to remote cross-compile toolchains. Empty in
# this example where the client and build server are both Linux.
toolchains = []
# Size of the local toolchain cache, in bytes.
toolchain_cache_size = 1073741824
# This might fix the __u64 error
rewrite_includes_only = false

[dist.auth]
type = "token"
token = "q_1[REDACTED]
```

My mozconfig:
```
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/../obj-debug
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-profiling

ac_add_options --enable-debug --disable-optimize

# Use distributed sccache:
ac_add_options CCACHE=$HOME/bin/sccache
```
(where `$HOME/bin/sccache` is a symlink to `/scratch/work/builds/sccache/target/release/sccache`, which I built with `cargo build --release --features=dist-server`)

**Comment by mitchhentges** [comment]
I've got a local reproduce now :+1:, a couple tweaks were needed:
* This issue is inconsistent, so a full `./mach build` was needed to trigger enough `sccache` calls to cause the issue
* I needed to do this in `release` mode to get an identical error (otherwise I get `Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.` instead) - this matches what you called out in your report, I was just doing `debug` mistakenly

I'll dig in further

**Comment by mitchhentges** [comment]
I've determined the source of the inconsistency: it isn't a threading/race-condition situation, it's based on [this timeout](https://github.com/mozilla/sccache/blob/main/src/server.rs#L75).
The timer is started when the sccache daemon is first started.
The first compile to come through _once the timeout expires_ triggers the error.

Accordingly, making `DIST_CLIENT_RECREATE_TIMEOUT` simply `0` makes the failure consistent on first compile.

**Comment by mitchhentges** [comment]
Based on the error message and the context, the issue seems clear: we're creating a blocking (non-async) `reqwest` client in the `Client::new()` function, which is _sometimes_ called from an `async` context (such as when the daemon has received a compile request, and it decides it's time to try to talk to the remote scheduler again).

The root problem is that [tokio runtimes can't be nested](https://stackoverflow.com/questions/65426683/why-does-tokio-return-the-error-cannot-drop-a-runtime-in-a-context-where-blocki). Sure, that makes sense.
What I don't understand is how this worked so far - did `tokio` use to ignore nested-async-runtime issues? :thinking:

**Comment by mitchhentges** [comment]
>  What I don't understand is how this worked so far - did tokio use to ignore nested-async-runtime issues? thinking

Looks like `reqwest=0.9`'s blocking implementation used [`futures`](https://crates.io/crates/futures/0.1.31) under the hood with a more simple "blocking" implementation. It _did_ have [thread-local state](https://github.com/rust-lang/futures-rs/blob/0.1.31/src/task_impl/std/mod.rs#L475-L479), but that was separate from our `sccache`-app-level `tokio` runtime.

`request=0.10` uses [`tokio`](https://crates.io/crates/tokio/0.2.25) under-the-hood, and creates a local `tokio` runtime when doing blocking operations. `tokio` doesn't like nested runtimes, so it raises an error if its [thread-local state](https://github.com/tokio-rs/tokio/blob/tokio-0.2.25/tokio/src/runtime/enter.rs#L24) is used twice at the same time (nested).

At the moment, my knee-jerk reaction here is that we shouldn't be doing blocking work in an async context - as the error says. Accordingly, we shouldn't have block a blocking _and_ an async `reqwest` client with every sccache dist client - most likely, we should just have the async client.
However, this requires larger migration work, which I can't commit to at the moment (besides, there could be a hidden underlying use case for the blocking reqwest client which invalidates my assumption anyways. Perhaps then we investigate deferring blocking-client-initialization until that moment. Either way, this is a deferrable problem).

So, I think that the short-term solution is to downgrade `reqwest`.

**Comment by mitchhentges** [comment]
>  What I don't understand is how this worked so far - did tokio use to ignore nested-async-runtime issues? thinking

Looks like `reqwest=0.9`'s blocking implementation used [`futures`](https://crates.io/crates/futures/0.1.31) under the hood with a more simple "blocking" implementation. It _did_ have [thread-local state](https://github.com/rust-lang/futures-rs/blob/0.1.31/src/task_impl/std/mod.rs#L475-L479), but that was separate from our `sccache`-app-level `tokio` runtime.

`request=0.10` uses [`tokio`](https://crates.io/crates/tokio/0.2.25) under-the-hood, and creates a local `tokio` runtime when doing blocking operations. `tokio` doesn't like nested runtimes, so it raises an error if its [thread-local state](https://github.com/tokio-rs/tokio/blob/tokio-0.2.25/tokio/src/runtime/enter.rs#L24) is used twice at the same time (nested).

At the moment, my knee-jerk reaction here is that we shouldn't be doing blocking work in an async context - as the error says. Accordingly, we shouldn't have block a blocking _and_ an async `reqwest` client with every sccache dist client - most likely, we should just have the async client.
However, this requires larger migration work, which I can't commit to at the moment (besides, there could be a hidden underlying use case for the blocking reqwest client which invalidates my assumption anyways. Perhaps then we investigate deferring blocking-client-initialization until that moment. Either way, this is a deferrable problem).

So, I think that the short-term solution is to downgrade `reqwest`. If this proves too tricky (due to `futures` compat, or anything else) then we can back out `e7099d6c8ad05b7a3994698ca0da92bd8452d687` for the `v0.3.0` release.

**Comment by mitchhentges** [comment]
[Hmm](https://github.com/mozilla/sccache/blob/main/src/dist/http.rs#L1078-L1079):
```
// TODO: this should really only use the async client, but reqwest async bodies are extremely limited
 // and only support owned bytes, which means the whole toolchain would end up in memory
```

**Comment by mitchhentges** [comment]
[Hmm](https://github.com/mozilla/sccache/blob/main/src/dist/http.rs#L1078-L1079):
```
// TODO: this should really only use the async client, but reqwest async bodies are extremely limited
// and only support owned bytes, which means the whole toolchain would end up in memory
```
I bet we can use [`Body::wrap_stream()`](https://docs.rs/reqwest/latest/reqwest/struct.Body.html#method.wrap_stream) here to have the best of both worlds.

**Comment by dholbert** [comment]
I see a fix landed here -- thanks!

But, hmm -- I just tried to test this with the updated sccache tip, and I'm now just getting a hang instead of a panic:
```
[2022-04-26T19:27:50Z DEBUG sccache::server] handle_client: compile
[2022-04-26T19:27:50Z INFO  sccache::server] Attempting to recreate the dist client
[2022-04-26T19:27:50Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
[2022-04-26T19:27:51Z DEBUG reqwest::connect] starting new connection: http://10.0.32.3:10600/
[2022-04-26T19:27:51Z DEBUG hyper::client::connect::http] connecting to 10.0.32.3:10600
[... no output after this ...]
```

@mitchhentges  can you reproduce?

**Comment by dholbert** [comment]
My STR, with tip-of-tree locally-built release sccache (and with a scheduled configured but not actively running):

(1) `RUST_BACKTRACE=full SCCACHE_LOG=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache`
(2) Wait 1 minute (to wait out the 30-second `DIST_CLIENT_RECREATE_TIMEOUT` mentioned above)
(3) In another terminal, run `./mach configure` from your mozilla-central clone.

ACTUAL RESULTS:
* mach configure hangs at ` 0:03.81 checking for the target C compiler... /scratch/work/builds/.mozbuild/clang/bin/clang`
* the sccache process has this initial output (from before I ran `./mach configure`):
```
[2022-04-26T19:52:24Z DEBUG sccache::config] Attempting to read config file at "/home/dholbert/.config/sccache/config"
[2022-04-26T19:52:24Z INFO  sccache::server] start_server: port: 4226
[2022-04-26T19:52:24Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
[2022-04-26T19:52:24Z DEBUG reqwest::connect] starting new connection: http://10.0.32.3:10600/
[2022-04-26T19:52:24Z DEBUG hyper::client::connect::http] connecting to 10.0.32.3:10600
[2022-04-26T19:52:24Z WARN  sccache::server] Scheduler address configured, but could not communicate with scheduler
[2022-04-26T19:52:24Z INFO  sccache::cache::cache] No configured caches successful, falling back to default
[2022-04-26T19:52:24Z INFO  sccache::server] server started, listening on port 4226
```
...followed by this output after I ran `./mach configure:`
```
[2022-04-26T19:53:44Z DEBUG sccache::server] handle_client: compile
[2022-04-26T19:53:44Z INFO  sccache::server] Attempting to recreate the dist client
[2022-04-26T19:53:44Z INFO  sccache::server] Enabling distributed sccache to http://10.0.32.3:10600/
[2022-04-26T19:53:44Z DEBUG reqwest::connect] starting new connection: http://10.0.32.3:10600/
[2022-04-26T19:53:44Z DEBUG hyper::client::connect::http] connecting to 10.0.32.3:10600
```
...and it just hangs at that point, with no further activity/output.

**Comment by mitchhentges** [comment]
Shoot, I'm guessing that [this part of the solution](https://github.com/mozilla/sccache/commit/58f9ee2794b79f05dff33551f974e28ed25b71d4#diff-48d27698cc708c7efe770fd897e4885efaa0a15cae30d54936068603ba03bbd9R367-R373) is causing the lock-up, hmm. I'll see how `cachepot` solves this.

**Comment by mitchhentges** [comment]
I've reproduced this exact bug in [cachepot (near their async `reqwest` migration) at  `19d8487f059777d72f20cc018530019ed1f16683`](https://github.com/paritytech/cachepot/tree/19d8487f059777d72f20cc018530019ed1f16683).
Looks like they worked around the hanging issue by porting [`dist-client` to be `async`](https://github.com/paritytech/cachepot/commit/ecba086663c43abcfcc323389bc45b8fd297e844). I'll see how cherry-pick-able that commit is.
