### ISSUE TITLE
After installing sccache cargo stopped working

### ISSUE THREAD

**Issue by TheHolyTachanka** [mozilla/sccache#1165]
When i try to run this:
```
cargo run
```
I get this Error its only happening after i installed sccache i cant build or run any .rs file

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `/home/USERNAME/.cargo/bin/sccache rustc - --crate-name ___ --print=file-names -Clink-arg=-fuse-ld=lld -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)
```

**Comment by Icelk** [comment]
It looks like you haven't specified the correct path for sccache, or it isn't marked as an executable.

**Comment by dholbert** [comment]
Likely both of the following are true:
(a) you have sccache configured as your rustc_wrapper, either through the RUSTC_WRAPPER environmental variable, or perhaps in `$HOME/.cargo/config`
(b) you have an error in that configuration (possibly you specified the incorrect path as lcelk said)

You can probably fix things in the short term by undoing (a) (i.e. not using sccache automatically); but really to address the issue, you want to look into (b).

**Comment by TheHolyTachanka** [comment]
i managed to fix it forgot about this thread thx anyway
