### ISSUE TITLE
questioning about  : HTTP storage backend 

### ISSUE THREAD

**Issue by Lambourl** [mozilla/sccache#1171]
Hello everyone, 

I have a question, I can't find the information.
Is it possible with sccache to have an HTTP storage backend? 
I know that in ccache it is possible (see: https://ccache.dev/manual/4.6.html#_http_storage_backend ). 
And if it is possible, could you explain it to me or add it to the documentation.
And if it is possible, would it also work with an HTTPS storage backend? 

If none of this is possible, you can of course close my issue.

Thank you in advance for your help

**Comment by nmattia** [comment]
Hi,

Any update on this? I'd be quite interested in an http storage backend.

**Comment by dtretyakov** [comment]
It will be great to support an HTTP backend with ability to configure HTTP request authentication.

And It looks like it could be implemented on top of `opendal` library (https://github.com/mozilla/sccache/issues/1483).

@Xuanwo maybe it could be the next storage implemented on top of it?

**Comment by Xuanwo** [comment]
The `HTTP Storage Backend` mentioned here is `WebDAV`. OpenDAL will implement `WebDAV` support in https://github.com/datafuselabs/opendal/issues/370~

**Comment by dtretyakov** [comment]
@Xuanwo could not existing "http" storage in `opendal` cover these needs? Or works differently with HTTP request paths/methods?

https://opendal.databend.rs/opendal/services/http/index.html

**Comment by Xuanwo** [comment]
> could not existing "http" service in `opendal` cover these needs? Or works differently with HTTP request paths/methods?

No. `http` backend is a read-only service that works on any HTTP server. To make cache work, we should support `PUT`, `DELETE` and other methods that supported by `WebDAV` protocol.

**Comment by Xuanwo** [comment]
> https://opendal.databend.rs/opendal/services/http/index.html

And sorry for the missing leading comeents of HTTP backend, I will fix them in https://github.com/datafuselabs/opendal/issues/1238

**Comment by Xuanwo** [comment]
cc @Lambourl @dtretyakov @nmattia, https://github.com/mozilla/sccache/pull/1597 will add this feature, would you like to try it and give us feedback?

**Comment by nmattia** [comment]
@Xuanwo thanks for the ping! I won't be able to test this any time soon unfortuntaely
