### ISSUE TITLE
Please document how to setup Google Cloud Storage (without local json key)

### ISSUE THREAD

**Issue by Krishnacore** [mozilla/sccache#1172]
It is pretty clear how to use GCP by specifying the path to the local json key. But I've been trying to figure out how to use the SCCACHE_GCS_OAUTH_URL (or SCCACHE_GCS_CREDENTIALS_URL) variable for two days now. Any help or link where to find this would be appreciated

**Comment by dcaba** [comment]
duplicated? https://github.com/mozilla/sccache/issues/870

**Comment by sylvestre** [comment]
fixed by 
https://github.com/mozilla/sccache/pull/1108/files
