### ISSUE TITLE
MSVC - cannot cache with "@" (command files)

### ISSUE THREAD

**Issue by donalmacc** [mozilla/sccache#1183]
Hi,

I've been trying out sccache for an MSVC based project with a custom build system that uses [command files](https://docs.microsoft.com/en-us/cpp/build/reference/cl-command-files?view=msvc-170) for all the arguments, but it seems that sccache doesn't cache any call that uses the @ syntax.  After running my test project, this is the output from sccache.

```
sccache -s
Compile requests                     39
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                  39
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
@                                    39
```

The format of every one of the compile calls is:
`sccache "C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" @..\build\Win64\foo.cpp.command`

Is there any planned support for command files in MSVC?

**Comment by exoosh** [comment]
See #107 and related (e.g. #192, #378, #1082) tickets and pull requests as well as [jasonwhite/sccache on branch `msvc-response-files`](https://github.com/jasonwhite/sccache/tree/msvc-response-files) ...

PR #192 is especially sad.
