### ISSUE TITLE
How to specify a cooporate web proxy?

### ISSUE THREAD

**Issue by fhaefemeier** [mozilla/sccache#1228]
I have to run my rust builds with sccache using S3 behind a web proxy. How can I declare the proxy?

I tried to set it via shell environment (as usual) but it isn't recognized by sccache:
```
export RUSTC_WRAPPER="sccache"
export HTTPS_PROXY=http://1.1.1.1:3128
cargo install
```

**Comment by Xuanwo** [comment]
Should work on https://github.com/mozilla/sccache/releases/tag/v0.4.0-pre.3, please have a try.

**Comment by fhaefemeier** [comment]
Is working now. Thanks!
But the release was only compilable if I not disable default features and enable specific ones. I will open a new ticket.

**Comment by Xuanwo** [comment]
This issue has been resolved. Please help close it, thanks @sylvestre
