### ISSUE TITLE
Support caching Rust compilation with `-l static=foo`

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#123]
I punted on caching any Rust compilation with `-l` in it in the original implementation, but [@alexcrichton pointed out](https://github.com/mozilla/sccache/issues/88#issuecomment-288729305) that supporting just `-l static=foo` should be straightforward.

**Comment by luser** [comment]
Just for reference, I built servo with sccache on a slightly out-of-date servo rev (https://github.com/servo/servo/commit/bb4ea82b236ebcd7cc6416262045a91438beb089) and the sccache logs showed 127 `CannotCache` lines. Doing a little grep-and-sed on the log showed:
```
$ rg CannotCache /tmp/sccache.log | sed -re 's/.*CannotCache\((.+)\).*/\1/' | sort | uniq -c
     22 -l
     36 multiple input files
     50 no output file
      1 stdin
     18 unknown source extension
```
So there are 22 rust compilations that weren't cacheable due to passing `-l`.

**Comment by luser** [comment]
I wrote a little Python script to filter those down to just invocations with `-l static=something`, and those account for 12/22.

**Comment by alexcrichton** [comment]
Ah yeah `-lstatic` sould be pretty easy to support. The logic basically looks like:

* Take a look at all `-L` arguments
* Strip out everything that's not `-L /foo` and `-L native=/foo`, e.g. strip `dependency=` and `framework=`, etc.
* For all of those paths iterate them in order
* For linking the staticlib `foo`, find the first of `libfoo.a`, `foo.lib`, `foo.a`, and return that.

Or at least IIRC that's the rough algorithm rustc uses!

**Comment by luser** [comment]
Fixed in https://github.com/mozilla/sccache/pull/125
