### ISSUE TITLE
Recognize .C as C++ for gcc/clang

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#127]
I saw this in sccache logs building servo, we currently produce `CannotCache(unknown source extension)`. I think these are all autoconf tests that we wouldn't cache anyway for other reasons, but we can at least mostly do the right thing here.

**Comment by mathstuf** [comment]
Duplicate of #586 which is fixed via #595.

**Comment by nnethercote** [comment]
This issue can be closed, but I don't have permission to close it.
