### ISSUE TITLE
Handle default object file name for C compilation

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#128]
We currently return `CannotCache(no output file)` if a C compilation doesn't include `-o output` or the MSVC equivalent. Compilers use pretty simple rules to generate the output file here, we should just support that case. This shows up a lot in sccache logs from building servo because autoconf does this a lot. I'm not sure it will help much, but it should be easy to support and there's no good reason not to.

[GCC's documentation](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#Overall-Options) says "By default, the object file name for a source file is made by replacing the suffix ‘.c’, ‘.i’, ‘.s’, etc., with ‘.o’. "  [MSVC's documentation](https://docs.microsoft.com/en-us/cpp/build/reference/fo-object-file-name) says "If you do not use this option, the object file uses the base name of the source file and the .obj extension." Related: @vvuk mentioned to me that he had hit an issue because he was building a project with MSVC+sccache that used `-Fosome\dir\`, which I didn't know was a thing you could do (even though it's mentioned in the docs I just linked), which causes MSVC to generate the object file in `some\dir` with the default object file name.

**Comment by F3real** [comment]
Hey Ted,
I'll look into this.

**Comment by vvuk** [comment]
The windows `-Fo` fix is at https://github.com/vvuk/sccache/commit/9ed9a78d09105ff70b6bebeb94ce1c7f34200785#diff-885eee6e54f6200dcc65474f2a44989fR293 -- should be easy to also handle a null output_arg there and do the replacement.
