### ISSUE TITLE
Use `bytes` crate for buffering data

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#13]
I left a pair of FIXME comments in the server source:
https://github.com/luser/sccache2/blob/1fb11fc53ec7ddae4663ea6dea6ad3afa29b01a9/src/server.rs#L695
https://github.com/luser/sccache2/blob/1fb11fc53ec7ddae4663ea6dea6ad3afa29b01a9/src/server.rs#L742

I didn't get around to sorting those out, but it'd be nice to use the `bytes` crate for buffering data:
https://github.com/carllerche/bytes

We probably want to use `MutByteBuf` in this case:
http://carllerche.github.io/bytes/bytes/buf/struct.MutByteBuf.html

**Comment by F3real** [comment]
I'll start working on this.

**Comment by glandium** [comment]
I'm not sure what the expected benefit is from using the bytes crate here. Why not just use [std::io::BufReader](https://doc.rust-lang.org/stable/std/io/struct.BufReader.html) ?

**Comment by luser** [comment]
We can't use `BufReader` with mio. This is mostly just to clean up the code instead of doing finicky work with `Vec<u8>`, since we have to read a full protobuf message before we can parse it.

**Comment by luser** [comment]
The tokio refactor in #68 made us use EasyBuf (which is part of tokio-core), so this is not an issue anymore.
