### ISSUE TITLE
Change type of TEN_GIGS constants to avoid overflow on  32bit OS

### ISSUE THREAD

**Issue by F3real** [mozilla/sccache#131]
Running cargo test on 32bit OS gives:

> warning: constant evaluation error: attempt to multiply with overflow. This will become a HARD ERROR in the future
  --> src/cache/cache.rs:51:25
   |
51 | const TEN_GIGS: usize = 10 * 1024 * 1024 * 1024;
   |                         ^^^^^^^^^^^^^^^^^^^^^^^
   |

This will also require code changes in:
https://github.com/luser/lru-cache/blob/cache-meter-trait/src/lib.rs#L208

**Comment by posix4e** [comment]
Any reason why not just make this 1GB in 32 bit mode?

**Comment by luser** [comment]
It's not a great default, but it probably doesn't matter all that much. If we don't fix this to use a u64 all the way down then local disk caching is not going to be very useful in a 32-bit sccache, in any event. Do you have a real need for a 32-bit sccache binary?

**Comment by na-g** [comment]
While this isn't my problem, I will point out that many of the SoC linux boards run 32 Bit OSes, e.g. Raspberry Pi (even on the 64 bit hardware version).

**Comment by posix4e** [comment]
My use case isn't that important, but... *shrug*

**Comment by luser** [comment]
That's fair. So as per the first comment here, we'd need to change the type of that constant from `usize` to `u64` and then similarly change the types down through `LruDiskCache` and our forked copy of `LruCache`.

**Comment by posix4e** [comment]
Happy to make it happen

**Comment by luser** [comment]
Feel free! I am not opposed to making that change, especially since I decided to fork lru-cache.

**Comment by luser** [comment]
Fixed by https://github.com/mozilla/sccache/pull/212
