### ISSUE TITLE
running rustc under wrapper is only supported when invoked by cargo

### ISSUE THREAD

**Issue by tofay** [mozilla/sccache#1314]
https://github.com/mozilla/sccache/pull/1280 adds support for using sccache when rustc is wrapped by another command, e.g `/path/to/wrapper rustc`.

This allows cargo users to use sccache as a rustc wrapper, and use another tool as a rustc wrapper for workspace members, resulting in commands like `sccache /path/to/workspace/wrapper rustc`.

This issue tracks the fact that running rustc with a wrapper is only supported by sccache when run under cargo (and hence the `CARGO` environment variable is defined). If a similar approach is taken by other build systems then sccache will fail to detect the compiler.

**Comment by lcmgh** [comment]
Shouldn't this be closed as the PR is merged?

**Comment by drahnr** [comment]
That's correct, closed with #1280
