### ISSUE TITLE
please consider using crate local-encoding-ng (instead of local-encoding)

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/sccache#1334]
The crate local-encoding is quite dated, and pulls in a range of dated dependencies including an ancient rand and a markdown parser.

Please consider replacing with local-encoding-ng which looks like a drop-in replacement without that baggage.

**Comment by Xanewok** [comment]
Fixed with https://github.com/mozilla/sccache/pull/1376, which removes `local-encoding` altogether.
