### ISSUE TITLE
License headers vs SPDX identifiers

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#1357]
Is there a particular reason or legal requirement to have the 30 lines headers in all files? The somewhat recent development on SPDX license identifiers is supposedly there to simplify this which would reduce it to 1 line (not counting the copyright holders).

**Comment by sylvestre** [comment]
Mozilla has this requirement: https://www.mozilla.org/en-US/MPL/headers/

**Comment by glandium** [comment]
The Apache 2.0 header is "only" 11 lines, plus the copyright line and spacers line, that's 14 lines total, where did you see 30 lines headers?
