### ISSUE TITLE
Does sccache support CMake?

### ISSUE THREAD

**Issue by mikejack07** [mozilla/sccache#1358]
Hi,

I am evaluating distributed build systems to be used in my team. We use windows machines and use CMake too in our projects.
Does sccache support CMake? Since we use CMake, I want to make sure sccache supports CMake before investing more time into it.

Thanks and regards

**Comment by sylvestre** [comment]
please don't use issues to ask questions ... especially when the answer is easy to get
search cmake on:
https://github.com/mozilla/sccache/blob/main/README.md
