### ISSUE TITLE
No release assets for 0.3.1

### ISSUE THREAD

**Issue by liskin** [mozilla/sccache#1399]
https://github.com/mozilla/sccache/releases/tag/0.3.1 doesn't have any assets (binaries). :-(
Possibly caused by this failure: https://github.com/mozilla/sccache/actions/runs/3454659136/jobs/5766193075 ?

(Also, the tag is without the "v" prefix. There was "v0.3.0", and then just "0.3.1".)

**Comment by sylvestre** [comment]
yeah, looks like we (Mozilla) have updated the permissions. 

The error is:
```
pre_receive protected tag 'v0.3.1' check failed:
  You're not authorized to create a tag
```

I will follow up

**Comment by sylvestre** [comment]
Fixed, i created the tag myself

**Comment by liskin** [comment]
Awesome, thanks!

(I'll note that it was kind of nice having a human-written changelog for the release, and that has now been lost, but having those assets is more important. Still, is there a changelog anywhere at all?)

**Comment by sylvestre** [comment]
updated:
https://github.com/mozilla/sccache/releases/tag/v0.3.1
