### ISSUE TITLE
proposal: Use opendal to handle the cache storage operations

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1404]
## Background

Hi, I'm the maintainer of [opendal](https://github.com/datafuselabs/opendal), a rust lib that focuses on accessing data freely, painlessly, and efficiently.

OpenDAL now supports almost all storage services, including `s3`, `gcs`, `azblob`, `oss`, `obs`, `hdfs`, `redis`, `fs` and so on.

```rust
use anyhow::Result;
use opendal::Operator;
use opendal::Scheme;

#[tokio::main]
async fn main() -> Result<()> {
    // Init Operator
    let op = Operator::from_env(Scheme::S3)?;

    // Create object handler.
    let o = op.object("test_file");

    // Write data info object;
    o.write("Hello, World!").await?;

    // Read data from the object;
    let bs = o.read().await?;

    // Delete object.
    o.delete().await?;

    Ok(())
}
```

I came across `sccache` last week and found opendal is a great choice for `sccache`, which can help resolve many issues like https://github.com/mozilla/sccache/issues/1384, https://github.com/mozilla/sccache/issues/1180, https://github.com/mozilla/sccache/issues/1167.

Apart from various storage backend supports, opendal also has the following benefits:

- Full observability support: [logging](https://opendal.databend.rs/opendal/layers/struct.LoggingLayer.html), [tracing](https://opendal.databend.rs/opendal/layers/struct.TracingLayer.html), [metrics](https://opendal.databend.rs/opendal/layers/struct.MetricsLayer.html).
- Automatic [retry](https://opendal.databend.rs/opendal/layers/struct.RetryLayer.html) support
- Used in production by databases like [databend](https://github.com/datafuselabs/databend/)

## Proposal

So I propose to replace the storage implementation with opendal instead.

I built a quick demo here: https://github.com/Xuanwo/cccache/tree/debug. Most of the change will be like:

```diff
- let credentials = self
-     .provider
-     .credentials()
-     .await
-     .context("failed to get AWS credentials")?;
- 
- let bucket = self.bucket.clone();
- let _ = bucket
-     .put(&key, data, &credentials)
-     .await
-     .context("failed to put cache entry in s3")?;
+ self.op.object(&key).write(data).await?;
```

If this proposal is accepted, I plan to

- Replace them one by one (s3, gcs, ...)
- Make sure all existing config work as before
- Then adding new services support

---

Any comments are welcome! Thanks in advance.

**Comment by sylvestre** [comment]
Looks interesting
Did you look at the performance impact?

**Comment by sylvestre** [comment]
Also, do you know any project using opendal ?

**Comment by Xuanwo** [comment]
> Did you look at the performance impact?

Take s3 as an example, `read` and `write` are mapped to `put_obejct` and `get_object` directly. I think no performance impact will be observed by users.

> Also, do you know any project using opendal ?

[databend](https://github.com/datafuselabs/databend/) is a cloud data warehouse which uses opendal heavily.

**Comment by Xuanwo** [comment]
> Sure but I would like to see some benchmark :) The devil is in the details

Agreed.

How about this benchmark plan?

- Compile different projects with no cache, sccache and sccache (opendal powered)
- Recode the finish durations for analysis.

> Are you aware of other projects?

Small project like [deepeth/mars](https://github.com/deepeth/mars).

No others so far to my knowledge. I'm seeking to expand the usage too.

**Comment by PsiACE** [comment]
opendal was created precisely to simplify access to data.

I think opendal is a good fit for sccache, taking over all the data storage services that might need to be considered without having to bother with abstractions and complex dependencies. And vice versa, sccache is a good project to test and validate opendal designs and implementations. 

Although there may be a lack of more projects using opendal at the moment, I thought it would be worthwhile to try it out on sccache.

**Comment by sylvestre** [comment]
Sure, I just don't want to add a critical dependency which could be unmaintained in a few months

**Comment by Xuanwo** [comment]
I did a simple benchmark.

## Setup

Test with [databend](https://github.com/datafuselabs/databend/) at commit [b24be85](https://github.com/datafuselabs/databend/commit/b24be852275a83cbed52203d8cf8b814d19c3f64)

Both of sccache and cccache are using the same local minio with different bucket.

### Sccache

sccache v0.3.1, built with release profile

```shell
export RUSTC_WRAPPER=/home/xuanwo/Code/mozilla/sccache/target/release/sccache
export CARGO_INCREMENTAL=0

export SCCACHE_BUCKET=sccache
export SCCACHE_ENDPOINT=127.0.0.1:9900

export AWS_ACCESS_KEY_ID=minioadmin 
export AWS_SECRET_ACCESS_KEY=minioadmin

cargo build
```

### Cccache

Cccache at commit [c1a725f0](https://github.com/Xuanwo/cccache/commit/c1a725f09116d6675f0a14566a49e8d9ad383c6b), built with release profile

> `cccache` remove the dist-server related features and is built with the latest stable rust.

```shell
export RUSTC_WRAPPER=/home/xuanwo/Code/xuanwo/cccache/target/release/cccache
export CARGO_INCREMENTAL=0

export SCCACHE_BUCKET=cccache
export SCCACHE_ENDPOINT=127.0.0.1:9900

export AWS_ACCESS_KEY_ID=minioadmin 
export AWS_SECRET_ACCESS_KEY=minioadmin

cargo build
```

## Result

### Without any cache

```shell
Finished dev [unoptimized + debuginfo] target(s) in 2m 45s
cargo build  1722.26s user 174.20s system 1147% cpu 2:45.30 total
```

### With sccache

First build

```shell
Finished dev [unoptimized + debuginfo] target(s) in 3m 47s
cargo build  412.81s user 76.77s system 215% cpu 3:47.27 total
```

Build after cargo clean

```shell
Finished dev [unoptimized + debuginfo] target(s) in 2m 38s
cargo build  325.56s user 59.88s system 243% cpu 2:38.17 total
```

### With cccache

First build

```shell
Finished dev [unoptimized + debuginfo] target(s) in 3m 34s
cargo build  557.05s user 99.79s system 305% cpu 3:34.94 total
```

Build after cargo clean

```shell
Finished dev [unoptimized + debuginfo] target(s) in 2m 31s
cargo build  427.92s user 70.19s system 327% cpu 2:31.96 total
```

---

The result is stable within couple of seconds.

**Comment by sylvestre** [comment]
Could you please try benchmark with [hyperfine](https://crates.io/crates/hyperfine) ? 
I don't trust single run compilation

**Comment by Xuanwo** [comment]
On the same setup:

## Sccache

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `cargo clean; cargo build` | 185.520 ± 6.944 | 176.236 | 198.428 | 1.00 |

## Cccache

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `cargo clean; cargo build` | 169.907 ± 5.350 | 160.920 | 177.485 | 1.00 |

**Comment by Xuanwo** [comment]
> Sure, I just don't want to add a critical dependency which could be unmaintained in a few months

We have great news related to this to share!

The newly open-source project [greptimedb](https://github.com/GreptimeTeam/greptimedb) is using OpenDAL too.

![image](https://user-images.githubusercontent.com/5351546/202169692-b9728a9d-28ce-4828-a929-0c3aa1ab78b3.png)

@sunng87 from the @GreptimeTeam is one of the contributors to OpenDAL.

---

We do know the concern of the long-term maintenance status of the project. And we are working hard to grow our community and introduce more maintainers (outside of our own team) to address that.

**Comment by Xuanwo** [comment]
In PR https://github.com/mozilla/sccache/pull/1412 I built a quick demo in about 5 minutes, please take a look and leave any comments so we can improve.

**Comment by kesavkolla** [comment]
@Xuanwo does OpenDAL uses connection pool? All the calls will be to the same backend S3. It would be nice to re-use the connections so that whole SSL handshakes are minimized and also avoiding any DNS lookups.

**Comment by Xuanwo** [comment]
> does OpenDAL uses connection pool?

Yes.

> also avoiding any DNS lookups

We also support caching DNS lookups by enabling `trust-dns` features.

**Comment by sylvestre** [comment]
reopening as we "only" have s3 & azure.

@Xuanwo  I would be curious if you could do GCS next. I would like to test it for Firefox CI.

**Comment by Xuanwo** [comment]
> @Xuanwo I would be curious if you could do GCS next. I would like to test it for Firefox CI.

Done by https://github.com/mozilla/sccache/pull/1474

**Comment by Xuanwo** [comment]
Most opendal related work has been done. Let's close this issue.
