### ISSUE TITLE
sccache@v0.3.1 s3 doesn't support AWS4-HMAC-SHA256 (already fixed on master)

### ISSUE THREAD

**Issue by arriven** [mozilla/sccache#1414]
sccache v0.3.1 uses simple hmac signature for authentication which is not supported by aws <https://github.com/mozilla/sccache/blob/41e408d3e22d3c5a03cc622c93e9348ef80df140/src/simples3/s3.rs#L40-L49>

Using it results in a following error

```xml
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>"
```

The issue seems to be fixed on latest master which uses new s3 backend. Can we get a new tagged version so that the fix is available with `cargo install` and `cargo binstall`?

**Comment by sylvestre** [comment]
Not yet, we need to bench the changes and land https://github.com/mozilla/sccache/pull/1409
Sorry
