### ISSUE TITLE
The image of "Matrix" in the README does not load.

### ISSUE THREAD

**Issue by alexey-milovidov** [mozilla/sccache#1416]
![Screenshot_20221122_210207](https://user-images.githubusercontent.com/18581488/203410181-c94f2b98-d3fa-46cf-a266-ed1e8b7ee711.png)

**Comment by sylvestre** [comment]
yeah, patches welcome :)

**Comment by cgsheeh** [comment]
![image](https://user-images.githubusercontent.com/12172761/203416209-12b0b459-73e4-4d21-8b5f-f1e92dd9ec2f.png)
