### ISSUE TITLE
sccache fails when running perl?

### ISSUE THREAD

**Issue by MisterEggnog** [mozilla/sccache#1426]
sccache fails when building the [ring](https://github.com/briansmith/ring) crate, I am not certain of the reason or if this is even on sccache's end.
What I have found inspecting the error logs that it seems to fail when invoking perl.
This seems to be an issue with sscache as it compiles when I deactivate sccache.

[ring.log](https://github.com/mozilla/sccache/files/10087478/ring.log)

**Comment by sylvestre** [comment]
Would be nice to have a small test case which shows the issue.
thanks

**Comment by MisterEggnog** [comment]
I do not know how sscache's test cases work, (for now,) but when I attempted to compile sscache I received a similar error from the same library as before*.
Is there a way to locally override sscache without needing to turn it off globally?

Here's a copy of the [error.log](https://github.com/mozilla/sccache/files/10087579/sscache_build.log) when building the library.

*However, this one does not seem to invoke perl.

**Comment by sylvestre** [comment]
Please don't upload full log. Strip the content and paste the relevant information in the bug.
It is much better for search.
thanks

**Comment by drahnr** [comment]
If `perl` is required, it shouldn't be pulled into the needed files for compilation for the artifact. That would be the responsibility of `build.rs` to declare the `perl` binary as `cargo:rerun-if-changed=path/to/perl`. Note that this is awkward, but assuming `perl` being present and not telling `build.rs` that any change there should propagate is incoherent. And that's ultimately what sccache handles in figuring out what to include in the minimal build env.

Note that this would only work if the builder and the host are the same linux distro essentially. Currently specifying this is not possible.

**Comment by MisterEggnog** [comment]
I can file an issue with [ring](https://github.com/briansmith/ring) if you do not think this issue is related to sscache.

I realize I did not consider the possibility this is related to current distribution I'm using, if that is the case I'll close this.

> Please don't upload full log. Strip the content and paste the relevant information in the bug. It is much better for search. thanks
Thank you for letting me know, I'll do that in the future.

**Comment by drahnr** [comment]
I'd have to double check the impl details, but iirc the environment for dist mode is very limited and definitely guarded by namespaces.

Currently sccache dies auto uploads of the tool chain, but also allows custom ones. You'd need to add perl to your tool chain package in the ice cream format. I think it would be doable for sccache, I just don't think it should be hard coded by sccache :)

A build.rs file should not assume the presence of external tooling.

**Comment by MisterEggnog** [comment]
Okay, this sounds like it's an issue on rings end, I'll file an issue with them.

**Comment by drahnr** [comment]
I think #798 would be a short term fix
