### ISSUE TITLE
Symlinked C compilers broken

### ISSUE THREAD

**Issue by Jake-Shadle** [mozilla/sccache#1437]
I'm not 100% sure, but I believe #1402 introduced a bug by canonicalizing the path https://github.com/mozilla/sccache/blob/main/src/server.rs#L942-L944, which completely breaks the clang driver model since the first invocation that resolves to the same binary is the one that gets used. This results in problems where C files are compiled as C++, or visa versa, or clang-cl is used when targeting the host system (eg build script).

**Comment by Jake-Shadle** [comment]
My workaround is just to create simple wrapper scripts in Rust that forward to the actual driver I want to use to break the symlink, which works fine and is easier to grok, but this issue will hit anyone targeting clang.

**Comment by sylvestre** [comment]
@figsoda rings a bell ?

**Comment by sylvestre** [comment]
we should have a test for this case

**Comment by drahnr** [comment]
We should then consider to only canonicalize for rust toolchains.

**Comment by figsoda** [comment]
maybe we should readlink until the executable name is different

**Comment by sylvestre** [comment]
@figsoda are you going to work on this or I should revert your PR ? thanks

**Comment by drahnr** [comment]
@sylvestre I'd support revert, we need a regression test and a PR that fixes both issues.
