### ISSUE TITLE
Add support for Google IAM roles to the GCS backend

### ISSUE THREAD

**Issue by cramertj** [mozilla/sccache#144]
> @luser: for S3 we support IAM roles coming from the EC2 instance metadata, which is super useful because it's very easy to assign an IAM role to an EC2 instance, and then you don't have to deal with providing explicit credentials.

It'd be nice to support a similar pattern for the GCS backend. We should be able to retrieve GCS service credentials from GCP instance metadata [as described here](https://cloud.google.com/compute/docs/storing-retrieving-metadata).

cc discussion on #137

**Comment by GMNGeoffrey** [comment]
I was very surprised to discover that sccache didn't work with cloud default credentials. It doesn't even work when you point it to `application_default_credentials.json`, which apparently has a different format than what it's looking for.

**Comment by Xuanwo** [comment]
Already supported in v0.4 releases. Please give a try.
