### ISSUE TITLE
Useless error messages when compilation fails on linux64/android/maybe others

### ISSUE THREAD

**Issue by staktrace** [mozilla/sccache#146]
https://bugzilla.mozilla.org/show_bug.cgi?id=1377211

When builds fail in automation (e.g. on tryserver) sccache seems to eat the real error messages and emit "cc1plus: error: to generate dependencies you must specify either -M or -MM" instead. This makes it very hard to fix build failures via tryserver if you don't have the relevant build platform/configuration handy locally. Even if you do it's a waste of time to replicate the build locally when sccache should just do the right thing.

**Comment by luser** [comment]
I have a patch to fix this in https://github.com/mozilla/sccache/pull/145
