### ISSUE TITLE
build-dependency on assert_cmd is needlessly tight

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/sccache#1465]
sccache build-depends strictly on a single version of assert_cmd.  Reason was explained in commit message for commit 70ca58d as being due to sccache having a lower MSVR than assert-cmd, but that seems no longer true.

Please switch to track only minor version - or preferrably only major version.

**Comment by sylvestre** [comment]
unrelated to this @jonassmedegaard but sccache will depend on https://crates.io/crates/opendal in the future

**Comment by jonassmedegaard** [comment]
thanks for the quick fix @sylvestre and also for the notice about future dependency (I did notice in recent git commit, but appreciated regardless)
