### ISSUE TITLE
100% cache misses when using `cargo install --git`

### ISSUE THREAD

**Issue by lilianmoraru** [mozilla/sccache#148]
I ran this command 3 times:
```
time RUSTC_WRAPPER="/home/lilian/.cargo/bin/sccache" RUSTFLAGS="-C target-cpu=native" cargo +nightly install --git https://github.com/BurntSushi/ripgrep.git --force --features 'simd-accel avx-accel'
```
and every time it results in 100% cache misses.

My guess now is that when using `--git`, it downloads the projects into a temporary folder, this way the paths change every time.

I was hoping that `sccache` will share the compiled crates, so, when compiling other projects, it will pick these up(from a previous ripgrep compilation for example).

Could this be solved or there is nothing that can be done here?

**Comment by alexcrichton** [comment]
This is likely due to Cargo using a tmpdir so path names are changing, and the hash right now may accidentally include the path name.

**Comment by luser** [comment]
If you run `cargo build -v` there you should be able to see the actual rustc invocations, which would show where the problem is. I think cargo passes the full path to some things on the commandline, and sccache doesn't try to filter those out currently.
