### ISSUE TITLE
"Storage options" section missing from README

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/sccache#1480]
There's an entry for it in the Table of Contents linking to https://github.com/mozilla/sccache#storage-options, but that anchor isn't actually present on the page.

**Comment by Xuanwo** [comment]
We used to place all storage-related options in `README.md`, but in PR https://github.com/mozilla/sccache/pull/1464, we split them into different files. Maybe we can just remove this link in ToC.

Do you wanna to send a PR to fix this?

**Comment by theres-waldo** [comment]
Huh, I could have sworn that when I tried earlier, the links underneath "Storage Options" (e.g. "Local") didn't resolve either... but now that I check again, they do.

So, the only issue seems to be the "Storage Options" link itself. I guess we should just de-linkify that but keep the links to "Local" etc. in ToC?

**Comment by theres-waldo** [comment]
https://github.com/mozilla/sccache/pull/1482

**Comment by sylvestre** [comment]
Thanks!

**Comment by Xuanwo** [comment]
This issue has been addressed, please closing~
