### ISSUE TITLE
s3 backend silently stopped working after 0.3.1 when AWS region isn't defined

### ISSUE THREAD

**Issue by indygreg** [mozilla/sccache#1508]
I use sccache with an S3 backend in GitHub Actions.

After upgrading from 0.3.0 to 0.3.3, I noticed that GitHub Actions jobs were seeing 0 cache hits. Surprisingly, cache writes appeared to be working. From https://github.com/indygreg/apple-platform-rs/actions/runs/3782041120/jobs/6429440116 (0.3.3):

```
Stopping sccache server...
Compile requests                    763
Compile requests executed           653
Cache hits                            0
Cache misses                        651
Cache misses (C/C++)                 95
Cache misses (Rust)                 556
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  2
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 110
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.504 s
Average cache read miss           0.504 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
crate-type                           83
multiple input files                 12
unknown source language              11
-                                     4

Cache location                  S3, bucket: apple-platform-rs-sccache
```

I installed sccache 0.3.1 and it appears to work. From https://github.com/indygreg/apple-platform-rs/actions/runs/3782894443/jobs/6431003988:

```
Stopping sccache server...
Compile requests                    763
Compile requests executed           653
Cache hits                          651
Cache hits (C/C++)                   95
Cache hits (Rust)                   556
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  2
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 110
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
crate-type                           83
multiple input files                 12
unknown source language              11
-                                     4

Cache location                  S3, bucket: Bucket(name=apple-platform-rs-sccache, base_url=https://apple-platform-rs-sccache.s3.amazonaws.com/)
```

So 0.3.1 works.

I'd love to bisect 0.3.2, but there are no pre-built binaries for this release. So the best I can do right now is tell you the regression is somewhere between 0.3.1 and 0.3.3.

I'm actively debugging this. Hopefully I'll have something more meaningful to report soon. But figured I'd get the issue on file to raise awareness.

**Comment by indygreg** [comment]
I attempted to bisect this locally and can't reproduce it: I'm able to achieve S3 read hits on sccache tags 0.3.0, 0.3.1, 0.3.2, and 0.3.3.

So whatever the regression is, it appears isolated to GitHub Actions.

Perhaps there is an additional non-deterministic environment variable / path in GitHub Actions that sccache >=0.3.2 considers as part of the cache key?

**Comment by indygreg** [comment]
I cranked up sccache logging to debug and found the issue in GitHub Actions. Appears that the S3 client doesn't know which AWS region to send requests to:

```
2022-12-26T19:20:18.2507457Z [2022-12-26T19:15:29Z DEBUG sccache::compiler::compiler] [proc_macro2]: Compiled in 0.679 s, storing in cache
2022-12-26T19:20:18.2507945Z [2022-12-26T19:15:29Z DEBUG aws_smithy_http_tower::parse_response] send_operation;
2022-12-26T19:20:18.2508455Z [2022-12-26T19:15:29Z DEBUG aws_smithy_http_tower::parse_response] send_operation; operation="PutObject"
2022-12-26T19:20:18.2508956Z [2022-12-26T19:15:29Z DEBUG aws_smithy_http_tower::parse_response] send_operation; service="s3"
2022-12-26T19:20:18.2509492Z [2022-12-26T19:15:29Z DEBUG aws_smithy_http_tower::parse_response] send_operation; status="construction_failure"
2022-12-26T19:20:18.2510153Z [2022-12-26T19:15:29Z DEBUG aws_smithy_http_tower::parse_response] send_operation; message=EndpointResolutionError(Error { message: "no region in params", extra: None })
2022-12-26T19:20:18.2510925Z [2022-12-26T19:15:29Z DEBUG sccache::compiler::compiler] [proc_macro2]: Cache write error: failed to construct request: EndpointResolutionError(Error { message: "no region in params", extra: None })
2022-12-26T19:20:18.2511315Z     
2022-12-26T19:20:18.2511485Z     Caused by:
2022-12-26T19:20:18.2511772Z         EndpointResolutionError(Error { message: "no region in params", extra: None })
2022-12-26T19:20:18.2512242Z [2022-12-26T19:15:29Z DEBUG sccache::server] [proc_macro2]: Cache write finished in 0.679 s
```

This is an undocumented change in behavior, likely a result of swapping in the new S3 backend.

Was the old client resolving the region hosting the S3 bucket and automatically routing requests to it? Or perhaps it was relying on the magical property where S3 buckets can be accessed in foreign regions? (I believe the official AWS clients are a bit opinionated about specifying a region for all clients.)

I suspect this can be worked around by exporting `AWS_REGION` or `AWS_DEFAULT_REGION`.

Another bug here is this write failure / error appears to not get reported as such. I would expect `Cache write errors` to be non-zero, as the logs indicate the cache write actually failed!

**Comment by indygreg** [comment]
Confirmed that setting `AWS_REGION` with 0.3.3 makes the S3 backend work again.

The current docs indicate that one should set the AWS region or S3 bucket endpoint URL via environment variables or configs.

So I think the most pressing bug here is the fact that write errors from the S3 backend aren't making it to the sccache statistics. That made this much harder to debug than it should have been.

Perhaps, also, sccache could emit a warning when the region isn't defined, as this will apparently be a fatal error for the s3 backend.

**Comment by sylvestre** [comment]
what about failing to start the service if not set?

**Comment by sylvestre** [comment]
actually, we already have SCCACHE_REGION
so, should probably be this one/clone

**Comment by indygreg** [comment]
> what about failing to start the service if not set?

If there's precedent for validating backend / other configs during service startup, making lack of an AWS region a fatal error makes sense to me. I'm generally of the opinion things should fail fast. But graceful degradation is also a desirable software property, especially for optional features like caching systems! I think the most important thing here is leaving some breadcrumb that things are broken without requiring users to opt in to more verbose logging to uncover it.

**Comment by Xuanwo** [comment]
@indygreg Please try `0.4.0-pre.2` with the old config.

In the new version, we will:

- Load `SCCACHE_REGION` if set.
- Load `AWS_REGION` if set.
- Try to detect region with bucket name and endpoint.

Also, I'm interested to implement fail fast to we failed to configure s3 correctly.
