### ISSUE TITLE
proposal: Exit with error message if storage is misconfigured

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1512]
## Background

Sccache will ignore storage errors by default:

- For reading, all non-ok responses will be treated as cache-miss.
- For writing, all non-ok responses will be ignored.

Thus, users don't know storage is misconfigured until they find the cache is always missed.

This problem has been proposed by the community many times:

- Fix https://github.com/mozilla/sccache/issues/45
- Fix https://github.com/mozilla/sccache/issues/1508
- Fix https://github.com/mozilla/sccache/issues/1384
- Fix https://github.com/mozilla/sccache/issues/1173
- Fix https://github.com/mozilla/sccache/issues/225

## Proposal

So I propose adding a storage check before starting the server by performing `write` and `read` operations with file path `.sccache_check`.

- If both of them succeed, sccache will run in `read-write` mode.
- If `write` fails with `PermissionDenied` and `read` is `Ok` or `NotFound`, sccache will run in `read-only` mode.
- All other cases will lead sccache exit with corresponding error messages.
  - For example, `read` returns `PermissionDenied` or `OtherError`.

The status will also be shown in `sccache --show-stat`.

With the super power of [OpenDAL](https://github.com/datafuselabs/opendal), this proposal should be easy (

Error happened during compilation will still be ignored.

## Drawbacks

Misconfigured sccache will break users' workflow, which may lead to more severe problems.

## Tasks

- [x] https://github.com/mozilla/sccache/pull/1515

**Comment by sylvestre** [comment]
That sounds like a great idea, i am sure that weeks of work have been lost while trying to configure sccache.

I did similar work with logging: https://github.com/mozilla/sccache/pull/1361

**Comment by Xuanwo** [comment]
Quick demo show:

```shell
:( SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 SCCACHE_BUCKET=test ./target/debug/sccache                  
sccache: error: cache storage failed to read: ObjectPermissionDenied (permanent) at read => S3Error { code: "AccessDenied", message: "Access Denied", resource: "", request_id: "46RYHDRAN8WD64XW" }

Context:
    response: Parts { status: 403, version: HTTP/1.1, headers: {"x-amz-request-id": "46RYHDRAN8WD64XW", "x-amz-id-2": "R9ldSWAQSbbTSYOowzLoJD0dRgRWbcS0wYV0ibbb+4yVok+oYEmvB+F8+2g05KWvXnGYK8poafw=", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Mon, 02 Jan 2023 04:48:47 GMT", "server": "AmazonS3"} }
    service: s3
    path: .sccache_check
    range: 0-
```
