### ISSUE TITLE
test test_gcp_arg_check requires feature dist-server

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/sccache#1517]
Checking all tests with feature `dist-server` disabled fails.

(update: bogus patch removed)

**Comment by sylvestre** [comment]
thanks
Would you like to do a PR to fix it?

**Comment by jonassmedegaard** [comment]
I never push code to Github, due to their questionable terms of service.

If you find it helpful that I provide a git clone elsewhere that you then fetch, then I am happy to do that.

**Comment by sylvestre** [comment]
Too bad. As a packager of sccache, I was hoping you would contribute directly to the project...

but yeah, a git clone repo would be nice

**Comment by jonassmedegaard** [comment]
Ok, I'll prepare a git clone...

(also, I just realized while rebuilding that above patch is wrong: The test tied to dist-server feature is test_gcp_arg_check) (the test test_run_log_no_perm fails for a different reason potentially specific to my build environment - if not I'll report that separately).

**Comment by jonassmedegaard** [comment]
Patch now available as the topmost commit here: https://salsa.debian.org/debian/sccache/-/tree/bug/1517

(and yes, as suspected the other test failure was a local issue at my end, not your concern)

**Comment by Xuanwo** [comment]
`test_gcp_arg_check` doesn't depend on `dist-server`.

Should be fixed in https://github.com/mozilla/sccache/pull/1520, please have a try.
