### ISSUE TITLE
Publish 0.2.0 release.

### ISSUE THREAD

**Issue by rillian** [mozilla/sccache#153]
We'd really like to get a new release published so people can `cargo install sccache`.

[ ] - We need an [lru-cache](https://github.com/contain-rs/lru-cache/pull/41) bump so we can stop using a git fork.
[ ] - Bump release version.
[ ] - `cargo publish`.

**Comment by rillian** [comment]
Any other issues?

**Comment by rillian** [comment]
We need to fix #117 so we can use this with local Firefox builds, but that shouldn't block release.

**Comment by luser** [comment]
IIRC that's it. The lru-cache PR is sort of hairy. Maybe we'd be better off just rewriting lru-disk-cache to not use lru-cache at all? I thought reusing an existing crate would be better but I wound up having to modify it so heavily that I'm not sure it was worthwhile.

**Comment by posix4e** [comment]
Happy to help out with testing here. I am back at brave and I use sccache regularly https://github.com/brave/browser-laptop-bootstrap/ . I have a gcs bucket I am using.

**Comment by luser** [comment]
I sorted out the few remaining issues and published 0.2.0: https://crates.io/crates/sccache/0.2.0
