### ISSUE TITLE
firefox/media/libav/libavcodec/avfft.h:37:16: error: redefinition of 'FFTComplex'

### ISSUE THREAD

**Issue by rillian** [mozilla/sccache#154]
When I compile Firefox on my local mac with `ac_add_options --enable-ccache=sccache` in `mozconfig` if fails with duplicate symbol definitions:
```
 3:31.49 In file included from /Users/giles/firefox/media/libav/libavcodec/avfft.c:1:
 3:31.49 In file included from <built-in>:2:
 3:31.49 In file included from /Users/giles/firefox/media/libav/avfft_perms.h:15:
 3:31.49 /Users/giles/firefox/media/libav/libavcodec/avfft.h:37:16: error: redefinition of 'FFTComplex'
 3:31.49 typedef struct FFTComplex {
 3:31.49                ^
 3:31.49 /Users/giles/firefox/media/libav/libavcodec/avfft.h:37:16: note: previous definition is here
 3:31.49 typedef struct FFTComplex {
 3:31.49                ^
```
among many similar warnings and errors.

`avfft.h` does have `#ifdef` protection, so something's confusing the pre-processor.

This is sccache built today from b2d1ea21d464ba51c3034876835dc0162a7dd80f.

**Comment by na-g** [comment]
This sounds like the issue I am having in #117.

**Comment by rillian** [comment]
Indeed it does. Thanks! I'll close this as a duplicate.
