### ISSUE TITLE
Print sccache version while running `--show-stats`

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1548]
Print sccache version in stats will make it easier for debugging.

**Comment by Xuanwo** [comment]
@sylvestre Can you help mark this issue as `help wanted` and `good first issue`? Thanks.

**Comment by borjamunozf** [comment]
Hi. I could try to do this if you want.

I have already done it, but not sure if this the idea.
![imagen](https://user-images.githubusercontent.com/25910927/212935601-031be04c-13dd-498b-b0da-56934e56f11b.png)

Doubts about position/formatting:
- Should it be first/latest print better? I guess versioning it's used to be shown as the first or latest thing on the output, but...

Thanks.

**Comment by Xuanwo** [comment]
> I have already done it, but not sure if this the idea.

Yes! This is what I want.



> * Should it be first/latest print better? I guess versioning it's used to be shown as the first or latest thing on the output, but...

Showing along with `cache location` LGTM. In the future, maybe we can introduce sections like `setup` and `statistics` to make them more readable.

For the output content, we can remove the `Sccache` prefix, and only use `Version`.

**Comment by drahnr** [comment]
There should be a clear statement that it's the _client_ version.

**Comment by borjamunozf** [comment]
> There should be a clear indicator that it's the _client_ version.

Do you mean something like this explicitly?
![imagen](https://user-images.githubusercontent.com/25910927/212997964-0e7b777d-73a2-441b-91ea-b6190c42de52.png)

Thanks.

**Comment by sylvestre** [comment]
Please avoid screenshot of text:
* they are terrible for accessibility
* they can't be searched
* it is only text here anyway ;)

**Comment by Xuanwo** [comment]
PR has been merged, let's close this.
