### ISSUE TITLE
Duplicate feature cfg

### ISSUE THREAD

**Issue by posix4e** [mozilla/sccache#158]
This  https://github.com/mozilla/sccache/blob/39fdfd83a84ccf1f1a8df58588c33953bebe702d/src/cache/cache.rs#L240
is already in the feature
https://github.com/mozilla/sccache/blob/39fdfd83a84ccf1f1a8df58588c33953bebe702d/src/cache/cache.rs#L236

any reason not to remove the inner?

**Comment by luser** [comment]
I think you actually need both of them--the `if cfg!(...)` is just a conditional that gets optimized away at compile-time, but the inner `#[cfg(...)]` is to guard the code that doesn't get built at all when that feature is disabled.
