### ISSUE TITLE
Build & Release `v0.3.3` for `aarch64-unknown-linux-musl`

### ISSUE THREAD

**Issue by ajschmidt8** [mozilla/sccache#1595]
`aarch64-unknown-linux-musl` builds [were disabled](https://github.com/mozilla/sccache/commit/a31cf6491e6f3cd05c704ffb86d98ca8974300b0) in CI prior to the `v0.3.3` release due to some transient upstream issues with Ubuntu packages repositories.

Those issues are resolved and `aarch64` was re-enabled successfully in #1499.

However, there are no still `aarch64-unknown-linux-musl` builds for the latest `v0.3.3` release ([here](https://github.com/mozilla/sccache/releases/tag/v0.3.3)).

Can these builds be uploaded to the GitHub release page?

Right now my team is stuck on using `v0.2.15` for `aarch64` while we use `v0.3.3` for `x86_64`.

**Comment by ajschmidt8** [comment]
@sylvestre, I rebuilt the `v0.3.3` release on my fork below to make it easy for you.

If you could just download the `aarch64-unknown-linux` artifacts from my forked release and upload them to the official release, that would be greatly appreciated!

Here are all of the relevant links for reference:

- Forked release - https://github.com/ajschmidt8/sccache/releases/tag/v0.3.3
- Forked release GHA Workflow - https://github.com/ajschmidt8/sccache/actions/runs/4152697998
- Comparison between my forked tag and official tag - https://github.com/mozilla/sccache/compare/v0.3.3...ajschmidt8:sccache:v0.3.3

The forked release artifacts are available on the first two links of the list above.

**Comment by sylvestre** [comment]
Thanks but, with all the recent supply chain attacks, I can't take a binary from another repo and just upload it here :)
I will see what I can do until then.

Sorry :)

**Comment by ajschmidt8** [comment]
I understand.

If you push a `v0.3.4` tag that includes the changes from [this PR](https://github.com/mozilla/sccache/pull/1499), that might be easier than trying to rebuild anything for `v0.3.3` locally. Just a thought.

Appreciate your help.

**Comment by Xuanwo** [comment]
The easiest solution for me is to try `v0.4.0-pre.6`. I am ready to fix any regression that might happen.

**Comment by ajschmidt8** [comment]
@Xuanwo, I'm hesitant to adopt a pre-release for all of my team's builds.

We have a lot projects that will take several hours to build if there are any issues with `sccache` and I won't have time to help debug in the event that there are issues.

How close is `v0.4.0` to being published in a proper release?

**Comment by ajschmidt8** [comment]
closing now that newer releases are out
