### ISSUE TITLE
superfluous dev-dependency on wiremock

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/sccache#1599]
The crate `wiremock` is no longer actually used since commit f21c88c, so the corresponding dev-dependency in Cargo.toml can be dropped.

**Comment by Xuanwo** [comment]
LGTM, would you like to send a PR person to fix the problem?

**Comment by jonassmedegaard** [comment]
Thanks for the suggestion, but no: I never push code changes to Github due to their copyleft-defeating terms-of-service.  I would be happy to instead share an externally hosted git clone that you could pull, but for a single-line change like this I assume that to be too much hassle.
