### ISSUE TITLE
Fix Windows compiler invocation to not create new console windows

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#16]
https://github.com/luser/sccache2/commit/235239aab0bd2be8ff8f0f4895851295ebb207c2 changed how we spawn the sccache server process on Windows to make it detached, but in the process it made it so that when the server spawns a compiler process it creates a new console window. This is noticeable if you run `cargo test test_sccache_command` on Windows, you'll see several console windows pop up.

**Comment by luser** [comment]
The original Python code was spawning the process with the `DETACHED_PROCESS` flag:
https://github.com/mozilla/sccache/blob/e3f5fb27092807627f3e31ddca43a66c3ddeb7a9/sccache.py#L60

the Rust code is also passing `CREATE_NEW_PROCESS_GROUP`:
https://github.com/mozilla/sccache/blob/5591191bc17da9b96513f2a3832cecf7bcb8d3e8/src/commands.rs#L145

I'll try removing that and see if it makes a difference. If not it might be some other difference in the Rust process spawning code vs. Python's subprocess.

**Comment by luser** [comment]
...that's not it.

**Comment by luser** [comment]
...that's not it.

**Comment by luser** [comment]
Oh, hah! This bug existed in the Python implementation as well, and @glandium fixed it in this commit by passing `CREATE_NO_WINDOW` in the `CreateProcess` flags:
https://github.com/glandium/sccache/commit/b259421c5225f040ea20d51261083287c02a8069

**Comment by RReverser** [comment]
@luser @alexcrichton I recently started using sccache, and am seeing a very similar issue (new console windows occasionally flickering with sccache). I know this one was fixed a long time ago, but I wonder if it was reintroduced again?

**Comment by Systemcluster** [comment]
Using `sccache 0.2.9`, tested on Windows 10 with PowerShell and CMD, this is (still or again) occurring currently. @luser would you mind re-opening this issue?

**Comment by luser** [comment]
Can you open a new issue on this? I think that'd be less confusing.
