### ISSUE TITLE
Local disk cache 3-4.5x slower than ccache

### ISSUE THREAD

**Issue by indygreg** [mozilla/sccache#160]
I frequently perform a number of fully cached clobber builds of Firefox as part of testing the Firefox build system. My workflow is build, clobber, build. This workflow essentially benchmarks non-cached aspects of the Firefox build system and the caching layer. I've previously been using ccache but switched to sccache because Rust compilation was being a long pole and I didn't want to wait dozens of seconds for Rust to finish compiling.

To my surprise, sccache is significantly slower than ccache for comparable operations. When you factor in cache hits from Rust, sccache is about the same speed (135-145s wall for a clobber build). But if you limit the comparison to just C/C++, then sccache is ~3x slower overall and ~4.5x slower to obtain object files:

```
ccache:   35s wall; 131s CPU; 20s wall to libxul link
sccache: 107s wall; 131s CPU; 93s wall to libxul link
```

My mozconfig has `export CC=clang` and `ac_add_options --disable-debug --disable-optimize`. Clang version is `4.0.0-1ubuntu1` (from Ubuntu 17.04). To get the numbers above, I did a full build then a `find objdir -name '*.o' | xargs rm` to nuke C/C++ object files. Then I did `mach build binaries` to measure C/C++ compile time from cache. This is with current master (`6267caf603d5a06e8a4b9391ffa02f6125e5ba9b`) built with `cargo build --release --features=all`

`perf` recording of all processes during an sccache build shows the following hot frames:

```
   4.79%  clang          libLLVM-4.0.so.1                   [.] llvm::StringMapImpl::LookupBucketFor
   4.29%  clang          clang                              [.] clang::Lexer::LexTokenInternal
   2.81%  clang          clang                              [.] clang::Lexer::LexIdentifier
   2.58%  clang          clang                              [.] clang::SourceManager::getFileIDLocal
   2.54%  clang          clang                              [.] clang::DoPrintPreprocessedInput
   2.01%  sccache        sccache                            [.] GFp_sha512_block_data_order_avx2
   1.82%  clang          libc-2.24.so                       [.] __memmove_avx_unaligned_erms
   1.40%  clang          libLLVM-4.0.so.1                   [.] llvm::raw_svector_ostream::write_impl
   1.22%  clang          clang                              [.] clang::Preprocessor::Lex
   1.20%  clang          clang                              [.] clang::SourceManager::getCharacterData
   1.11%  sccache        sccache                            [.] tinfl_decompress
   1.02%  sccache        sccache                            [.] <zip::crc32::Crc32Reader<R> as std::io::Read>::read
   0.97%  clang          [kernel.kallsyms]                  [k] __d_lookup_rcu
   0.90%  watchman       watchman                           [.] w_ht_lookup
   0.84%  clang          clang                              [.] clang::Preprocessor::LookUpIdentifierInfo
   0.83%  clang          clang                              [.] clang::TokenLexer::Lex
   0.79%  clang          clang                              [.] clang::SrcMgr::ContentCache::getBuffer
   0.77%  clang          libLLVM-4.0.so.1                   [.] llvm::raw_ostream::write
   0.74%  sccache        [kernel.kallsyms]                  [k] copy_page
   0.73%  clang          libLLVM-4.0.so.1                   [.] llvm::raw_ostream::write
   0.70%  clang          clang                              [.] clang::Lexer::Lex
   0.69%  clang          clang                              [.] clang::Lexer::getSpelling
   0.69%  clang          ld-2.24.so                         [.] do_lookup_x
   0.67%  python         python2.7                          [.] PyEval_EvalFrameEx
   0.67%  sccache        [kernel.kallsyms]                  [k] copy_page_range
```

ccache by comparison:

```
   4.74%  watchman       watchman                           [.] w_string_equal
   3.20%  python         python2.7                          [.] PyEval_EvalFrameEx
   2.24%  python         python2.7                          [.] lookdict_string
   1.82%  watchman       watchman                           [.] w_ht_lookup
   1.61%  ccache         ccache                             [.] 0x000000000000f5d1
   1.43%  ccache         [kernel.kallsyms]                  [k] copy_user_enhanced_fast_string
   1.30%  ar             libbfd-2.28-system.so              [.] _bfd_elf_make_section_from_shdr
   1.27%  yasm           libc-2.24.so                       [.] _int_malloc
   1.10%  yasm           libc-2.24.so                       [.] _int_free
   1.04%  python         python2.7                          [.] PyObject_Malloc
   0.96%  ccache         ccache                             [.] 0x000000000000f5c4
   0.93%  python         python2.7                          [.] _PyType_Lookup
   0.89%  watchman       watchman                           [.] w_ht_insert
   0.88%  yasm           libc-2.24.so                       [.] malloc
   0.83%  ccache         [kernel.kallsyms]                  [k] __d_lookup_rcu
   0.76%  python         python2.7                          [.] collect
   0.76%  python         python2.7                          [.] visit_decref
   0.67%  python         [kernel.kallsyms]                  [k] __d_lookup_rcu
   0.64%  python         python2.7                          [.] visit_reachable
   0.63%  yasm           libc-2.24.so                       [.] __stpcpy_sse2_unaligned
   0.60%  python         python2.7                          [.] PyDict_GetItem
   0.58%  yasm           libc-2.24.so                       [.] free
   0.56%  yasm           libc-2.24.so                       [.] __strncpy_sse2_unaligned
   0.53%  yasm           libc-2.24.so                       [.] strlen
   0.52%  yasm           yasm                               [.] 0x0000000000025b06
   0.51%  ccache         [kernel.kallsyms]                  [k] link_path_walk
```

SHA-512 appears in there. You could switch to blake2b for a ~2x speedup.

tinfl_decompress() and a crc32 associated with reading a zip file also appear. Switching to lz4 (which uses the insanely fast xxHash for content verification) would yield a nice speedup (but would yield larger compressed blobs). zstd would be a good choice if you want to preserve the compression ratio. And for local storage, disabling compression and/or bypassing zip by rolling your own archive format could be a nice win.

But the bulk of the overhead with sccache is spent in clang. Process reporting indicates a bunch of `clang++ -E` invocations. I'm not sure if this is a feature or a bug. If a feature, then there's probably not much that can be done other than change the caching architecture.

A ~70s overhead versus ccache for the same workload is pretty significant. I wish sccache were comparable so it could be used as a drop-in replacement for ccache with similar local disk performance. Also, presumably that overhead comes into play for remote caches as well. Although with network latency being relatively long, I have no clue of the actual impact.

**Comment by luser** [comment]
> To my surprise, sccache is significantly slower than ccache for comparable operations.

By default ccache uses "direct mode" where it doesn't actually run the preprocessor. I don't think sccache will ever be that fast, as I don't think we'll ever add a mode like that (it's not workable for a distributed cache). There's always going to be overhead from running the preprocessor, unfortunately. We should try to get closer to ccache's performance, though. I'd be interested to see a comparison of ccache in "preprocessor mode" vs. sccache. Also maybe a comparison with ccache in preprocessor mode and with `CCACHE_COMPRESS` enabled to see what that looks like.

> SHA-512 appears in there. You could switch to blake2b for a ~2x speedup.

We just recently switched from SHA-1 to SHA-512 specifically for a speedup (the ring SHA-512 implementation is written in assembly), so I'm not eager to do that again.

> tinfl_decompress() and a crc32 associated with reading a zip file also appear.

We could definitely explore alternate cache entry storage formats. We're using zip because that's what sccache.py used, probably because Python has a built-in zipfile module so it was easy. We could use any arbitrary storage format. I'd probably just use a tarfile with whatever the most suitable compression format wrapped around it is. I know you favor zstd nowadays, that'd be fine. We'd want to mostly optimize for decompression speed, so that cache hits are fast, but also make sure that compression isn't too CPU-heavy since that will be happening in the background for cache misses.

We could also very easily measure the zip compression overhead by turning off zip compression in sccache: https://github.com/mozilla/sccache/blob/6267caf603d5a06e8a4b9391ffa02f6125e5ba9b/src/cache/cache.rs#L134 .

**Comment by indygreg** [comment]
I reproduced with ccache with `compression = true` and `direct_mode = false`. This is roughly equivalent to what sccache does today.

`96s wall; 600s CPU; 79s wall to libxul link`.

ccache is still a little faster than sccache, but not by much.

`perf` shows that LLVM/Clang makes an entrance with the use of the preprocessor:

```
   5.04%  clang          libLLVM-4.0.so.1                   [.] llvm::StringMapImpl::LookupBucketFor                                                                  ▒
   4.70%  clang          clang                              [.] clang::Lexer::LexTokenInternal                                                                        ▒
   3.06%  clang          clang                              [.] clang::Lexer::LexIdentifier                                                                           ▒
   2.88%  clang          clang                              [.] clang::SourceManager::getFileIDLocal                                                                  ▒
   2.59%  clang          clang                              [.] clang::DoPrintPreprocessedInput                                                                       ▒
   1.33%  clang          clang                              [.] clang::SourceManager::getCharacterData                                                                ▒
   1.31%  clang          clang                              [.] clang::Preprocessor::Lex                                                                              ▒
   1.09%  clang          [kernel.kallsyms]                  [k] __d_lookup_rcu                                                                                        ▒
   0.98%  clang          libc-2.24.so                       [.] __memmove_avx_unaligned_erms                                                                          ▒
   0.92%  clang          clang                              [.] clang::Preprocessor::LookUpIdentifierInfo                                                             ▒
   0.92%  clang          clang                              [.] clang::TokenLexer::Lex                                                                                ▒
   0.87%  clang          clang                              [.] clang::SrcMgr::ContentCache::getBuffer                                                                ▒
   0.79%  clang          clang                              [.] clang::Lexer::Lex                                                                                     ▒
   0.78%  clang          clang                              [.] clang::Lexer::getSpelling                                                                             ▒
   0.75%  python         python2.7                          [.] PyEval_EvalFrameEx                                                                                    ▒
   0.74%  clang          ld-2.24.so                         [.] do_lookup_x                                                                                           ▒
   0.74%  clang++        [kernel.kallsyms]                  [k] __d_lookup_rcu                                                                                        ▒
   0.69%  clang          clang                              [.] clang::SourceManager::getLineNumber                                                                   ▒
   0.67%  clang          ld-2.24.so                         [.] _dl_relocate_object                                                                                   ▒
   0.63%  clang          ld-2.24.so                         [.] _dl_lookup_symbol_x                                                                                   ▒
   0.63%  clang          clang                              [.] clang::Lexer::SkipWhitespace                                                                          ▒
   0.62%  clang          clang                              [.] clang::SourceManager::getColumnNumber                                                                 ▒
   0.62%  clang          [kernel.kallsyms]                  [k] __do_page_fault                                                                                       ▒
   0.56%  clang          clang                              [.] clang::TokenLexer::ExpandFunctionArguments                                                            ▒
   0.55%  clang          [kernel.kallsyms]                  [k] unmap_page_range                                                                                      ▒
   0.53%  clang          [kernel.kallsyms]                  [k] filemap_map_pages                                                                                     ▒
   0.53%  clang          libc-2.24.so                       [.] __memcmp_sse4_1 
```

FWIW I disabled compression and blew away and repopulated the cache and the numbers didn't change much. This is pretty much all preprocessor overhead.

**Comment by luser** [comment]
I think supporting an equivalent to ccache's direct mode for use on developer machines would be useful, I opened https://github.com/mozilla/sccache/issues/219 .

**Comment by ezyang** [comment]
We have noticed this as well. We are using sccache in a distributed setting, but we guarantee that all of the nodes have exactly the same file system layout / working copies. It would be nice to have direct mode here as well.

**Comment by m87m** [comment]
>  By default ccache uses "direct mode" where it doesn't actually run the preprocessor. I don't think sccache will ever be that fast, as I don't think we'll ever add a mode like that (it's not workable for a distributed cache).

@luser could you explain me please why it is not possible to use direct mode for distributed cache? Do I understand correctly that issue #219 will never be implemented?

**Comment by kalpaj1997** [comment]
I've the same question as well. @luser can we keep any hopes to have direct mode implemented? If we have direct mode, we will never have to look at ccache again.

**Comment by sylvestre** [comment]
AFAIK nobody is working on it.

Ted described it here:
https://github.com/mozilla/sccache/issues/219#issuecomment-544522192

Someone could have a look. @Xuanwo  i guess your framework doesn't do that?

**Comment by Xuanwo** [comment]
> @Xuanwo i guess your framework doesn't do that?

My framework (OpenDAL) only cares about operation on storage services and not related to cache logic it self.

But opendal does have `fs` support which is powered by `tokio::fs`. I'm not sure if it's useful.

**Comment by kalpaj1997** [comment]
> > @Xuanwo i guess your framework doesn't do that?
> 
> My framework (OpenDAL) only cares about operation on storage services and not related to cache logic it self.
> 
> But opendal does have `fs` support which is powered by `tokio::fs`. I'm not sure if it's useful.

From what I understand from conversations with different threads, direct mode wouldn't be supported on storage services. The intended feature is for local storage only, for e.g Linux file system.

@luser has explained ccache's logic here - https://github.com/mozilla/sccache/issues/219#issuecomment-544522192

However, the functionality requires modification to scache logic itself. If we can implement this, scache will be 3x faster on local storage and benefits students like us who are building AOSP and other open source projects for learning/hobbying.

**Comment by mikev-junimo** [comment]
Has anyone had the chance to re-test this now that #1882 has been merged?

**Comment by sylvestre** [comment]
yeah, it should be good now. Closing
thanks
