### ISSUE TITLE
superfluous dependency on time

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/sccache#1600]
The crate `time` is no longer actually used since commit f1a8b0a (more than 3 years ago), so the corresponding dependency in Cargo.toml can be dropped.

**Comment by Xuanwo** [comment]
LGTM, would you like to send a PR person to fix the problem?

**Comment by jonassmedegaard** [comment]
Thanks for the suggestion, but no: I never push code changes to Github due to their copyleft-defeating terms-of-service.  I would be happy to instead share an externally hosted git clone that you could pull, but for a single-line change like this I assume that to be too much hassle.

**Comment by drahnr** [comment]
I don't think you can claim copyrights (or lefts) on a change that deletes one line of code.

`#deny(unused_dependencies)]` is imho preferred approach, much faster too, than handling an issue per dead dependency

**Comment by jonassmedegaard** [comment]
I agree that I would loose no copyright for code I contribute here, concretely.  Also, this project is liberally licensed, so even if my contribution here would be covered by copyright it still would not be affected by Github terms of service.

My concern is code where I hold copyright and where I choose to use copyleft licensing. And my chosen approach is to contribute only comments to Github.
Yes, I could instead totally abandon Github, or I could give up on copyleft licensing, or I could use Github for liberal licensed code and another site for copyleft, or... There are many way to approach it. And also several ways to interpret those terms of service.
