### ISSUE TITLE
Failed to enter a new Linux namespace, caused by: EPERM: Operation not permitted.

### ISSUE THREAD

**Issue by Ruoye-W** [mozilla/sccache#1607]
I tried to deploy build server in Ubuntu 20.04 docker container, bubblewrap verison is 0.4.0, kernel version is 4.14.81.bm.29-amd64, sccache verison is sccache 0.4.0-pre.7, and build server was running as root. when client send distributed compilation request, build server got error message as follow:
[2023-02-15T08:07:01Z WARN  sccache::dist::http::server] Res 1 error: run build failed, caused by: Compilation execution failed, caused by: Failed to enter a new Linux namespace, caused by: EPERM: Operation not permitted.

**Comment by borjamunozf** [comment]
Meanwhile the savy people answer, I think could the issue could be related to the default behaviour of Bubblewrap + Docker.

Bubblewrap sandbox approach with new Linux usernamespace, but it _conflicts_ when running inside Docker, as by default restricts it by security reasons. The workaround, I would say, without seeing your Docker configuration, it's to run the Builder container in **privileged** mode, meaning

```bash
docker run --privileged <builder>
````

or setting up on your docker-compose:
```yaml
privileged: true
````

Let me know how it goes.

**Comment by drahnr** [comment]
@borjamunozf do not do this in production. You're killing the security boundary between host and container.
Use `oci-seccomp-filter` to record the seccomp filter exceptions you need and add those to that container.
