### ISSUE TITLE
Support authentication in WebDAV storage

### ISSUE THREAD

**Issue by dtretyakov** [mozilla/sccache#1608]
In the https://github.com/mozilla/sccache/pull/1597 was added support for WebDAV storage.

The major missing part in it is ability to configure authentication. OpenDAL now supports the following options for that:
* [username/password](https://github.com/datafuselabs/opendal/pull/1323)
* [token](https://github.com/datafuselabs/opendal/pull/1349)

So it would be great to have these options in sccache as well.

cc @Xuanwo

**Comment by Xuanwo** [comment]
Both username and token has been supported.
