### ISSUE TITLE
SCCACHE_LOG_LEVEL breaks Cargo

### ISSUE THREAD

**Issue by kornelski** [mozilla/sccache#161]
```sh
export RUSTC_WRAPPER=sccache
export SCCACHE_LOG_LEVEL=debug
cargo build
```
> error: output of --print=file-names has changed in the compiler, cannot parse

I guess it's because Cargo tries to read stdout of rustc, and finds sccache log instead. 

sccache could be smart and hide debug output if `--print` switch is present.

**Comment by glandium** [comment]
SCCACHE_LOG_LEVEL breaks everything, actually.

**Comment by sylvestre** [comment]
I think it is fixed
