### ISSUE TITLE
sccache fails compiling ObjC code with a .cpp extension and -xobjective-c++

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#163]
Reported on IRC, sccache is failing to build Firefox on Mac currently with some errors in OpenVR code. The OpenVR code is in .cpp files, but includes OS X system headers that use ObjC. The moz.build file passes `-xobjective-c++` in `CXXFLAGS`, but sccache always passes `-xwhatever` based on the file extension: https://github.com/mozilla/sccache/blob/6267caf603d5a06e8a4b9391ffa02f6125e5ba9b/src/compiler/gcc.rs#L311

We should fix this so that if there's already an `-xwhatever` on the commandline we don't add another one.

**Comment by glandium** [comment]
> We should fix this so that if there's already an -xwhatever on the commandline we don't add another one.

hum, you should use the flag that was passed for the preprocessor, but the compilation will need a mapped value for the preprocessed output.

**Comment by luser** [comment]
Well if there's already an `-xobjective-c++` on the commandline then we can just pass that to both invocations and it should work fine, right? The issue is that since the file is .cpp we're passing `-xc++-cpp-output` and it breaks.

I guess your point is that we ought to be replacing `-xobjective-c++` with `-xobjc-cpp-output`?

**Comment by glandium** [comment]
> it should work fine, right?

except for all the warnings that adds.

**Comment by glandium** [comment]
See https://github.com/mozilla/sccache/issues/117#issuecomment-317585176

**Comment by mikeconley** [comment]
Out of curiosity, are there any workarounds for this bug while a proper fix is developed?

**Comment by rillian** [comment]
The work-around I'm aware of is to use `RUSTC_WRAPPER=sccache` so you still get caching for rust code, but use plain `--enable-ccache` to for C/C++/ObjC code.

**Comment by mikeconley** [comment]
Cool, thanks @rillian.

For the folks who don't want to look up the dev-platform thread, this appears to be what you want to drop in your mozconfig for now:

    mk_add_options "export RUSTC_WRAPPER=sccache"

Assuming sccache is on your PATH.

**Comment by luser** [comment]
@glandium are you actively working on this? If not I'll take it.

**Comment by glandium** [comment]
I am

**Comment by luser** [comment]
@glandium's patch is in https://github.com/mozilla/sccache/pull/170
