### ISSUE TITLE
rust coverage test could not compile error

### ISSUE THREAD

**Issue by yihau** [mozilla/sccache#1652]
When I tried to do coverage test with rust nightly-2023-02-09, I got

```
sccache: encountered fatal error
sccache: error: failed to zip up compiler outputs
sccache: caused by: failed to zip up compiler outputs
sccache: caused by: failed to open file `"/Users/yihau/yihau/sccache-coverage-error/target/debug/deps/unicode_ident-25938e1fedca0d89.gcno"`
sccache: caused by: No such file or directory (os error 2)
error: could not compile `unicode-ident`

Caused by:
  process didn't exit successfully: `/Users/yihau/.cargo/bin/sccache rustc --crate-name unicode_ident --edition=2018 /Users/yihau/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-ident-1.0.8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=156 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C metadata=25938e1fedca0d89 -C extra-filename=-25938e1fedca0d89 --out-dir /Users/yihau/yihau/sccache-coverage-error/target/debug/deps -L dependency=/Users/yihau/yihau/sccache-coverage-error/target/debug/deps --cap-lints allow -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort` (exit status: 254)
warning: build failed, waiting for other jobs to finish...
```

I have a tiny project can reproduce the error: https://github.com/yihau/sccache-coverage-build-error (The step is in the `coverage.sh`)

btw, It works fine with `nightly-2023-02-08`

**Comment by sylvestre** [comment]
Indeed, I have the same issue with https://github.com/uutils/coreutils

@Xuanwo did you see this problem before ?

**Comment by Xuanwo** [comment]
Regardless of the root cause, we can choose to ignore the `not found` error, abandon this cache, and continue with the compilation process. I will implement a solution for this issue.

**Comment by yihau** [comment]
Hi @Xuanwo, anything I can help with this one?

**Comment by Xuanwo** [comment]
> Hi @Xuanwo, anything I can help with this one?

We can ignore the NotFound error happened here:

https://github.com/mozilla/sccache/blob/4a8b5f556de579cb62f27712e91d0a13947189bc/src/cache/cache.rs#L253-L254
