### ISSUE TITLE
Does not work with Rust 1.68.0 on a Linux system

### ISSUE THREAD

**Issue by Cthutu** [mozilla/sccache#1654]
I used `cargo install sccache` and added the path to my `config.toml`.  When running `cargo build` it fails immediately when cargo without sccache would succeed.

Here is the output:
![image](https://user-images.githubusercontent.com/348614/224549784-7d80cf01-a2f5-479c-87db-31f710e32a53.png)

**Comment by sylvestre** [comment]
Please replace the screenshot by text.
it is terrible for accessibility and search. Thanks

**Comment by Xuanwo** [comment]
Seems you are using the wrong path, please try using the full path directly instead.

**Comment by drahnr** [comment]
`/home/matt/~/...` looks very fishy.

**Comment by Cthutu** [comment]
I was unable to replace the screenshot with text since my terminal didn't want to copy any text :(  Hence the screenshot.

As for the path, I am not using a wrong path.  My `config.toml` looks like:

```
[build]
rustc-wrapper = "~/.cargo/bin/sccache"
```

But it does give me a clue.  Looks like sccache is handling paths incorrectly.  Good spot there.  It obviously doesn't understand `~` and just appends it to `/home/matt`.

**Comment by Cthutu** [comment]
After changing the path to `.cargo/bin/sccache`, it still doesn't work:
```
❯ sccache cargo build
sccache: error: failed to execute compile
sccache: caused by: Compiler not supported: "error: unexpected argument \'-E\' found\n\nUsage: cargo [+toolchain] [OPTIONS] [COMMAND]\n\nFor more information, try \'--help\'.\n"
```

**Comment by Cthutu** [comment]
> Seems you are using the wrong path, please try using the full path directly instead.

I was able to figure out what keypresses I needed to copy text of the terminal  :)

**Comment by Cthutu** [comment]
Original attempt with `cargo build`:
```
❯ cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `/home/matt/~/.cargo/bin/sccache rustc - --crate-name ___ --print=file-names -C link-arg=--ld-path=/usr/bin/mold --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)
```

**Comment by Xuanwo** [comment]
Hello, @Cthutu. There are several different problems mixed together here.

First of all, `rustc-wrapper` doesn't understand what `~` is, please apply the following diff

```diff
[build]
- rustc-wrapper = "~/.cargo/bin/sccache"
+ rustc-wrapper = "/home/matt/.cargo/bin/sccache"
```

Then, `cargo` is not a compiler, therefore `sccache` cannot be directly applied to it. Instead, please use `RUSTC_WRAPPER` or configure it through the config.

Finally, `/home/matt/~/.cargo/bin/sccache` indicates that we have configured a wrong path for `rustc-wrapper`, please apply the changes I suggested.
