### ISSUE TITLE
Allow Setting Redis Key Experation

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1666]
### Discussed in https://github.com/mozilla/sccache/discussions/1665

<div type='discussions-op-text'>

<sup>Originally posted by **jretterer-prol** March 18, 2023</sup>
In using sccache with redis along with the allkeys-lru eviction policy I was seeing keys being removed from redis even thought the allocated memory space was not fully utilized. That led me to check the TTL on the redis keys and found one is set for sccache keys.

```
127.0.0.1:6379> TTL c/7/8/c78004b4adb30628728df15ce1e99e9f862814aaa9473c1582b5b996e823439c
(integer) 86258
```

After finding that I tried to find a way to adjust this but I can't seam to find it.  So, is there a way to adjust this expiry time for redis keys or even better, set it so the time is refreshed when keys are read?</div>

**Comment by Xuanwo** [comment]
Note: OpenDAL already supports setting a TTL, so we only need to add the configuration value on the sccache side.

**Comment by Kinrany** [comment]
Is there an option for turning off key expiration completely in the meantime? With LRU unused keys will naturally be evicted over time.

[The Redis doc](https://github.com/mozilla/sccache/blob/main/docs/Redis.md) would probably be a good place for this too.

**Comment by Xuanwo** [comment]
> Is there an option for turning off key expiration completely in the meantime?

Yes, I think we can skip the TTL setting if it's `0`. Would you like to give it a try?

**Comment by Kinrany** [comment]
Yes please! How do I do that?

**Comment by Xuanwo** [comment]
> Yes please! How do I do that?

- Add a new config value for sccache: `SCCACHE_REDIS_TTL`
- Set it to via https://docs.rs/opendal/latest/opendal/services/struct.Redis.html#method.default_ttl

By the way, we are not setting any TTL on redis now.

**Comment by Kinrany** [comment]
Hmm. Brief search suggests that Redis doesn't have a default TTL either. So who is setting it? A different default in OpenDAL?

**Comment by Xuanwo** [comment]
> A different default in OpenDAL?

No, opendal doesn't set TTL by default.

**Comment by Kinrany** [comment]
Would setting TTL accomplish anything with a default Redis instance then? I'm trying to understand if that would be solving the right problem. Where does the current value come from? Do we know?
