### ISSUE TITLE
static libraries not reproducible on Mac, causes Rust cache misses

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#169]
@metajack found this while trying to use sccache to build servo on Mac. There's a crate that uses the `gcc` crate in a build script to build a static library, and the crate is always a cache miss because sccache includes the hash of the static library in the cache key, but Apple's `ld` includes timestamps in static libraries (with no way to disable that behavior, AFAICT), so the file never hashes the same.

We discussed a few remedies, including having the gcc crate zero out the timestamps on static libraries it generates, or having sccache parse static libraries and hashing only the object files within.

**Comment by froydnj** [comment]
alexcrichton/cc-rs#225 was added to make Mac `ar` invocations more deterministic, but apparently that didn't address all of the issues.  [Modifying sccache's hashing of `ar` files](https://github.com/alexcrichton/cc-rs/pull/225#issuecomment-330620663) seems like it's going to be necessary.

**Comment by metajack** [comment]
I have a WIP patch for this: https://github.com/metajack/sccache/tree/custom-hashing
