### ISSUE TITLE
[0.4.1] Test failures on Arch Linux

### ISSUE THREAD

**Issue by alucryd** [mozilla/sccache#1697]
Hi guys, I'm getting some test failures when building 0.4.1 for Arch Linux, here's the full build log: https://build.alucryd.xyz/#/builders/344/builds/31/steps/8/logs/stdio

How can I debug/fix this?

**Comment by Xuanwo** [comment]
I am unable to replicate this issue both in the CI environment and on my local machine. Could it be related to the setup of `archbuild`?

**Comment by Xuanwo** [comment]
> It's quite possible, we build packages in chroots using nspawn, maybe these tests need additional capabilities.

Since sccache will run all checks in CI, as shown in https://github.com/mozilla/sccache/actions/workflows/ci.yml?query=branch%3Amain

Maybe it's OK to not run check in archbuild?
