### ISSUE TITLE
Proposal: Make `SCCACHE_S3_NO_CREDENTIALS` require a value of `true`

### ISSUE THREAD

**Issue by ajschmidt8** [mozilla/sccache#1723]
It seems that `SCCACHE_S3_NO_CREDENTIALS` takes effect even when its value is set to non-truthy values like `SCCACHE_S3_NO_CREDENTIALS=false`.

From reviewing the source code, it looks like this is intended.

Can we switch this environment variable to require an explicit value of `true` to be enabled (e.g. `SCCACHE_S3_NO_CREDENTIALS=true`)?

The fact that `sccache` turns this feature on when this environment value is falsy (or even empty) is currently causing problems for one of the build tools that we use.

I'm happy to work on this assuming this proposal is approved.

**Comment by sylvestre** [comment]
Sounds good. I am all for hardening options.

**Comment by ajschmidt8** [comment]
PR: https://github.com/mozilla/sccache/pull/1724

**Comment by drahnr** [comment]
Generally agree, but could we also accept `0` and `1`?
