### ISSUE TITLE
Windows SDK Generates C4668 During Pre-processing - Confuses Sccache

### ISSUE THREAD

**Issue by Alexei-Barnes** [mozilla/sccache#1725]
## Issue

Sccache cannot compile some Windows applications via MSVC when `/we4668` is specified because first it tries to use the same arguments to preprocess the files, which fails within the Windows SDK.

Specifically, when trying to use sccache to cache Unreal Engine compilation (after fixing some other issues) sccache produces the error `preprocessor failed` from: https://github.com/mozilla/sccache/blob/main/src/compiler/c.rs#L339

In the include list in this error, the relevant error is visible:
```
Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\intsafe.h
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\intsafe.h(66): error C4668: '__midl' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

## Why is this a problem with sccache?

The reason sccache runs into this problem, but Unreal Engine does not, is that sccache faithfully copies all arguments for compilation into the preprocessor command it executes. However, when Unreal Engine builds, it explicitly disables this error message when preprocessing and only enables it during compiling.

## Expected behaviour

I believe the correct behaviour here is that this compiler warning should be explicitly ignored when building using MSVC.

**Comment by Alexei-Barnes** [comment]
I'm currently testing a potential fix for this now; then I'll create a PR. It's a pretty simple fix, but testing sccache with Unreal is a bit of a headache.

**Comment by Alexei-Barnes** [comment]
Does the job 👍
Creating a minimal reproduction of this that could live in a test might be a bit of a challenge, but is probably worth it.

**Comment by Alexei-Barnes** [comment]
OK, here's a minimal reproduction:

> main.cpp
```cpp
#include <iostream>
#include <intsafe.h>

int main(int, char**) {
    std::cout << "Hello world!" << std::endl;
    return 0;
}
```

> to compile
```pwsh
cl.exe -c main.cpp -nologo "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/we4668" "/D__STDC_WANT_SECURE_LIB__=1" "/EHsc"
```

> to reproduce issue
```pwsh
sccache.exe cl.exe -c main.cpp -nologo "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/we4668" "/D__STDC_WANT_SECURE_LIB__=1" "/EHsc"
```

**Comment by Alexei-Barnes** [comment]
Sample output from the above:

```pwsh
PS ~\git\reproduction-of-sccache-windows-sdk-issue> $compile = "-c", "main.cpp", "-nologo", "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\INCLUDE", "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8.1\include\um", "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt", "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared", "/we4668", "/D__STDC_WANT_SECURE_LIB__=1", "/EHsc"
PS ~\git\reproduction-of-sccache-windows-sdk-issue> cl.exe @compile
main.cpp
PS ~\git\reproduction-of-sccache-windows-sdk-issue> ..\sccache\target\debug\sccache.exe cl.exe @compile
main.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\intsafe.h(66): error C4668: '__midl' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

**Comment by Alexei-Barnes** [comment]
@aidanhs found https://gist.github.com/uucidl/f6203d2623798c26fb9ad0ba1d409276, which shows that this has been a problem hanging around for years. Arguably this is a bug with either the compiler or the Windows SDK.

**Comment by AJIOB** [comment]
Looks like my issue #2250 faces with the similar problem, but in the user code
