### ISSUE TITLE
redis cache need "expiration" in config

### ISSUE THREAD

**Issue by diablohsh** [mozilla/sccache#1791]
currently, there is no place to set expiration time for redis backend,the key expired very soon thus resulting a high cache miss rate.
after adding this code:
``use std::time::Duration;``
``builder.default_ttl(Duration::from_secs(2592000));``
the problem solved.

so, can you add an "expiration" variable to the config just like memcached backend?

**Comment by Xuanwo** [comment]
duplicated with https://github.com/mozilla/sccache/issues/1666
