### ISSUE TITLE
0.5.4 crate doesn't build on stable

### ISSUE THREAD

**Issue by steakknife** [mozilla/sccache#1865]
- rust: 1.71.1 (stable)

It was fixed in #1827, so if someone would be kind enough to bump the release, that would be groovy.

<details>

<summary>Error</summary>

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

```

</details>

<details>

<summary>Ugly temporary workaround</summary>

`cargo install --git https://github.com/mozilla/sccache sccache --locked`

</details>

**Comment by Xuanwo** [comment]
I'm guessing `cargo install sccache --locked` is enough. By adding locked, cargo will make sure to use the exactly same version we specified in `Cargo.lock`.

**Comment by steakknife** [comment]
- I always use `--locked`.
- It built with `cargo install --git https://github.com/mozilla/sccache sccache --locked`
- It builds now.
