### ISSUE TITLE
Invalid Credentials only when SCCACHE_GCS_RW_MODE is READ_ONLY

### ISSUE THREAD

**Issue by mkruskal-google** [mozilla/sccache#1886]
I setup our github CI to use sscache with a GCS bucket.  For trusted PRs, I use READ_WRITE mode, and for untrusted I use READ_ONLY.  Other than this setting, the tests are exactly the same.

What I found is that when the setting is READ_ONLY, I get the following error:
```
sccache: error: Server startup failed: cache storage failed to read: Unexpected (permanent) at read => Invalid Credentials
```

Simply changing it to unconditionally use READ_WRITE fixes the problem, but it leaves our cache open to pollution.

**Comment by Xuanwo** [comment]
Thanks for the report! It's a typo in https://github.com/mozilla/sccache/blob/bc58e4b1eab7a01580d0f2a85b8422eb4f646eef/src/cache/gcs.rs#L33C34-L33C85 which should be `https://www.googleapis.com/auth/devstorage.read_only`. Would you like t send a PR to fix this?
