### ISSUE TITLE
seems to inhibit cargo parallelism

### ISSUE THREAD

**Issue by matthiaskrgr** [mozilla/sccache#1910]
I'm using sccache git.
Since a couple of days it looks like sccache somehow inhibits parallelism when building projects, almost as if cargo would order sccache "build these 8 crates in parallel" but then sccache still builds only a single crate at a time (not much going on according to htop).
When I disable sccache via `RUSTC_WRAPPER="" cargo build --release`, I can see that my system is fully utilized again.

**Comment by matthiaskrgr** [comment]
cc @sylvestre  it looks like this is caused by this change, at least when I revert it locally, performance looks much better
https://github.com/mozilla/sccache/commit/cada7c70fddf413da5359d311d8c849a22082cf6#diff-48d27698cc708c7efe770fd897e4885efaa0a15cae30d54936068603ba03bbd9L590

**Comment by sylvestre** [comment]
OK. Many thanks for investigating

**Comment by matthiaskrgr** [comment]
Mh wait maybe there is still something weird, I'm getting mixed results now -...-

**Comment by matthiaskrgr** [comment]
Is there some better way to debug this besides looking at htop to find out "how many threads are launched" ?

**Comment by matthiaskrgr** [comment]
Ok, the good news: I can tell you that reverting both clippy commits fixed the problem for me.
the bad news: I can only tell you that reverting both clippy commits fixed the problem for me (although the `await` change still looks somewhat suspicious to me :upside_down_face: )

I feel I have nerdsniped myself already too much into this :sweat_smile:

**Comment by sylvestre** [comment]
@matthiaskrgr sorry but I can't reproduce
how do you start your rust build ?
I don't see changes with:
RUSTC_WRAPPER="/home/sylvestre/dev/debian/sccache/target/debug/sccache" cargo

could you please share step to reproduce? thanks
