### ISSUE TITLE
v0.6.0 released without assets

### ISSUE THREAD

**Issue by calavera** [mozilla/sccache#1923]
The latest release doesn't have any binaries associated to it, only source code.

This makes the `mozilla-actions/sscache-action` to fail if there is no version specified:

```
Run mozilla-actions/sccache-action@v0.0.3
try to setup sccache version: v0.6.0
sccache download from url: https://github.com/mozilla/sccache/releases/download/v0.6.0/sccache-v0.6.0-x86_64-unknown-linux-musl.tar.gz
Error: Error: Unexpected HTTP response: 404
Error: Unexpected HTTP response: 404
```

**Comment by sylvestre** [comment]
failed because
`line 7: hub: command not found`

**Comment by sylvestre** [comment]
caused by https://github.com/actions/runner-images/issues/8362

**Comment by sylvestre** [comment]
fixed:
https://github.com/mozilla/sccache/releases/tag/v0.6.0
