### ISSUE TITLE
feature request: Support config max concurrency jobs

### ISSUE THREAD

**Issue by qhsong** [mozilla/sccache#1950]
I use sccache to complier my project on 16c CPU to complier a C++ project, it seems sccache limit the jobs into cpu cores;

```bash
# ps aux|grep sccache|wc -l
131

# ps aux|grep clang++|grep -v sccache|wc -l
17
```

Seems sccache limited concurrency task into CPU count. This behavior seems not match with `ccache`. So can we set an config for max concurrent number?

**Comment by qhsong** [comment]
Seems we need modify variable here:
https://github.com/mozilla/sccache/blob/95138785383021aa8ce50b456ebfbef1277840ee/src/jobserver.rs#L27

**Comment by sylvestre** [comment]
feel free to provide a PR

**Comment by qhsong** [comment]
As a new Ruster, let me try here ...

**Comment by pomo-mondreganto** [comment]
I believe my latest PR #1993 fixes this issue
