### ISSUE TITLE
Failed to install sccache 0.73

### ISSUE THREAD

**Issue by k82cn** [mozilla/sccache#1988]
When installing sccache v0.7.3, got the following error:

```
   Compiling opendal v0.40.0
error[E0063]: missing field `tls_params` in initializer of `ConnectionAddr`
   --> /home/vagrant/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.40.0/src/services/redis/backend.rs:276:17
    |
276 |                 ConnectionAddr::TcpTls {
    |                 ^^^^^^^^^^^^^^^^^^^^^^ missing `tls_params`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `opendal` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

Here's the environment information:
```
$ uname -a
Linux swx-forge04 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release
No LSB modules are available.
[klausm@swx-forge04 minikube]$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by cajus** [comment]
Same here on Fedora 39, but seems to be more of an opendal / redis 0.22->0.23 problem.

**Comment by sylvestre** [comment]
Try
cargo build --locked

**Comment by Xuanwo** [comment]
FYI: redis `0.23.4` has been yanked

https://github.com/redis-rs/redis-rs/issues/995#issuecomment-1827926026

**Comment by Xuanwo** [comment]
NOTE: Please always use `cargo install sccache --locked` to make sure sccache is using the `Cargo.lock` we provided.

Firstly, it makes sure that your build work as expeceted. 

Secondly, it protects you from supply chain attacks. Consider this scenario: if someone hacks into our dependency `abc`'s account and pushes a new release containing malicious code, all your code would be compromised.

The only way to protect to use `cargo install sccache --locked`.
