### ISSUE TITLE
Version of sccache available on apt has all backends disabled

### ISSUE THREAD

**Issue by rkargon** [mozilla/sccache#1998]
When installing sccache via `apt get install sccache`, it seems that that binary was compiled with all of the different backends disabled: 

```
user@host/dir# apt-get install sccache
user@host/dir# sccache --version
sccache 0.4.0-pre.6
user@host/dir# sccache --help
... 

Enabled features:
    S3:        false
    Redis:     false
    Memcached: false
    GCS:       false
    GHA:       false
    Azure:     false
```

However, manually downloading the binary provided on the github 'Releases' page for v.0.4.1 seems to work fine:
```
# ./sccache --version
sccache 0.4.1
# ./sccache --help
Enabled features:
    S3:        true
    Redis:     true
    Memcached: true
    GCS:       true
    GHA:       true
    Azure:     true
```

Is there any change the apt repository could be updated with a version of sccache that supports more backends? (I personally am trying to use the GCS backend)

The output of `apt-cache show sccache` for the current version of sccache that apt has is below:
```
Package: sccache
Source: sccache (0.4.0~~pre6-1)
Version: 0.4.0~~pre6-1+b1
Installed-Size: 4438
...
Filename: pool/main/s/sccache/sccache_0.4.0~~pre6-1+b1_arm64.deb
Size: 1219572
MD5sum: d7a0537724577ae60b6c65acd77200ab
SHA256: 2cc1a74faca570200b25844baf41ad6b3f3c9ae1b0491560a7ed197816df32a7
```

**Comment by sylvestre** [comment]
We don't maintain the debian packages. Please report it in debian.

Also, it is a pretty old version of sccache. You should use the binary available on github instead.

@jonassmedegaard could you please share your plans wrt sccache? Thanks

**Comment by jonassmedegaard** [comment]
I agree with sylvestre: How downstream distributions treat a project should be discussed with them, so please file a bugreport against the Debian package (for which I am the maintainer) and let's discuss further there.
