### ISSUE TITLE
Look into replacing protobuf with serde

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#20]
We're using protobuf for the client/server protocol right now. It's kind of a pain. We should look into just using serde instead, and defining a few Rust structs to serialize over the socket. I know serde is a bit difficult to use in non-nightly Rust, but if we get it working with nightly and it looks good we can jump through the hoops to make it work in stable Rust.

**Comment by luser** [comment]
serde uses the "macros 1.1" feature that's on track for stabilization now, so it should be feasible to use this without requiring a nightly compiler soon.

**Comment by alexcrichton** [comment]
Nowadays the way to implement this I believe would be:

* Update the server's [codec](https://github.com/mozilla/sccache/blob/6dba30a3afa512837598f079c5a94bd55468a101/src/server.rs#L814-L871) to not use protobuf, but keep the In/Out types the same
* Update the client's [parsing code](https://github.com/mozilla/sccache/blob/6dba30a3afa512837598f079c5a94bd55468a101/src/client.rs#L53-L77) to use the same logic as the server

**Comment by luser** [comment]
This was fixed by #85.
