### ISSUE TITLE
Add native aliyun oss support (mentorship available)

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#2043]
Hi, sccache community.

It's a long-term issues that users want to connect sccache with [aliyun oss](https://www.alibabacloud.com/zh/product/object-storage-service) which is definitely possible since [Apache OpenDAL](https://github.com/apache/incubator-opendal) provides native support for OSS.

## Tasks

- Add oss related config
- Add oss storage
- Using an OSS bucket (Please ensure you have one prepared. The free tier ought to suffice.).

## Mentorship

@xuanwo is willing to offer mentorship to help address this issue effectively. @xuanwo promises to respond to your questions regarding the implementation of this feature within 24 hours, excluding weekends.

After finishing this issue, you will

- Know more about rust!
- Know more about sccache's stroage layer
- Able to implement new storage integration for sccache

---

Close https://github.com/mozilla/sccache/issues/1167

**Comment by PsiACE** [comment]
I want to try this issue, I am very interested in sccache.

**Comment by Xuanwo** [comment]
> I want to try this issue, I am very interested in sccache.

Thanks a lot, let's rock!

**Comment by Xuanwo** [comment]
Hi @PsiACE, what are your plans regarding this issue? Would you like to schedule a kick-off meeting?

**Comment by PsiACE** [comment]
> Hi @PsiACE, what are your plans regarding this issue? Would you like to schedule a kick-off meeting?

Let me make some random attempts first. I have already read the code for webdav integration.

**Comment by PsiACE** [comment]
> Perfect!

I have already used some code to complete the basic filling. If the test passes, I will submit a PR. Wish me good luck.
