### ISSUE TITLE
0.7.6 includes a breaking change, but is a semver "minor".

### ISSUE THREAD

**Issue by arilotter** [mozilla/sccache#2057]
0.7.6 adds a **mandatory** `ttl` field to the `[cache.redis]` section of sccache_config.

A config file that worked perfectly in 0.7.5:

```
[cache.redis]
url = "redis://redis.internal.devserver.local:6379/0"
```

In 0.7.6, now throws the error:
```
  sccache: error: Failed to load config file
  sccache: caused by: Failed to load toml config file from /root/.config/sccache/config
  sccache: caused by: TOML parse error at line 1, column 1
    |
  1 | [cache.redis]
    | ^^^^^^^^^^^^^
  missing field `ttl`
  ```

This makes 0.7.6 a release with breaking changes, and by semver, it should be labeled as 0.8.0, or the requirement for the `ttl` key should be dropped and a default used instead.

**Comment by arilotter** [comment]
@sylvestre I opened https://github.com/mozilla/sccache/pull/2058 that i think fixes it

**Comment by sylvestre** [comment]
thanks!

**Comment by sudhackar** [comment]
thanks!
