### ISSUE TITLE
Make hashes less dependent on source and build paths

### ISSUE THREAD

**Issue by mbitsnbites** [mozilla/sccache#207]
Currently I was not able to properly use a shared cache between two machines without them using the exact same source and build folders, which seems quite unnecessary.

Apparently (according to #4 ), there are already some thoughts for how to fix this?

~~My gut feeling is that since the preprocessed result is what's being hashed (together with the command line flags that affect how the compilation is performed), things like file names (input, output) and include paths should not be important at all, so you should be able to remove them from the hash completely, right? (this includes `-I`, `-o`, `-MT`, `-MF`, `-include` etc, plus the source file name)~~

**Comment by mbitsnbites** [comment]
...come to think of it: flags for preprocessor defines (`-D`, `-U`, `-undef`, and similar) should also be possible to exclude from the hash. That would be a huge win for projects that use different compile-time configurations, since many compilation units are pre-processed to the same code regardless of configuration.

I don't know how these things are treated in sccache today, though.

**Comment by mbitsnbites** [comment]
Forget everything I've said about compiler flags and paths. I did some debugging of `generate_hash_key()`, and `parsed_args.common_args` seems to be very clean, containing only flags that affect the post-preprocessing compilation step.

Same thing for the environment flags, where only `MACOSX_DEPLOYMENT_TARGET` and `IPHONEOS_DEPLOYMENT_TARGET` affect the hash.

However, the **preprocessor output** contains lots of paths, at least for gcc. These are typically of the form:
```c++
# 1 "/home/alice/git/coolproject/modules/foo/src/cool_source.cpp"
# 1 "/home/alice/git/coolproject-build/Release//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "/home/alice/git/coolproject/modules/foo/src/cool_source.cpp"
...
```
A relatively simple solution (that hopefully works) would be to strip the preprocessor output of all lines starting with `# `.

**Comment by mbitsnbites** [comment]
PR #208 addresses this issue for GCC and Clang.

I'm not sure if the corresponding problem exists for MSVC.

**Comment by mqudsi** [comment]
Does this issue affect other languages like rust?

**Comment by mqudsi** [comment]
Thank you for that kind reply. I think cargo could structure things differently on its end to remove some unnecessary duplication and simultaneously make sccache's life easier; I had originally proposed some sort of fs-local cache on cargo's end in a github issue and that's when I was first informed about sccache and the difficult problems it was trying to solve :)

**Comment by daniel-sherwood** [comment]
Hi - I have just upgraded to a build including these fixes and it seems to work with two directories on the same machine, however I am still getting 100% cache misses when running on a different machine.  Can you suggest how I go about debugging this to establish the cause of the cache misses?
