### ISSUE TITLE
sccache version on pypi is out of date

### ISSUE THREAD

**Issue by robertmaynard** [mozilla/sccache#2125]
The pypi version of sccache ( https://pypi.org/project/sccache/ ) is on 0.7.4 and needs to be updated due to that release have severe issues. We should update ASAP to 0.7.6+

**Comment by Xuanwo** [comment]
This package is maintained by @messense, do you want take a look? And maybe we can integrate it in sccache's workflow instead.

**Comment by robertmaynard** [comment]
Thanks @Xuanwo, I didn't know what the best process was for tagging messense or if this was already being uploaded by some workflow

**Comment by sylvestre** [comment]
@messense could you please grant me permissions? thanks
https://pypi.org/user/Sylvestre/

thanks

**Comment by messense** [comment]
@sylvestre Just tried but PyPI says `User 'Sylvestre' does not have a verified primary email address and cannot be added as a Maintainer/Owner for project`

**Comment by sylvestre** [comment]
@messense done, thanks

**Comment by messense** [comment]
FYI, pypi version has been updated to 0.7.7 now (dropped Linux i686 wheel for now because I'm [having trouble compile it](https://github.com/messense/crate-wheels/actions/runs/8158289499/job/22299878604#step:4:977) on CentOS 7 Docker container).

https://pypi.org/project/sccache/0.7.7/#files

**Comment by robertmaynard** [comment]
Thank you!

**Comment by sylvestre** [comment]
@messense thanks!
have you been able to add me? thanks!

**Comment by messense** [comment]
Yes, please check your email.
