### ISSUE TITLE
Set User Agent Header for S3 Requests

### ISSUE THREAD

**Issue by ajschmidt8** [mozilla/sccache#2136]
## Feature Request

As defined by MDN ([src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent)):

> The User-Agent request header is a characteristic string that lets servers and network peers identify the application, operating system, vendor, and/or version of the requesting user agent.

I'd like to request that `sccache` set a user-agent header for requests to AWS/S3. The user-agent header should include the `sccache` version.

## Use Case

AWS supports writing IAM policies that block access to resources based on the user-agent header: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-useragent.

I'd like to write a policy that denies access to an S3 bucket for versions of `sccache` that are affected by #2038.

**Comment by ajschmidt8** [comment]
cc: @Xuanwo in case this option needs to be exposed in opendal

**Comment by Xuanwo** [comment]
As mentioned in https://github.com/apache/opendal/issues/4389#issuecomment-2017579898, this should already be simple. Let me mark this as `good first issue` and `help wanted`. Feel free to take this if you want to implement it too.

**Comment by ajschmidt8** [comment]
@Xuanwo, thanks. PR here: https://github.com/mozilla/sccache/pull/2137.
