### ISSUE TITLE
Add i686 musl builds to releases

### ISSUE THREAD

**Issue by matthauck** [mozilla/sccache#216]
Would be really cool if you guys release i686 musl binary releases as well.

**Comment by matthauck** [comment]
For the record, I was able to get it working with docker containers `messense/rust-musl-cross:i686-musl`  and `messense/rust-musl-cross:x86_64-musl`.

**Comment by matthauck** [comment]
Yeah, we do have linux 32-bit c++ build environments. 

Also, while we're talking about released builds, it looks like the binaries posted don't support redis. I personally expected those to be built with `--features all`. 

I was able to get it going myself, so I'm :ok_hand:, just a suggestion to perhaps ease adoption for people not familiar with rust to be able to just download a binary that supports all the features.

**Comment by luser** [comment]
> Also, while we're talking about released builds, it looks like the binaries posted don't support redis. I personally expected those to be built with --features all.

Oh, that's an oversight, thanks! The normal Travis builds do build with `--features all`, but release builds use a separate script. I'll fix that up for the next release, and also see if I can get an i686 build setup.

**Comment by matthauck** [comment]
I was able to build i686/x64 versions this way:

```
docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:i686-musl \
    sh -c "cargo build --release --features=all --target i686-unknown-linux-musl"
docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl \
   sh -c "cargo build --release --features=all --target x86_64-unknown-linux-musl"
```

**Comment by luser** [comment]
I've used a Docker image to produce musl builds locally as well, but I don't think I can do that in Travis, and that's what I'm using for release builds now. If it's possible to do so I'd be fine with that, or if you can otherwise find a workaround to make the i686-musl build work, that's also fine. Sorry this is such a hassle!

**Comment by rillian** [comment]
Supposedly you can [use custom Docker images](https://docs.travis-ci.com/user/docker/) on Travis. I haven't tried myself, but the Rust project does this for their builds.

You probably need a `docker cp` command to retrieve the artifact for publication.
