### ISSUE TITLE
Support using authentication on s3 get requests

### ISSUE THREAD

**Issue by johnklai1** [mozilla/sccache#217]
Our s3 bucket requires authorization for get requests as well, and I noticed that the s3 implementation only sets authorization for put requests.  I have a change that uses credentials for the get requests as well, but I'm not sure if this needs to be configurable (e.g. only use credentials for get requests if some environment variable is set).

https://github.com/johnklai1/sccache/commit/8660c006d965947b4eac0082a072f6e98d8d3a80

**Comment by luser** [comment]
Yeah, I would like to be able to preserve the existing behavior, it's what we use in Firefox CI (our s3 buckets are world-readable). It's slightly faster to do unauthenticated GET requests if possible. I'd love to support this as well, though. We've been hung up for a while by sccache not supporting a config file, which would make it much more straightforward to have nontrivial configurations.

**Comment by jechase** [comment]
#135 implements this feature in a configurable manner. I've been maintaining my fork which includes it for use in my company's build pipeline until it gets merged.

**Comment by Xuanwo** [comment]
Has been implemented.

cc @sylvestre Please close this issue.
