### ISSUE TITLE
S3 has 100% of misses all of the time

### ISSUE THREAD

**Issue by kornelski** [mozilla/sccache#218]
How can I diagnose issues with sccache apparently not working with S3? 

```sh
export SCCACHE_BUCKET=…
export AWS_ACCESS_KEY_ID=…
export AWS_SECRET_ACCESS_KEY=…
export RUSTC_WRAPPER=$(which sccache)
cargo clean
cargo build --release
cargo clean
cargo build --release
```

If I do the above without setting up S3, I get cache hits on local disk.

However, with S3 enabled I only get cache misses. The S3 bucket remains completely empty.

How can I diagnose what went wrong?

> Compile requests               233
Compile requests executed      205
Cache hits                       0
Cache misses                   205
Cache timeouts                   0
Cache read errors                0
Forced recaches                  0
Cache write errors             181
Compilation failures             0
Cache errors                     0
Non-cacheable compilations       0
Non-cacheable calls             28
Non-compilation calls            0
Unsupported compiler calls       0
Average cache write          0.000 s
Average cache read miss      6.322 s
Average cache read hit       0.000 s
Cache location             S3, bucket: Bucket(name=…, base_url=http://….s3.amazonaws.com/)

**Comment by kornelski** [comment]
export RUST_LOG=sccache=trace /Users/porneL/.cargo/bin/sccache rustc …
cat sccache.log

**Comment by luser** [comment]
Did you get this sorted out? We have an existing issue on file about this: https://github.com/mozilla/sccache/issues/45

Right now it's hard to diagnose if your S3 configuration isn't correct.

**Comment by kornelski** [comment]
Yes, I've eventually found the log, and that put requests were failing. Eventually it turned out to be permissions problem (I can't believe I had to write custom JSON to set up such a basic thing as protected s3 bucket).

It'd be great if you could add proper diagnostic for it, e.g. try making a PUT request at server startup and fail loudly if that request is rejected.

**Comment by turbo** [comment]
I seond @kornelski 's suggestion.
