### ISSUE TITLE
migrate from `winapi` to `windows-rs`

### ISSUE THREAD

**Issue by ognevny** [mozilla/sccache#2185]
## motivation

`winapi` hasn't been updated for more than 3 years and the maintainer said that they have no motivation to continue the development of it. for now the recommended approach is to use `windows-rs`, which also has support for `*-gnullvm` windows targets

**Comment by Xuanwo** [comment]
Makes sense, would you like to submit a PR for this? I'm willing to help review and get it's merged.

**Comment by ognevny** [comment]
> Makes sense, would you like to submit a PR for this? I'm willing to help review and get it's merged.

I can try to do this

**Comment by ognevny** [comment]
I have some work implemented: https://github.com/ognevny/sccache/tree/migrate-from-winapi. but there are lots of errors as some API is needed to be adjusted. currently I have no idea what to do with them

**Comment by ognevny** [comment]
> I will take a look, thanks!

I still didn't make any change with that branch... migration from winapi requires for some code "remake" since bindings from microsoft work in a bit another way

**Comment by Xuanwo** [comment]
I failed to implement it because I know very little about Windows. However, my friend @berrysoft, who is an expert in Windows, is interested in this issue and is currently working on it.
