### ISSUE TITLE
Can't select the `redis` feature

### ISSUE THREAD

**Issue by Dalzhim** [mozilla/sccache#239]
I tried building `sccache` using the following alternatives :
* `cargo build --features redis --release`
* `cargo build --features all --release`
* `cargo build --all-features --release`

Every time I had the same problem, executing `sccache` displayed that `redis` was not part of the enabled features.

I ended up being successful by using the same `--features redis` for both `cargo build` and `cargo install` as so :
1. `cargo build --features redis --release`
1. `cargo install --features redis --force`

Updating the documentation with this information could save others a lot of wasted time!

**Comment by flxo** [comment]
By calling `sccache` you probably executed a `sccache` binary you installed before in `~/.cargo/bin` which is usually added to `PATH` during the `rustup` installation. 
The binaries you built with one of the three cargo invocations listed go to `target/release/sccache`.

A `cargo build` just builds. A `cargo install` implies the build step *and* copies the artefact to `~/.cargo/bin` (don't remember where this is on Windows).

**Comment by Xuanwo** [comment]
Thank for @flxo's answer. I believe this issue has been resovled.

cc @sylvestre Please close this issue.
