### ISSUE TITLE
Building sccache from source and making it ASAN clean

### ISSUE THREAD

**Issue by yf225** [mozilla/sccache#247]
I am working on https://github.com/yf225/sccache which adds NVCC support to sccache. One thing I noticed is that if I build sccache from source (with `cargo build && cargo install -f`) and run it with ASAN, I will get this segfault: https://github.com/rust-lang/rust/issues/50492. However, running the released binary https://github.com/mozilla/sccache/releases/ with ASAN works fine.

I am wondering what are the particular settings that were used in producing the released binaries? And could you help with building a custom binary based on https://github.com/yf225/sccache? I am also planning to open a PR for NVCC support into the main repo, after I add some unit tests to `nvcc.rs`.

Thanks!

**Comment by luser** [comment]
The release binaries get built targeting `x86_64-unknown-linux-musl`:
https://github.com/mozilla/sccache/blob/037a96ef5e8e9258a62cd712edc912b0b1327413/.travis.yml#L19

The script that gets run there just installs the right target via rustup and also builds a copy of OpenSSL against musl:
https://github.com/mozilla/sccache/blob/037a96ef5e8e9258a62cd712edc912b0b1327413/scripts/travis-musl-openssl.sh

**Comment by yf225** [comment]
@luser This works, thanks a lot!
