### ISSUE TITLE
Rework server to use tokio

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#25]
In the intervening time since I started writing sccache2, the `futures` crate had its first release, and the `tokio-core` crate was released alongside it. The API for that is much nicer than the mio 0.5 API that sccache2 is currently using, and it'd mean we could use `Future`s instead of my half-baked `Task` implementation. I've already pulled in `future` for one thing, we might as well just refactor the whole server to use tokio.

**Comment by luser** [comment]
This might be worth waiting for hyper to support futures: https://github.com/hyperium/hyper/issues/934

**Comment by luser** [comment]
@alexcrichton suggested that we ought to use [`tokio-curl`](https://github.com/tokio-rs/tokio-curl) for HTTP instead, and he also mentioned that [`tokio-process`](https://github.com/alexcrichton/tokio-process) should fit into our use case pretty well.

**Comment by alexcrichton** [comment]
Finished in #70!
