### ISSUE TITLE
Unable to use Azure redis

### ISSUE THREAD

**Issue by CoRfr** [mozilla/sccache#250]
Because of an issue with how redis-rs handles passwords, I was not able to use Azure redis service at this time.

Problem is that passwords generated contains an = sign.

I opened issue https://github.com/mitsuhiko/redis-rs/issues/152 but the `redis` version would need to be updated once this is resolved.

**Comment by luser** [comment]
If a version of the redis crate gets released with the fix I'd be happy to take a PR to update the dependency here!

**Comment by Xuanwo** [comment]
SHould be fixed by https://github.com/mozilla/sccache/issues/1404. Feel free to report issues if azure redis still can't connect.
