### ISSUE TITLE
sccache's terminal detection for color support doesn't work the same as rustc

### ISSUE THREAD

**Issue by andreastt** [mozilla/sccache#254]
sccache does not appear to pass on the original environment variables when cargo/rustc is invoked. Setting `RUSTC_WRAPPER=sccache` causes all other set environment variables, such as `TERM=dumb`, to not take effect.

This can be reproduced in a dumb terminal:

```
% RUSTC_WRAPPER=sccache cargo build --target x86_64-pc-windows-gnu
   Compiling libc v0.2.39
   Compiling cfg-if v0.1.2
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.4
   Compiling log v0.4.1
   Compiling rand v0.3.18
   Compiling tempdir v0.3.5
   Compiling mozprofile v0.3.0 (file:///home/ato/src/gecko/testing/mozbase/rust/mozprofile)
   Compiling winreg v0.5.0
   Compiling mozrunner v0.6.1 (file:///home/ato/src/gecko/testing/mozbase/rust/mozrunner)
[0m[1m[38;5;9merror[E0308][0m[0m[1m: mismatched types[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0mtesting/mozbase/rust/mozrunner/src/runner.rs:410:13[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m410[0m[0m [0m[0m[1m[38;5;12m| [0m[0m            Some(path) if is_binary(&path) => Some(path),[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m            [0m[0m[1m[38;5;9m^^^^^^^^^^[0m[0m [0m[0m[1m[38;5;9mexpected enum `std::result::Result`, found enum `std::option::Option`[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: expected type `[0m[0m[1mstd::result::Result<[0m[0mstd::option::Option<[0m[0m[1mstd::path::PathBuf[0m[0m>, [0m[0m[1mstd::io::Error>[0m[0m`[0m
[0m               found type `std::option::Option<[0m[0m[1m_[0m[0m>`[0m

[0m[1m[38;5;9merror[E0308][0m[0m[1m: mismatched types[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0mtesting/mozbase/rust/mozrunner/src/runner.rs:436:46[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m436[0m[0m [0m[0m[1m[38;5;12m| [0m[0m                                if is_binary(path) {[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m                                             [0m[0m[1m[38;5;9m^^^^[0m[0m [0m[0m[1m[38;5;9mexpected reference, found struct `std::string::String`[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: expected type `[0m[0m[1m&std::path::PathBuf[0m[0m`[0m
[0m               found type `[0m[0m[1mstd::string::String[0m[0m`[0m

[0m[1m[38;5;9merror[0m[0m[1m: aborting due to 2 previous errors[0m

[0m[1mFor more information about this error, try `rustc --explain E0308`.[0m
error: Could not compile `mozrunner`.

To learn more, run the command again with --verbose.
```

In a normal terminal the difference can be observed by the fact that `RUSTC_WRAPPER=sccache TERM=dumb` not silencing the colour escape sequences:

<img width="920" alt="screen shot 2018-06-05 at 13 30 38" src="https://user-images.githubusercontent.com/399120/40976198-390a5ba8-68c5-11e8-8c00-fefdae0f33f6.png">

I originally reported this as https://github.com/rust-lang/rust/issues/50645, thinking it was a rustc problem with diagnostic annotations, but further investigation showed that it was sccache that did not pass on the environment.

**Comment by andreastt** [comment]
Or is it the other way around? That it is cargo, in the event of `RUSTC_WRAPPER=sccache`, that does not pass on the environment?

**Comment by luser** [comment]
sccache passes all the environment variables down to rustc, but it has special handling for color output:
https://github.com/mozilla/sccache/blob/bbff69f2c748339726b7c12fb175eeceea451870/src/commands.rs#L452

It's just using the `atty` crate to detect whether stdout is a terminal and thus it should write colored output. I added this because sccache always pipes rustc's output, so rustc wouldn't write color output like it does by default. (#99)

Does rustc have some fancier terminal detection? If there's some easy-to-use crate we can plug in here I'm happy to do that.

**Comment by fbernier** [comment]
Also getting this issue. Weirdly, I get colors with `--release` builds or with `--color=always`. Here's how rustc seem to do it: https://github.com/rust-lang/rust/blob/master/src/librustc_errors/emitter.rs#L113

**Comment by luser** [comment]
Ah! rustc passes that down to `termcolor`, which must do something smarter.

**Comment by luser** [comment]
While attempting to fix the issue I mentioned in the previous comment I realized that there's another branch here which needs to be addressed:
https://github.com/mozilla/sccache/blob/bbff69f2c748339726b7c12fb175eeceea451870/src/commands.rs#L534-L549

Specifically, unhandled compiles get run by the client, but currently we pipe the compiler output and then write it to stdout/stderr, which breaks things in the opposite way, by making rustc unable to detect that it's running in a terminal.

**Comment by fbernier** [comment]
Thanks for you work!
