### ISSUE TITLE
Support --coverage

### ISSUE THREAD

**Issue by marco-c** [mozilla/sccache#258]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1334940.

ccache supports it: https://lists.samba.org/archive/ccache/2015q1/001273.html.

**Comment by luser** [comment]
I don't think this would be terribly hard to support. sccache currently knows [to handle `-fprofile-generate`](https://github.com/mozilla/sccache/blob/512826537da482e3f94709d372193eb5221808e0/src/compiler/gcc.rs#L125), but doesn't do a whole lot with it.

[The GCC docs for `-fprofile-generate`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fprofile-generate) say that that option enables `-fprofile-arcs`, which is what actually causes gcc to produce the .gcno outputs, and [the docs for `--coverage`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-coverage) say that that option also enables `-fprofile-arcs`, so we should add entries to the gcc `ARGS` list to handle both `-fprofile-arcs` and `--coverage` as `ProfileGenerate`, and then add some logic to include the .gcno output in the list of outputs similar to [how we handle `-gsplit-dwarf` currently](https://github.com/mozilla/sccache/blob/512826537da482e3f94709d372193eb5221808e0/src/compiler/gcc.rs#L294).

**Comment by gabriel-v** [comment]
The way I read it, `-fprofile-arcs` instruments the outputs to create `.gcda` files when being run. On the other hand, `-ftest-coverage` is what's going to create the `.gcno` files we want to pick up here.
