### ISSUE TITLE
Error when an unsupported compiler is found

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#261]
We switched Firefox CI to use clang-cl but hadn't updated sccache to pick up [this fix](https://github.com/mozilla/sccache/commit/037a96ef5e8e9258a62cd712edc912b0b1327413), so sccache returned "unsupported compiler" and didn't cache any of our C++ compilation, but we didn't notice because the clang-cl build was faster anyway! See [this bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1476604#c3) for more details.

It would be useful to at least have an option to error when an unsupported compiler is detected so that we could catch this by failing the build. It might also be sensible to make this the default? It definitely seems like something people would want to know.

**Comment by na-g** [comment]
Perhaps this could be implemented as a default behavior which could be toggled off per expected unknown compiler with a whitelist.  As new but expected unknown compilers are discovered they could be added to the whitelist, and errors would only occur when a new unknown compiler is discovered.

**Comment by luser** [comment]
I'm going to make this always an error for now. If someone finds a compelling reason to do otherwise we can add an option.
