### ISSUE TITLE
Handle -Xclang for clang-cl

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#262]
We added basic support for clang-cl recently, but we don't handle`-Xclang`, which can be used to pass options down to the clang frontend (vs. the clang-cl frontend which parses MSVC options). We use this in Firefox builds to pass down GCC-style dependency options, like:
`-Xclang -MP -Xclang -dependency-file -Xclang .deps/lz4.obj.pp -Xclang -MT -Xclang lz4.obj`

Currently sccache refuses to cache these compiles because it thinks the arguments to `-Xclang` that do not start with a dash are input source files, and it will not cache a compile with multiple source files. At the very least we need it to understand that `-Xclang` takes an argument so that it parses the commandline correctly.

A more thorough followup would be to correctly detect clang-cl as clang-cl, and parse its commandlines with MSVC arguments but also accumulate `-Xclang` arguments into a separate list and then parse them with the clang argument parser, which might be a bit hairy. Otherwise we won't properly cache compiles like the example above, where we're instructing clang-cl to output a dependency file.

**Comment by luser** [comment]
The changes in https://github.com/mozilla/sccache/pull/271 add support for this.

**Comment by luser** [comment]
I finally got around to testing this locally now that #271 has merged and it does indeed fix the issue we were hitting:
```
$ /c/build/sccache/target/debug/sccache.exe ~/.mozbuild/clang/bin/clang-cl.exe -Fohello.obj -c hello.c -I.
$ /c/build/sccache/target/debug/sccache.exe ~/.mozbuild/clang/bin/clang-cl.exe -Fohello.obj -c hello.c -I.
$ /c/build/sccache/target/debug/sccache.exe --show-stats
Compile requests                 2
Compile requests executed        2
Cache hits                       1
Cache misses                     1
<...>
$ /c/build/sccache/target/debug/sccache.exe ~/.mozbuild/clang/bin/clang-cl.exe -Fohello.obj -c hello.c -I. -Xclang -MP -Xclang -dependency-file -Xclang hello.obj.pp -Xclang -MT -Xclang hello.obj
$ /c/build/sccache/target/debug/sccache.exe --show-stats
Compile requests                 3
Compile requests executed        3
Cache hits                       2
Cache misses                     1
<...>
```

**Comment by emerick** [comment]
That's fantastic, thanks!
