### ISSUE TITLE
Don't pass /Brepro to the preprocessor for MSVC/clang-cl

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#264]
clang-cl warns if you pass `/Brepro` while preprocessing:
```
$ ~/.mozbuild/clang/bin/clang-cl.exe -E test.c -Brepro
clang-cl.exe: warning: argument unused during compilation: '-mno-incremental-linker-compatible' [-Wunused-command-line-argument]
```

We need to add `/Brepro` to [the list of known args](https://github.com/mozilla/sccache/blob/df13487fad5874f144ce1316c999170ac3803237/src/compiler/msvc.rs#L207), and I guess add a new variant to `MSVCArgAttribute` like `CompilationArgument` for arguments that we don't want to pass to the preprocessor, and handle that appropriately in `parse_arguments`. It looks like the MSVC code doesn't currently have a good way to support this, so it might need some tweaking. The `ParsedArguments` struct does have a `preprocessor_args` member that the MSVC code isn't using, so it'd probably be easiest to refactor things to put preprocessor-specific args there and not use `common_args` when running the preprocessor.

**Comment by luser** [comment]
This should be more easily fixable after the refactoring that landed in https://github.com/mozilla/sccache/pull/271 . The code has been changed to separate out preprocessor arguments, so we'd just need to handle this argument so that it doesn't get added to `common_args`.

**Comment by wenjunche** [comment]
any updates ?

I just tested  0.2.8-alpha.0 and it is still happening.

Thanks

**Comment by sylvestre** [comment]
thanks
