### ISSUE TITLE
Rusoto now has a standalone credentials module

### ISSUE THREAD

**Issue by indiv0** [mozilla/sccache#28]
It looks like rusoto support was dropped in 657cb895f12bb0e51f950b6d62b1ff24a59ad9a8 for various reasons. However, you retained the rusoto credentials code in the form of an extracted file ([src/simples3/credential.rs](https://github.com/mozilla/sccache/blob/6eadccc9d6752747766d550388590199d87f23a5/src/simples3/credential.rs)).

It might interest you to know that rusoto now has a [standalone credentials module](https://crates.io/crates/rusoto_credential), which is published and functions independently of the main rusoto module. If you are interested in using it in your project, I can look into porting the modifications you've made to your version of the module into ours.

**Comment by luser** [comment]
Oh, that would be super useful! FWIW, I liked Rusoto, I was just hitting some hard-to-diagnose issues and my S3 needs were fairly simple. I've only made a few small changes to the credentials module, I'd be happy to submit them as PRs.

**Comment by indiv0** [comment]
That would be great, actually. As for rusoto itself, we're close to landing an important PR (https://github.com/rusoto/rusoto/pull/321) which will bring S3 in line with the rest of the codebase (currently it's mostly hand-crafted, legacy code from before our major re-write). Once that's done, I can help you migrate back to it as it's going to be much less problematic.

**Comment by Xuanwo** [comment]
This issue has been resolved by https://github.com/mozilla/sccache/issues/1404
