### ISSUE TITLE
Handle clang plugins somehow

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#288]
We use a clang plugin to do static analysis in Firefox CI, and @glandium noted that sccache does not currently handle clang plugins at all. The simplest thing I could think to do here would be to include the contents of the plugin file as part of the hash. That would only work well if the plugin is built in a reproducible manner, of course.

Annoyingly, the traditional way of loading a clang plugin is to pass it down to `cc1` [with a bunch of `-Xclang` options](https://clang.llvm.org/docs/ClangPlugins.html#using-the-cc1-command-line) and of course [that's what we use in the Firefox build](https://dxr.mozilla.org/mozilla-central/rev/9c13dbdf4cc9baf98881b4e2374363587fb017b7/build/autoconf/clang-plugin.m4#160). [The clang docs do say](https://clang.llvm.org/docs/ClangPlugins.html#using-the-clang-command-line) that you can use `-fplugin=plugin` now, and supporting that sounds easier, so maybe we can fix the Firefox build to use that and just support that?

**Comment by luser** [comment]
To clarify--I don't think this is really *terrible*, it just means that if we change the plugin source it effectively won't get run on sources where we get cache hits. (I'm actually not 100% sure on this and we probably need to do some testing, because presumably we *would* include it as part of the preprocessor run, but I don't know if it would actually get invoked.) This shouldn't be a big issue for Firefox builds, since the plugin just does static analysis checks, so the only place this would be a problem would be if a new check was added.

**Comment by luser** [comment]
I filed a bug on using `-fplugin=path` in the Firefox build: https://bugzilla.mozilla.org/show_bug.cgi?id=1487070

**Comment by chmanchester** [comment]
This was taken care of in 0a85712a23b586621d2a5d471f44530b94795cec, but I will open a pull request to handle the `-fplugin=` case similarly.
