### ISSUE TITLE
Rust code fails to compile with sccache on Windows

### ISSUE THREAD

**Issue by buttercookie42** [mozilla/sccache#293]
I'm trying to build Firefox on Windows 7 (with clang). When I enable sccache (built from the current master branch), compilation of Rust code fails with something like
> 0:10.44 error: command failed: 'rustc.exe'
> 0:10.44 info: caused by: Das Handle ist ungültig. (os error 6)
> 0:10.46 error: Could not compile `winapi`.

Additionally, while I'm not sure if it's related or not, on some attempts to build I've also noticed what I think were "rustc" commandline windows momentarily flashing in and out of existence, something that I never noticed to happen when building without sccache.

**Comment by luser** [comment]
Thanks for filing this! I'll test this when I have time tomorrow and see what happened.

**Comment by luser** [comment]
The error printed there is `ERROR_INVALID_HANDLE`, FWIW.

**Comment by luser** [comment]
With sccache master (dda88a658c0f48994527c201e15f736ad193da4f) and rustc 1.28.0 I'm able to compile a small test crate without issues:
```
$ RUSTC_WRAPPER=/c/build/sccache/target/debug/sccache.exe cargo build -v
   Compiling itoa v0.3.4
     Running `c:/build/sccache/target/debug/sccache.exe rustc --crate-name itoa 'C:\Users\ted\.cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=8fdbbc2ecc32a839 -C extra-filename=-8fdbbc2ecc32a839 --out-dir 'c:\build\snippet\target\debug\deps' -L 'dependency=c:\build\snippet\target\debug\deps' --cap-lints allow`
   Compiling snippet v0.1.0 (file:///C:/build/snippet)
     Running `c:/build/sccache/target/debug/sccache.exe rustc --crate-name snippet 'src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=d4598b05811c20ca -C extra-filename=-d4598b05811c20ca --out-dir 'c:\build\snippet\target\debug\deps' -C 'incremental=c:\build\snippet\target\debug\incremental' -L 'dependency=c:\build\snippet\target\debug\deps' --extern 'itoa=c:\build\snippet\target\debug\deps\libitoa-8fdbbc2ecc32a839.rlib'`
    Finished dev [unoptimized + debuginfo] target(s) in 2.23s
```

What revision of Firefox are you attempting to build? I can try that as well.

**Comment by buttercookie42** [comment]
I can't remember because I've since rebased at least once or twice, but I've updated my local sccache to the current master (i.e. still dda88a6) and then tried building sccache itself using sccache. Rustc version is the same as yours.

The error message this time is very slightly more informative:
> error: could not exec the linker `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64\link.exe`
>   |
>   = note: Das Handle ist ungültig. (os error 6)
>   = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib""d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build0.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build1.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build10.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build11.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build12.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build13.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build14.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build15.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build2.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build3.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build4.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build5.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build6.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build7.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build8.rcgu.o" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.build_script_build9.rcgu.o" "/OUT:d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.exe" "d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\build\\winapi-3fe2515386a43ab3\\build_script_build-3fe2515386a43ab3.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:d:\\Users\\Jan\\.mozbuild\\sccache\\target\\debug\\deps""/LIBPATH:D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-a2acd5f5dca269de.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-af367b4bf1f63fec.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-a1c17caf251336a7.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-88975955845d914b.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-3bfe42d2b50eccc6.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-7c8c2618a28cd3f2.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-bb4237926b8207c3.rlib" "D:\\Users\\Jan\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-19c7c2c4d55ff072.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
> 
> error: aborting due to previous error
> 
> error: Could not compile `winapi`.

**Comment by buttercookie42** [comment]
I'm not sure if it was upgrading to sccache 0.2.8 or simply a more recent mozilla-central (possibly using a newer version of winapi?) that fixed it, but in any case at the moment it's now working for me.
