### ISSUE TITLE
try_read_config_file should return a Result

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#295]
@mystor was trying out sccache-dist and was getting "sccache: Could not load config" running `sccache-dist auth generate-jwt-hs256-server-token`.  Unfortunately right now we don't propagate errors up from `try_read_config_file` so it's not readily apparently why it's failing (I suggested using `RUST_LOG=debug` as a workaround to get the info from [the log statements there](https://github.com/mozilla/sccache/blob/dda88a658c0f48994527c201e15f736ad193da4f/src/config.rs#L244).) Propagating errors up would let us display a more useful error message.

/cc @aidanhs

**Comment by mystor** [comment]
With the logging I realized that I was missing configuration keys, which would have been easier to discover with error logging :-)

**Comment by sylvestre** [comment]
it is now fixed
https://github.com/mozilla/sccache/blob/762b165a227ea086fa63de35dd953cc628ecdb3f/src/config.rs#L535
