### ISSUE TITLE
Cache `rustc --emit=metadata`?

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#301]
We currently cache Rust compiles with `--emit` values containing only `link` or `dep-info` since most of the other possible values have niche uses:
https://github.com/mozilla/sccache/blob/dda88a658c0f48994527c201e15f736ad193da4f/src/compiler/rust.rs#L135-L138

However, running `cargo check` nowadays will use `--emit=metadata` which we could reasonably cache, and is something that has widespread usage. I've seen recommendations for setting up CI for Rust projects to do `cargo check && cargo test`. It might be worth caching this type of compile if it provides a speedup. @alexcrichton: what do you think?

**Comment by Marwes** [comment]
Hah, I were just looking over some build timings and one of the most time consuming parts is using `cargo clippy` (which uses `cargo check` I think) since it needs to download and check all our dependencies (which isn't necessary for the test and release builds thanks to sccache).

**Comment by luser** [comment]
I believe supporting this is just a matter of adding "metadata" to that list and changing this conditional to also allow "metadata":
https://github.com/mozilla/sccache/blob/dda88a658c0f48994527c201e15f736ad193da4f/src/compiler/rust.rs#L749-L753

We already ask rustc to provide the list of output filenames, so everything else might just work. Adding a test that runs `cargo check` to the existing cargo tests would be good as well:
https://github.com/mozilla/sccache/blob/master/tests/sccache_cargo.rs

**Comment by Marwes** [comment]
I will try and take a look.

**Comment by Marwes** [comment]
Looked into it a bit and it seems like says that it emits a `.rlib` file whereas it actually emits a `.rmeta` file. Not 100% sure though since it is a bit difficult to get decent logs out of the cargo test.

**Comment by alexcrichton** [comment]
Sounds reasonable to me to cache metadata output! Given the speed of `cargo check` I think this'd best be coupled with https://github.com/mozilla/sccache/issues/31 to ensure that `sccache` doesn't accidentally slow down the build, but this'd definitely speed up larger crates

**Comment by Marwes** [comment]
Extracted from the cargo test:

```
rustc "--crate-name" "itoa" "/home/markus/.cargo/registry/src/github.com-1ecc6299db9ec823/itoa-0.3.4/src/lib.rs" "--crate-type" "rlib" "--emit" "dep-info,metadata" "-C" "debuginfo=2" "-C" "metadata=8beed17c1534836d" "-C" "extra-filename=-8beed17c1534836d" "--out-dir" "/tmp/sccache_test_rust_cargo.spn3UYAuDcXX/cargo/debug/deps" "-L" "dependency=/tmp/sccache_test_rust_cargo.spn3UYAuDcXX/cargo/debug/deps" "--cap-lints" "allow" "--print" "file-names"

libitoa-8beed17c1534836d.rlib
```

`rustc --print-files` emits that it outputs and `.rlib` whereas the only thing that ends up in `target/debug/deps` is `.d` and `.rmeta` files.

**Comment by luser** [comment]
Weird. I guess detecting that and doing s/rlib/rmeta/ when emit==metadata is not the worst thing, though.
