### ISSUE TITLE
supporting different languages

### ISSUE THREAD

**Issue by cipher1024** [mozilla/sccache#305]
I'd like to sccache to build a project built with the Lean theorem prover. How can I adapt sccache so that I can specify which compiler to use?

**Comment by luser** [comment]
Hi! sccache works like ccache in that you simply place it in front of your compile commandline, like `sccache gcc -c file.c -o file.o`. sccache will attempt to detect what type of compiler is being used the first time it encounters a particular compiler binary:
https://github.com/mozilla/sccache/blob/3d9f934ae94759e6aef4b3c02bf0779df4fe2cc6/src/compiler/compiler.rs#L660-L716

And then each type of compiler implements a few traits to specify how to parse its commandline, hash its inputs, etc:
https://github.com/mozilla/sccache/blob/3d9f934ae94759e6aef4b3c02bf0779df4fe2cc6/src/compiler/compiler.rs#L90-L104
https://github.com/mozilla/sccache/blob/3d9f934ae94759e6aef4b3c02bf0779df4fe2cc6/src/compiler/compiler.rs#L110-L315

You'd need to add code to detect Lean as a compiler, and implement those traits similar to what we do for [C compilers](https://github.com/mozilla/sccache/blob/master/src/compiler/c.rs) and [the Rust compiler](https://github.com/mozilla/sccache/blob/master/src/compiler/rust.rs).

**Comment by luser** [comment]
Each implementation of the trait is responsible for handling compiler-specific behavior. There's a generic C compiler implementation that forwards to specific implementations for gcc/clang/msvc, and there's a Rust implementation.

It's hard to say specifically, but I've leaned towards accepting patches for additional functionality as long as it fits into the existing codebase in a reasonable manner. We have several cache storage backends that were contributed, we only use the S3 backend at Mozilla.

**Comment by cipher1024** [comment]
Update: I'm making progress on writing my patch and learning Rust. Right now, I'm a bit stuck on trying to test my implementation because I'd like to try it with a creator that actually spawns processes. If I understand correctly, the following is only a mock up:

```rust
        let creator = new_creator();
        next_command(&creator, Ok(MockChild::new(exit_status(0), "foo\nbar\ngcc", "")));
```

and it will output `"foo\nbar\ngcc"` the first time a process is created. I also tried the following to get a creator:

```rust
        let mut core = Core::new().unwrap();
        let jobserver = unsafe { Client::new() };
        let creator = <ProcessCommandCreator as CommandCreatorSync>::new(&core.handle(), &jobserver);
```

but I get the following error:

```
thread 'compiler::compiler::test::test_lean_scratch' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("failed to spawn \"echo\" \"--deps\" \"data/list/basic.lean\""), State { next_error: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" }), backtrace: InternalBacktrace })', libcore/result.rs:945:5
```

What should I do?

**Comment by luser** [comment]
Cool! If you want to write tests that invoke actual processes I don't think you want to use the `MockCommand` stuff at all. You'd probably be better served writing a test in the style of the existing system tests:
https://github.com/mozilla/sccache/blob/master/tests/system.rs

Most of the other tests are unit tests that mock out process execution to make things simpler, but the system tests invoke real compilers and check that the right things happen.

**Comment by cipher1024** [comment]
Nice! Thanks! If I add a test case in there, do you recommend I add a line in `.travis.yml` to make sure Lean is present when running the test suite? Anything else I should do to test against Lean?
