### ISSUE TITLE
Add a bubblewrap version check in dist server startup

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#316]
cc @aidanhs 

We need bubblewrap 0.3.0 or newer for its commandline handling. Ubuntu 18.04 ships 0.2.1, and using that produces a confusing error about `--` being an unsupported option. We should just version-check the supplied binary on startup and error if it's not new enough. `bwrap --version` works:
```
$ bwrap --version
bubblewrap 0.2.1
$ /build/bubblewrap-0.3.1/bwrap --version
bubblewrap 0.3.1
```

**Comment by ncalexan** [comment]
Yeah, I just ran into this yesterday -- and I figured it was the version.  So thanks for confirming!
