### ISSUE TITLE
Increase server startup timeout

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#317]
We have [an extremely low-frequency intermittent failure](https://bugzilla.mozilla.org/show_bug.cgi?id=1442211) where we hit the server startup timeout in Firefox CI. We should just increase the timeout from 5s to 10s. The server already sends back a status message when it starts successfully, so this shouldn't make things work in the normal case, but it gives us a little extra breathing room.

**Comment by glandium** [comment]
What makes you think that it won't only delay the inevitable? That is, that it will happen at the same frequency, but take 10 seconds instead of 5? Because really, I see no reason why it would more than 5 seconds to start in any case.

**Comment by luser** [comment]
It's a fair question. I'm assuming that this is happening in situations where the machine is overloaded, but our build instances are pretty powerful nowadays so that does seem fairly unlikely.

**Comment by luser** [comment]
...actually now that I look more closely we have sccache.log from the most recent failure and it shows an error message:
```
DEBUG:sccache::cache::cache: Trying S3Cache(taskcluster-level-3-sccache-us-east-1.s3.amazonaws.com)
DEBUG:sccache::server: notify_server_startup(success: true)
error: No such file or directory (os error 2)
```
