### ISSUE TITLE
Document how a distributed Rust toolchain should look

### ISSUE THREAD

**Issue by ncalexan** [mozilla/sccache#320]
Right now, I'm distributing C and C++ from my macOS client to my Linux64 build farm (consisting of one rather mangy build cow, named 🐄).  I'd like to distribute the Rust bits too, of course.  This ticket tracks documenting the format for doing the equivalent of `icecc-create-env`.

A great first step would be posting a tarball produced on Linux64 for dissection.

/cc @aidanhs

**Comment by luser** [comment]
The sccache client has a `--package-toolchain` option when built with the `dist-client` feature that should do the right thing.

**Comment by luser** [comment]
I merged my [distributed quick start guide](https://github.com/mozilla/sccache/blob/master/docs/DistributedQuickstart.md), I'd love to improve it to include setting up a cross-compile on Mac/Windows as well.

**Comment by chmanchester** [comment]
We're providing dist toolchains from automation now, and I added a few more notes about macOS in 42ebb0b8008feb6f94dc0a9e41213fa4c7dc5ade.
