### ISSUE TITLE
Add distributed compile stats

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#322]
We don't currently report any info on distributed compiles in the stats output. I don't know what would be useful here, but at least "number of compiles that were distributed" seems like it would be useful.

**Comment by aidanhs** [comment]
This does exist since the tests needed to assert on it - https://github.com/mozilla/sccache/blob/d175720/tests/dist.rs#L86-L87

**Comment by luser** [comment]
Fixed by https://github.com/mozilla/sccache/pull/334 .
