### ISSUE TITLE
Sort the "Non-cacheable reasons" lines in the stats output

### ISSUE THREAD

**Issue by xTibor** [mozilla/sccache#324]
When I'm monitoring the stats output of sccache with `watch sccache -s` the "Non-cacheable reasons" lines in the output are displayed in a random order, they jump around the place which is rather distracting. It would be nice if this list would be sorted for example by the count column.

**Comment by luser** [comment]
Yes, we should definitely fix this! The code that prints those lines is here:
https://github.com/mozilla/sccache/blob/06b999976d71a44eec94863acd326aa03783c495/src/server.rs#L871-L878

It would just be a mater of collecting them into a `Vec` and sorting that before printing.
