### ISSUE TITLE
Starting the sccache server times out (macOS)

### ISSUE THREAD

**Issue by staktrace** [mozilla/sccache#328]
We're seeing intermittent failures in webrender CI (on macOS) when running `sccache --start-server` where it times out waiting for the server to start. Running with debug-level logging produces no output.

Examples:
https://tools.taskcluster.net/groups/Jj5DaOYWSqyTL8bLQExG5w/tasks/JdK9W5pmRyG1BHDhcqQT_Q/runs/0/logs/public%2Flogs%2Flive_backing.log
https://tools.taskcluster.net/groups/MjouIXsqQnis4oB4j_ZT7w/tasks/SwXIbSLjTKmgxILexweMEw/runs/0/logs/public%2Flogs%2Flive_backing.log
https://tools.taskcluster.net/groups/U5zac0SGR52bWG7iwnX2eQ/tasks/JEMZN29rTq-qUM-XmLywOw/runs/0/logs/public%2Flogs%2Flive_backing.log

**Comment by luser** [comment]
Two things:
1. What version of sccache are you running on your workers?
2. You can try bumping the log level up to trace for now to see if that gives us any more info. That should at least let us verify that the server process is doing *something*.

**Comment by staktrace** [comment]
The `wr-207-254-40-58` worker is running `sccache 0.2.6`. Not sure what the other one is using (it's powered off at the moment due to a scheduled power outage in the Toronto office).

I'll bump the log level and see what happens.

**Comment by jwatt** [comment]
@staktrace Any follow-up here?

**Comment by staktrace** [comment]
At least one of the sccache problems was diagnosed to be the idle timeout kicking in, and the patch at https://github.com/servo/webrender/pull/3403/commits/1c921c424572ba37bf279c7760ba85d9b93c1ec4 was a potential fix. There was another problem too that was never diagnosed and we ended up disabling sccache. But if you're running into this problem you can try setting SCCACHE_IDLE_TIMEOUT=0 as per the patch above and see if that helps.

**Comment by Xuanwo** [comment]
The history of this issue has been very long, and there have been many changes in the code of sccache. I will close this issue, please create a new issue if this problem still exists.
