### ISSUE TITLE
Save stats to disk

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#33]
Currently the stats are only saved in-memory, so when the server shuts down they're lost. We should save them to disk like the Python sccache did. This is mostly useful for local developers, where they might expect the stats to be persistent like ccache's stats. If we do this we should also add a `--zero-stats` option to match ccache.

**Comment by elichai** [comment]
now that there's `--zero-stats` option, what about persistant stats? it's really helpful to know cache hits/misses over time. Thanks!

**Comment by poopsicles** [comment]
just wondering about this issue, it's bee bothering me for a while
#612 went inactive, but maybe saving it in the config location as maybe `sccache-stats.toml` would suffice?

**Comment by mathstuf** [comment]
Like in https://github.com/mozilla/sccache/issues/1033#issuecomment-1953163097, can a label be used to distinguish these auto-closed inactive issues from actually resolved problems?
