### ISSUE TITLE
rust-crypto

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#330]
`rust-crypto` is unmaintained for ~2 years now. The dependencies are ageing and are unmaintained too (i.e. `gcc` crate, which got renamed to `cc` and which received a ton of fixes for its `build.rs`) and pulling in libraries with known issues (`openssl` <= 1.1.0).

Are there any plans to obsolete the usage of `rust-crypto`?

**Comment by luser** [comment]
We're really just using it for hmac and hashing. There's https://github.com/mozilla/sccache/pull/310 which wants to replace both ring and rust-crypto with RustCrypto. I'm going to look more closely at that once I get the last few large PRs merged for the distributed compilation feature that we've been adding.

**Comment by newpavlov** [comment]
IIUC `sccache` no longer depends on `rust-crypto`, so I think this issue can be closed.

**Comment by Xuanwo** [comment]
> IIUC `sccache` no longer depends on `rust-crypto`, so I think this issue can be closed.

cc @sylvestre to close this issue. BTW, I'm willing to help triage and close stale issues~

**Comment by sylvestre** [comment]
> cc @sylvestre to close this issue. BTW, I'm willing to help triage and close stale issues~

This requires some extra perms from the Mozilla org. (Almost) everybody is off. Let's see next year :)
