### ISSUE TITLE
Intermittent hang in Firefox CI

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#335]
While trying to update the version of sccache in use in Firefox CI to fix [an issue with clang-cl](https://bugzilla.mozilla.org/show_bug.cgi?id=1476604) we ran into a situation where builds in CI would [intermittently hang](https://bugzilla.mozilla.org/show_bug.cgi?id=1507781). @mshal bisected this down to 5481e8736a6712a42d29382d8f858cee9e03dddc (you can see [the failures on try](https://treeherder.mozilla.org/#/jobs?repo=try&revision=dc27d5cf5604e226238079e5c744faf0ebfa4036)) which points at the `tokio-process` update from #286.

If it works the simplest fix for now would be to revert to `tokio-process` 0.1, but it'd be good to figure out the root cause here. The failures manifest as a build hang. From reading the sccache logs it looks like in every case we start a local compile but never see it finish.

/cc @Marwes @alexcrichton

**Comment by Marwes** [comment]
I'd guess this is just another instance of https://github.com/alexcrichton/tokio-process/issues/42 which also causes https://github.com/mozilla/sccache/issues/248. Updating `tokio-process` to the most recent patch should thus fix it (which is done in https://github.com/mozilla/sccache/pull/304 as well).

**Comment by luser** [comment]
Fixed by merging https://github.com/mozilla/sccache/pull/304 . Thanks!
