### ISSUE TITLE
Support `ar` "compiler" to allow static libraries

### ISSUE THREAD

**Issue by vidstige** [mozilla/sccache#339]
Linking with `ar` causes the following error.

```
error: failed to execute compile
caused by: Compiler not supported
```

It's very easy to reproduce by the following
```bash
echo "int foo() { return 67; }" > a.c
sccache gcc -c a.c
sccache ar rcsU libfoobar.a *.o
```

I see lots of PRs up so I suspect this project is not maintained any longer, otherwise I would have probably proposed a PR for this.

**Comment by luser** [comment]
First off: yes, sccache is still under active development. We do have a PR backlog, I'm hoping to clear some of that out this week (and some of them should probably just be closed).

This is an interesting idea and we could probably support it. I'm not sure if it's worthwhile though--does ar take a measurable amount of time to do its work? There's always overhead involved in caching. I don't think I've seen a build system invoke a compiler wrapper around ar before.

**Comment by vidstige** [comment]
Thanks for super quick answer @luser ! When I see a project with both old and new PRs up it just gives that impression. Thanks for clarifying!

`ar` does normally not take very long time, however it might take substantial amount of time. There is even something called "thin" archive that avoids copying file content and just archives relative paths to object files.

Anyway, regardless of it saving or not saving time, it would be nice if `sccache` didn't bail out completely. For example I'm considering switching to `sccache` over `ccache` for a massive C++ project. It's built with cmake and we're currently using the [`RULE_LAUNCH_LINK`](https://cmake.org/cmake/help/v3.0/prop_tgt/RULE_LAUNCH_LINK.html) variable to prefix all link commands with `ccache`. This does not work with `sccache` as it bails out. I've worked around it now by not using any cache at all for linking. Compiling saves the most time anyway. So one "fix" could be that there is a "pass through list" so that `sccache` would not bail out on `ar` (but it _would_ bail out on, e.g. "random_command") nor use any cache, but simply run the command. Is that reasonable and/or feasible?

**Comment by luser** [comment]
I'd have to think about that for a bit. Does ccache support linking at all? I was under the impression that it didn't. sccache does not attempt to cache linking. It might not error, but it will certainly not do anything useful.

**Comment by vidstige** [comment]
I'm not sure. It might be it does not do anything. In that case we can just close this. :-) Just thought I'd add it to make it easier to switch from `ccache` if needed. At least people should be able to google now.  Thanks or your input.

**Comment by spease** [comment]
I suspect I'm running into this error with a project using cmake. Is there an easy way to explicitly exclude ar from getting called with sccache? I can't compile the project even if I just `cargo install sccache` and don't set any environment variables.
