### ISSUE TITLE
Add support for clang plugin parameters

### ISSUE THREAD

**Issue by hferreiro** [mozilla/sccache#350]
Support for clang plugins was handled in #332 but, support for `-plugin-arg-<plugin-name>` is missing. An example invocation from a chromium build is the following:

```
-Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc
```

**Comment by luser** [comment]
This should be easy enough to support, we should just need to add it to the list of supported clang arguments:
https://github.com/mozilla/sccache/blob/12008f60bc8b5335e8e8fa878e3bdc2749e50756/src/compiler/clang.rs#L88

cc @chmanchester

**Comment by barrbrain** [comment]
For chromium clang, there are currently just 2 plugins for which arguments are passed in the build configuration:
1. `-plugin-arg-find-bad-constructs` at [build/config/clang/BUILD.gn:23](https://chromium.googlesource.com/chromium/src/+/master/build/config/clang/BUILD.gn#23)
2. `-plugin-arg-blink-gc-plugin` at [third_party/blink/renderer/BUILD.gn:123](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/BUILD.gn#123)

Adding rules for these is sufficient to have a fully cacheable build when setting `clang_use_chrome_plugins = true`.
