### ISSUE TITLE
More granular bucketing?

### ISSUE THREAD

**Issue by ccotter** [mozilla/sccache#354]
As far as I understand, nearly every configuration (SCCACHE_BUCKET, etc) is specified when the server is brought up and subsequently fixed. In build environments where multiple users build different projects on the same machine (which could be Jenkins environments or developers building different projects on the same machine), we'd need to run one sccache server per project/user or whatever the granularity is that we are bucketing.

To make managing this easier, it would simplify things if the S3 bucket could be specified by the sccache client. Since all environment variables are already sent to the server, we could accomplish this by having the sccache server read `SCCACHE_BUCKET` (or a new variable to not confuse the meaning of `SCCACHE_BUCKET`) in the list of environment variables sent over from the client and use this when talking to the s3 server.

Any thoughts on this idea?

**Comment by luser** [comment]
Is there a particular reason you need to use multiple buckets in this case? Cache entries in the bucket are stored under keys which are a SHA-512 of various compile inputs so there's no real risk of cache entries from multiple projects conflicting. sccache wasn't really designed with multiple independent users connecting to a single server in mind, the server process is really just an optimization to keep HTTP connection pools alive and some other things cached in memory.

**Comment by Xuanwo** [comment]
Hi @ccotter, are there other blocks that prevent we using the same bucket? As @luser said, it's OK and no risk that always using the same sccache across different projects.
