### ISSUE TITLE
Add checksums to releases

### ISSUE THREAD

**Issue by Jake-Shadle** [mozilla/sccache#369]
Currently, there are no checksums associated with a platform's release tarball so that installers can validate them, eg. scoop.

Usually, this is done with something like `${project}_${version}_checksums.txt`, but this might be annoying for sccache because it isn't cross-compiled, so maybe just doing a simple ${tarball_name}.sha/256 would allow easy validation without complicating the release process too much.

https://github.com/gohugoio/hugo/releases is a good example.

**Comment by luser** [comment]
This should be straightforward enough to do. The Linux/Mac releases get built on Travis and packaged in the `before_deploy` step:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/.travis.yml#L43-L48
Any additional files uploaded probably need to be mentioned in the `deploy.file` key:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/.travis.yml#L54

The Windows release gets built on AppVeyor and packaged in the `before_deploy` step there:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/appveyor.yml#L55-L64
There's similarly a `deploy.artifact` key that likely needs updated:
https://github.com/mozilla/sccache/blob/05bd9c7944d8c7c6e11f994c8cb5246f7638d887/appveyor.yml#L67
