### ISSUE TITLE
test::system::test_sccache_command fails

### ISSUE THREAD

**Issue by glandium** [mozilla/sccache#37]
```
	thread 'test::system::test_sccache_command' panicked at 'Error: sccache binary not found at `"/home/glandium/sccache/target/debug/deps/sccache". Do you need to run `cargo build`?', src/test/system.rs:197
```

Interestingly, there is no `sccache` executable in that directory, only `sccache-somehash`, so the assumption in system.rs doesn't work on my system (using rust/cargo Debian packages).

**Comment by luser** [comment]
This is the same failure we're seeing on builds with nightly Rust in Travis:
https://travis-ci.org/mozilla/sccache/jobs/180115158

I think cargo changed the location of the test- binaries in a newer version. On my machine, using rustc 1.12 and cargo 0.13, I have:
```
luser@eye7:/build/sccache2$ ls target/debug/
build  deps  examples  native  sccache  sccache-68561a6f40d373d7
```

And `deps` just contains rlibs. I noticed this while hacking on another Rust crate that was using a separate binary in its tests, but with that crate I was using nightly Rust. I guess we can just fix the test here to look in both places.

**Comment by luser** [comment]
I tested locally with nightly Rust+cargo and that commit fixes it (and still works with stable Rust+cargo).

**Comment by glandium** [comment]
Still doesn't work for me:
```
	thread 'test::system::test_sccache_command' panicked at 'Error: sccache binary not found, looked in `["/home/glandium/sccache/target/debug/deps", "/home/glandium/sccache/target/debug"]`. Do you need to run `cargo build`?', src/libcore/option.rs:705
```

As I said, there is no `sccache` executable. Only `sccache-somehash`. Rustc 1.13, cargo 0.15.

**Comment by luser** [comment]
Are you running `cargo build` before you run `cargo test`? cargo apparently only builds the tests when you run `cargo test`, and I don't know that there's any way to tell it "I need this binary for the tests to work".
