### ISSUE TITLE
Add more detailed explanations for uncacheable flags

### ISSUE THREAD

**Issue by Jake-Shadle** [mozilla/sccache#379]
While it's great that uncacheable flags have a high level "TooHard/Flag" attached to them, it would be really helpful to have a link to an issue for each one that explains why, as right now it's kind of disappointing to hit on an uncacheable compiler call, but not really have a detailed reason for why the flag is "hard". I opened #378 because it was apparent from the code why it was considered hard, but other ones aren't as clear immediately.

**Comment by luser** [comment]
Not a bad idea. I guess we could re-enable the project wiki here and make a page with sections describing why we don't handle particular flags or scenarios and then print links to the proper section in the stats output. Currently the non-cacheable reasons are just stored as `HashMap<String, usize>`:
https://github.com/mozilla/sccache/blob/12008f60bc8b5335e8e8fa878e3bdc2749e50756/src/server.rs#L1038

so we'd need to change that to have a place to store the URLs. Printing them in the `--show-stats` output would be straightforward:
https://github.com/mozilla/sccache/blob/12008f60bc8b5335e8e8fa878e3bdc2749e50756/src/server.rs#L1198

**Comment by Jake-Shadle** [comment]
That sounds even better than what I was thinking. 😄

**Comment by TriplEight** [comment]
That would be very helpful.
