### ISSUE TITLE
Add tests for S3 storage using minio

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#38]
We don't currently have any automated tests for S3 storage, because we currently hardcode the AWS endpoint URL and I didn't feel like writing tests that ran against a live S3 bucket. Someone recently pointed out [minio](https://github.com/minio/minio) as a useful mock S3 implementation. Once we get https://github.com/mozilla/sccache/pull/27 landed we should be able to write some tests that run against a local minio instance.

I don't know if there's a convention for Rust tests that require additional programs--it'd be great to be able to skip the tests if minio is not available.

**Comment by Riebart** [comment]
moto can also act as a [generic AWS endpoint](https://github.com/spulec/moto#stand-alone-server-mode) for mocking and testing. Minio is less suited for S3 testing as it supports only a strict subset of the AWS S3 API operations.

**Comment by Xuanwo** [comment]
@sylvestre Please assign this issue to me. I plan to implement s3 test under our new integration tests framework by minio.
