### ISSUE TITLE
data migration between storages

### ISSUE THREAD

**Issue by wicast** [mozilla/sccache#395]
It will be nice to have a migration command.

Suppose I was using a laptop with a redis setup in LAN. When I left this LAN environment, I have to recreate all the cache I've used in redis on local storage.Also, this can be a method for sharing pre-build libs with friends.

**Comment by luser** [comment]
sccache is actually ignorant of the full contents of cache storage, it just treats the cache as a key/value store. This would be pretty hard to implement in sccache, I'm not sure it would be valuable enough.

**Comment by wicast** [comment]
I haven't read the code yet, is there any key iteration method over a store?

**Comment by flxo** [comment]
@wicast No. This isn't required. 

https://github.com/mozilla/sccache/blob/7a201b1aee6fbf48c3b55bfcd5d03fd91c871a7f/src/cache/cache.rs#L140-L164

**Comment by Xuanwo** [comment]
I believe this issue is not in sccache's scope. @sylvestre, Let's close with wontfix.

**Comment by sylvestre** [comment]
agreed
