### ISSUE TITLE
Get only cache misses

### ISSUE THREAD

**Issue by siscia** [mozilla/sccache#396]
Hi,

I am trying to use sccache, but I am keeping getting only Cache Misses.

```
# sccache -s
Compile requests                        243
Compile requests executed               170
Cache hits                                0
Cache misses                            164
Cache timeouts                            0
Cache read errors                         0
Forced recaches                           0
Cache write errors                        0
Compilation failures                      1
Cache errors                              1
Non-cacheable compilations                0
Non-cacheable calls                      73
Non-compilation calls                     0
Unsupported compiler calls                0
Successful distributed compilations       0
Failed distributed compilations           0
Average cache write                   0.019 s
Average cache read miss               1.840 s
Average cache read hit                0.000 s

Non-cacheable reasons:
crate-type                               61
-                                        12
```

Is that normal/ok?

The project I am building this project: https://github.com/RedBeardLab/rediSQL

It is a `cdylib` project, does it change anything?

**Comment by jwatt** [comment]
I don't know much about sccache, but you probably should mention what platform you're building on. For example, I noticed that there's a known issue (#169) on macOS.

**Comment by siscia** [comment]
Thanks! Well Linux for x86_64

The "standard".

**Comment by JeanMertz** [comment]
I've seen the same happening. `cdylib` project (specifically, building for the wasm target). macOS.

**Comment by Xuanwo** [comment]
> It is a `cdylib` project, does it change anything?

It's a known problem that sccache doesn't work well with `cdylib` deps. Visit our docs for more information: https://github.com/mozilla/sccache/blob/main/docs/Rust.md

We are working on solution to fix this.
