### ISSUE TITLE
sccache client on macOS failing to distribute compilation

### ISSUE THREAD

**Issue by jwatt** [mozilla/sccache#406]
I'm having problems getting sccache on my Mac to distribute compilation to my Linux workstation.

Given both machines are on my home network, I have the scheduler set up to use simple HTTP (not HTTPS), and the client and scheduler appear to be communicating fine. Specifically my client config file basically contains:

```
[dist]
scheduler_url = "http://my-workstation.localdomain:10600"
toolchain_cache_size = 1073741824

[[dist.toolchains]]
type = "path_override"
compiler_executable = "/usr/local/opt/llvm/bin/clang++"
archive = "/Users/me/toolchains/clang-8.0.0-x86_64.tar.gz"
#archive = "/Users/me/toolchains/clang.tar.xz"
archive_compiler_executable = "/clang-8.0.0-x86_64/bin/clang++"

[dist.auth]
type = "token"
# This should match the `client_auth` section of the scheduler config.
token = "my client token"
```

Running the client sccache server on my Mac via:

```
RUST_LOG=trace SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache
```

I see very little of use in the log output from sccache/reqwest/hyper etc. to help debug why toolchain upload to the workstation machine isn't working. The only bit of useful output is:

WARN 2019-04-04T04:37:29Z: sccache::compiler::compiler: [conftest.E2EDOm.o]: Could not perform distributed compile, falling back to local: Could not submit toolchain: Could not submit toolchain: `https://<build-server-ip-address>:10501/api/v1/distserver/submit_toolchain/5`: connection closed

I tried digging into the code using a debugger but there are a lot of layers of async indirection through the various modules which made that non-trivial and time consuming. It appears that the connection is already closed on the tx object before the body is even dispatched though, which is weird.

Another thing I discovered is that if I changed the sccache client code to dispatch a string instead of the toolchain file by changing [this line](https://github.com/mozilla/sccache/blob/9b04c5857bc9/src/dist/http.rs#L1185), then the log message changes from "connection closed" to "The certificate was not trusted":

WARN 2019-04-04T04:04:55Z: sccache::compiler::compiler: [conftest.Ius_Ek.o]: Could not perform distributed compile, falling back to local: Could not submit toolchain: Could not submit toolchain: `https://<build-server-ip-address>/api/v1/distserver/submit_toolchain/65`: an error occurred trying to connect: The certificate was not trusted.: The certificate was not trusted.

I haven't looked into the code for passing the certificate generated by the build server from the scheduler to the client, but it looks like that isn't working for me.

**Comment by chmanchester** [comment]
I was able to reproduce this error (in addition to a failure to package the rust toolchain) when trying out a setup in an office using https as well.

**Comment by jwatt** [comment]
Thanks for looking into this!

**Comment by chmanchester** [comment]
I looked into this a little more this afternoon and found that even when "connection closed" is printed there's an underlying error that gets buried in hyper that states ""The certificate was not trusted."

**Comment by jwatt** [comment]
Yeah, see the paragraph above starting "Another thing I discovered...". I didn't figure out why switching from a file to a string allowed that error to surface though, or why it was happening.

**Comment by chmanchester** [comment]
This is using the `add_root_certificate` functionality in `reqwest` (implemented in https://github.com/seanmonstar/reqwest/pull/124) to make clients aware of the certs that should be used to connect to build servers -- @seanmonstar, do you happen to know if this is known to work for self-signed certs on macOS?

**Comment by seanmonstar** [comment]
I don't have a macOS device, so I can't verify myself. It uses [native-tls](http://crates.io/crates/native-tls) to provide the functionality, which my understanding is it should work on Windows, macOS, and Linux.

**Comment by chmanchester** [comment]
Ok, thanks. native-tls uses something similar for tests that work fine on macOS so that all looks sensible. I verified the server is doing a fine job of passing its cert along to the client, so it seems like there's something about how we're generating it the macOS tls backend wont accept...

**Comment by chmanchester** [comment]
I noticed the subject and issuer were blank on the provided cert, setting those gets me far enough to be able to distribute a "hello world" compilation, but I'm still hitting issues trying to build firefox so wont call this done just yet.
