### ISSUE TITLE
handle /clang arguments for clang-cl

### ISSUE THREAD

**Issue by froydnj** [mozilla/sccache#408]
clang 8.0 introduced a better "escape hatch" for `clang-cl` than `-Xclang`: `/clang:ARG`.  The former passes the argument directly to `cc1`; the latter passes the argument to the clang driver itself, essentially allowing anything to be passed through as if you were using `clang` instead of `clang-cl`.

I think this is just a matter of adding a `SlashClang` case to `ArgData` and adding similar reprocessing of `SlashClang` arguments as the `XClang` case already does.  But it'd be nice to not completely duplicate the `XClang` processing code.

**Comment by glandium** [comment]
There is partial support in #808

**Comment by froydnj** [comment]
This is done, then.
