### ISSUE TITLE
MSVC: SCCACHE not printing included headers with /showIncludes and ninja can't detect changes

### ISSUE THREAD

**Issue by dpar39** [mozilla/sccache#411]
If I call `cl.exe -showIncludes ... /Fo$out /c $in` it correctly prints the list of include files to `stdout`. If I call `sccache cl.exe -showIncludes ... -c /Fo$out /c $in` only the name of the output object is printed to stdout.
Ninja relies on the list of include headers to figure out dependency builds.
I can reproduce the problem on 0.2.8 and master local build. I've tried both /showIncludes and -showIncludes, it doesn't make a difference.
If the compiler command has some error (e.g. a path to file doesn't exists), then the list of includes is correctly printed on the console.

**Comment by piscisaureus** [comment]
I'm running into this as well. It appears that when sccache invokes the compiler after a cache miss, the `/showIncludes` flag is dropped.

I did the following test:

### First run (expecting a sccache cache miss):

I run:
  1. `sccache cl /showIncludes /c bar.cc`

sccache invokes:
  1. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"" -E C:\Users\BERTBE~1\AppData\Local\Temp\sccache.ddMykFjaAGPF\testfile.c`
  2. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"" -nologo -showIncludes -c -Fonul -I. C:\Users\BERTBE~1\AppData\Local\Temp\sccache.tfHJK22noDJy\test.c`
  3. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"" -E bar.cc -nologo -showIncludes`
  4. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"" -c bar.cc -Fobar.obj`

Note how step **4**, which is where it actually compiles the file, the `/showIncludes` flag is missing.

### Second run (expecting a sccache cache hit):

I run:
  1. `sccache cl /showIncludes /c bar.cc`

sccache invokes:
  1. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"" -E bar.cc -nologo -showIncludes`

**Comment by auric** [comment]
Hi
@piscisaureus @mathstuf 
Are there any news about when it's going to be merged?

**Comment by mathstuf** [comment]
I believe it is waiting on review.
