### ISSUE TITLE
sccache cant start on windows10 20h1 build 18875

### ISSUE THREAD

**Issue by gettf** [mozilla/sccache#413]
sccache --start-server
**Starting sccache server...
error: Server startup failed: an attempt was made to access a socket in a way forbidden by its access permissions (os error 10013)**

sccache -s
**error: Connection to server timed out**

**Comment by aminya** [comment]
I was having this issue. I had installed sccache from chocolatey. Updating sccache using Cargo fixes the issue

```
cargo install sccache --git https://github.com/mozilla/sccache 
```
