### ISSUE TITLE
jwt/token auth conflicts with recommended server setup

### ISSUE THREAD

**Issue by chmanchester** [mozilla/sccache#416]
Per our docs:

> Securing communication with the scheduler is the responsibility of the sccache cluster administrator - it is recommended to put a webserver with a HTTPS certificate in front of the scheduler and instruct clients to configure their scheduler_url with the appropriate https:// address.

We've done this as a part of our setup for rolling out `sccache-dist` to offices, however I'm unable to use jwt for authentication with this setup. With the scheduler behind its own server incoming server traffic if seen by the scheduler as coming from localhost, so when the token is decoded the scheduler reads the contained IP, finds it isn't the same as what it's seeing as the origin of the request (`127.0.0.1`), and the heartbeat request is rejected. Unless I'm missing something here the issue is inherent to the intended design of the sccache-dist setup with jwt.

As a side note, I found jwt works fine with an entirely local setup (scheduler, server, and client on the same machine) -- something similar with the server's `public_addr` set to localhost will actually satisfy the token check on the remote scheduler, but this rather defeats the purpose of the check, and this IP is then used to try to allocate jobs which of course fails.

**Comment by chmanchester** [comment]
I didn't realize this initially, but the shared token setup performs a similar check of the server's IP, so a similar problem occurs.

**Comment by chmanchester** [comment]
Hi @luser, do you recall the motivation for running a separate https server in front of the scheduler vs. the scheduler itself running as https? rouille seems to support ssl, but we aren't taking advantage of that in the scheduler. Any more context you might have would be much appreciated. Thanks!

**Comment by luser** [comment]
I don't recall exactly. It might have been just that we expected that ops folks would want to have nginx as the externally-facing application? It would also involve writing some more code to allow configuring rouille with SSL. I don't actually know how the JWT code works, but would it be possible to [configure nginx to pass along the original client IP](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers), and have the scheduler use the IP from that header as the origin IP?
