### ISSUE TITLE
sccache-dist fails to compile rust from macOS client

### ISSUE THREAD

**Issue by chmanchester** [mozilla/sccache#425]
I'm trying to distribute rust compilations from my macOS but I'm seeing errors along the lines of:

 0:04.15    Compiling unicode-xid v0.1.0
 0:04.15      Running `CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_NAME=unicode-xid CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PRE= CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_REPOSITORY='https://github.com/unicode-rs/unicode-xid' CARGO_PKG_HOMEPAGE='https://github.com/unicode-rs/unicode-xid' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_DESCRIPTION='Determine whether characters have the XID_Start
 0:04.15 or XID_Continue properties according to
 0:04.15 Unicode Standard Annex #31.
 0:04.15 ' DYLD_FALLBACK_LIBRARY_PATH='/Users/chmanchester/m-c/obj-dbg/release/deps:/Users/chmanchester/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/chmanchester/lib:/usr/local/lib:/lib:/usr/lib' CARGO_MANIFEST_DIR=/Users/chmanchester/m-c/third_party/rust/unicode-xid CARGO=/Users/chmanchester/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo CARGO_PKG_AUTHORS='erick.tryzelaar <erick.tryzelaar@gmail.com>:kwantam <kwantam@gmail.com>' /Users/chmanchester/sccache/target/release/sccache /Users/chmanchester/.cargo/bin/rustc --crate-name unicode_xid /Users/chmanchester/m-c/third_party/rust/unicode-xid/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=2 -C codegen-units=1 --cfg 'feature="default"' -C metadata=cd67636ebc1e2662 -C extra-filename=-cd67636ebc1e2662 --out-dir /Users/chmanchester/m-c/obj-dbg/release/deps -C linker=/Users/chmanchester/m-c/build/cargo-linker -L dependency=/Users/chmanchester/m-c/obj-dbg/release/deps --cap-lints warn`
 0:05.32 error: couldn't create a temp dir: No such file or directory (os error 2) at path "/var/folders/hl/jl3cj_5j1_1fw660gwkq32tc0000gn/T/rustcbtasct"
 0:05.32 error: aborting due to previous error
 0:05.32 Compiler killed by signal 1
 0:05.36 error: Could not compile `unicode-xid`.

I've verified the toolchain distributed to the builder can build basic crates with `--target=x86_64-apple-darwin`, but I'm sort of out of ideas for how to debug futher. @alexcrichton, I know you might not have too much context on the distributed stuff, but does that error indicate a particular failure mode in cargo that rings a bell? Thanks for taking a look!

**Comment by luser** [comment]
Is this error happening from rustc on the remote builder? If so it might be that the `TMPDIR` env var is being sent across the wire and used there, but the macOS location doesn't exist on the Linux builder. There's trace-level logging in the build server that should let you verify that:
https://github.com/mozilla/sccache/blob/d17572040a8b338b496bb27c4ee520bc385ee3af/src/bin/sccache-dist/build.rs#L156

**Comment by chmanchester** [comment]
Oh, yeah, unsetting `TMPDIR` when the server goes to run the compile fixes this.

**Comment by jwatt** [comment]
Ah, nice suggestion! :)
