### ISSUE TITLE
Allow to run distributed server and client over HTTP

### ISSUE THREAD

**Issue by ncalexan** [mozilla/sccache#438]
Right now, the documentation strongly _recommends_ fronting distributed services with HTTPS but doesn't say that it is _required_.  However, there a few HTTPS schemes baked into the code: everywhere that produces a URL based on `server_id.addr()`, for example https://github.com/mozilla/sccache/blob/954897f9c933c7328f5289a38926ab7a6bbff3c2/src/dist/http.rs#L247

I wonder if addressing this will require moving to `server_id.url()`.  I think this happened for the scheduler, which moved to a URL in the last ~6 months.

This is very similar to https://github.com/mozilla/sccache/issues/406, but not exactly the same.

**Comment by chmanchester** [comment]
The scheduler to client communication is where we suggest setting up a server with a valid cert. This ought to work with HTTP, although I haven't tried this setup myself. Between the server and a client we're using ad hoc certs generated by the server. As long as this is working well (#406 or similar are fixed) this shouldn't require specific intervention from a user or someone setting up a cluster.

**Comment by ncalexan** [comment]
> The scheduler to client communication is where we suggest setting up a server with a valid cert. This ought to work with HTTP, although I haven't tried this setup myself. Between the server and a client we're using ad hoc certs generated by the server. As long as this is working well (#406 or similar are fixed) this shouldn't require specific intervention from a user or someone setting up a cluster.

Yeah, I realized this after digging into the tickets.  I will close this because once the issue(s) preventing the scheduler and the build servers to communicate over TLS are resolved, this won't make much sense.
