### ISSUE TITLE
g++ on .c files fails with sccache

### ISSUE THREAD

**Issue by Trass3r** [mozilla/sccache#440]
Tried sccache while building gcc itself. Their files are still named *.c but are compiled with g++.
Not sure if you can do anything about the g++ detection (implicit `-x c++`):

```sh
$ cat main.c
class Foo;
int main() {}
$ g++ -c main.c
$ sccache g++ -c main.c
main.c:1:1: error: unknown type name ‘class’
 class Foo;
 ^~~~~
$ sccache g++ -c main.c -x c++
```

**Comment by sylvestre** [comment]
fixed now
