### ISSUE TITLE
How do I uninstall sccache?

### ISSUE THREAD

**Issue by sent-hil** [mozilla/sccache#442]
I installed sccache with `cargo install` and was able to uninstall it, however now `cargo build` is broken since it is still try to use sccache to build. Tried removing ~/.cargo ~/.rustup, uninstalling rustup completely. Basically broke all of cargo functionality. I was able to use brew to reinstall it, however I would like to remove it.

Thanks.

**Comment by alok** [comment]
Just a thought, is `$RUSTC_WRAPPER` set to `sccache`? If it is, removing it may help.

**Comment by sent-hil** [comment]
@alok yep, that was it, thanks!
