### ISSUE TITLE
Fail compiles on misconfigured S3 bucket

### ISSUE THREAD

**Issue by alexcrichton** [mozilla/sccache#45]
We discussed this on IRC, but a nifty feature to help debug misconfiguration of S3 credentials would be to fail compilations (perhaps with an error message) if the S3 cache management fails.

I ran into two separate problems during integration:

* First I forgot to make the whole S3 bucket public-readable
* Next, I used the wrong credentials by accident

I think both cases have a fairly predictable error which can flag "misconfiguration" as opposed to transient error, and it'd definitely help working through the setup!

**Comment by alexcrichton** [comment]
One thing I just remembered on https://github.com/rust-lang/rust/pull/38359 though was that we don't have secret env vars on PRs, so the configuration where the access key is specified but the secret key isn't would be nice to continue working.

**Comment by nierob** [comment]
I had the same, a typo in credentials killed 15 min of my time :-)

**Comment by Ten0** [comment]
same here, 30min

**Comment by sylvestre** [comment]
don't hesitate to propose patches to improve this :)
