### ISSUE TITLE
Occassional "entity already exists" failure from build server

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#451]
I set up sccache for distributed compilation on `Fedora 30` (client and dist server) following the guides under `docs/`

Normal sccache operation with redis works fine, but remote compilation always fails with this.
```
 WARN 2019-06-14T20:03:30Z: sccache::compiler::compiler: [serde_json]: Could not perform distributed compile, falling back to local: could not run distributed compilation job: could not run distributed compilation job: Error 500 (Headers={"server": "tiny-http (Rust)", "date": "Fri, 14 Jun 2019 20:03:30 GMT", "content-type": "application/json", "content-length": "152"}): {"description":"run build failed","cause":{"description":"failed to prepare overlay dirs","cause":{"description":"entity already exists","cause":null}}}
```
https://github.com/mozilla/sccache/blob/954897f9c933c7328f5289a38926ab7a6bbff3c2/src/bin/sccache-dist/build.rs#L133 fails since the directory seems to already exist. Is there some rationale behind it or should/could that particular error be ignored?

I applied that change with no side effects (tested without a custom toolchain on Linux x86_64 only).

**Comment by chmanchester** [comment]
I've seen this a few times while testing, re-titling to make it more discoverable.

**Comment by chmanchester** [comment]
The builder is holding a lock at that point, so this probably has to do with servers that have been re-started rather than concurrent accesses.
