### ISSUE TITLE
switch between nightly and stable causes buildfailure

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#454]
`cargo +nightly b` after accidentally running `cargo b` where the default toolchain is `stable`

```
   Compiling unicase v1.4.2
error[E0514]: found crate `rustc` compiled by an incompatible version of rustc
 --> /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/unicase-1.4.2/build.rs:1:1
  |
1 | extern crate version_check as rustc;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.37.0-nightly (9606f6fa6 2019-06-14))
  = note: the following crate versions were found:
          crate `rustc` compiled by rustc 1.35.0 (3c235d560 2019-05-20): /home/bernhard/Projects/rhapsodize/target/debug/deps/libversion_check-b81766fb0f808cf7.rlib

error: aborting due to previous error

error: Could not compile `unicase`.

The quick solution is to delete referenced rlib files, I am also not sure if this is related to sccache at all.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by drahnr** [comment]
Going to be solved by #666

**Comment by repi** [comment]
Did it solve it? Been merged but this is still open.

Would that also solve the case of switching between two different nightly versions (same version number, different date)?

**Comment by drahnr** [comment]
It is indeed solved and can be closed.

**Comment by repi** [comment]
Sweet! Thx

**Comment by drahnr** [comment]
@repl note that you need to flush your cache (redis, memcached or whatever backend you are using) - wrongly versioned binary artifacts are still cached there which will cause you to see errors until they are removed.
The same is true for your `target` dir.

**Comment by repi** [comment]
Ah thanks for the heads up!

**Comment by repi** [comment]
We upgraded to f50207525810c12f9dbad2b9e92892d055b1b38a on `master` and flushed our sccache data and `target/` but are still seeing build failures related to sccache when our CI switches to a new nightly build:

```
error[E0514]: found crate `futures_core` compiled by an incompatible version of rustc
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.5/src/mpsc/mod.rs:81:5
   |
81 | use futures_core::stream::{FusedStream, Stream};
   |     ^^^^^^^^^^^^
   |
   = help: please recompile that crate using this compiler (rustc 1.45.0-nightly (ed084b0b8 2020-05-15))
   = note: the following crate versions were found:
           crate `futures_core` compiled by rustc 1.45.0-nightly (769d12eec 2020-05-12): /var/buildkite/builds/embark-studios/ark/target/debug/deps/libfutures_core-9cd068e3b6544207.rmeta
 ```

@drahnr any ideas of what else could be incorrect?

**Comment by drahnr** [comment]
As a matter of fact, testing focused on switching between stable and nightly, I'll give it a shot soon and post the shell helper function I use to wipe  sccache

**Comment by drahnr** [comment]
```
function cachewipe {
    killall sccache
    rm -r ./target || true
    rm -r ~/.cache/sccache* || true
    redis-cli -u redis://1.2.3.4:6379/2 flushall || true
    export SCCACHE_RECACHE=1
}
```
followed by `cargo b` does work for me

**Comment by repi** [comment]
We use a GCS bucket for our sccache storage, which we've wiped manually and works, but as there are nightly releases every few days or so this gets tricky as every update would need a full cache wipe.

**Comment by drahnr** [comment]
The above should really only be necessary once  - from pre #666 to post #666 - I am hopefully going to get around to test this soon

**Comment by froydnj** [comment]
> The above should really only be necessary once - from pre #666 to post #666 - I am hopefully going to get around to test this soon

Wait, why is it even necessary in the first place?

**Comment by drahnr** [comment]
@repl a colleague just provided me a way of reproducing it
@froydnj frankly I don't remember why, could have been just coincidence that it never happened ever after I did that?

**Comment by drahnr** [comment]
Tried to reproduce this today, to no avail.
