### ISSUE TITLE
sccache makes cargo always rebuild dependencies

### ISSUE THREAD

**Issue by apiraino** [mozilla/sccache#457]
### Basic Information
sccache version: 0.2.8, tried also [v0.2.9.alpha-0 commit  9e5df99](https://github.com/lzutao/sccache/releases/tag/0.2.9)
OS: Linux 5.0.0-17-generic #18-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
cargo version; 1.37.0-nightly (545f35425 2019-05-23)
rustc version: 1.37.0-nightly (4edff843d 2019-06-16)

### How to reproduce

```
$ echo $RUSTC_WRAPPER
sccache
$ git clone https://github.com/apiraino/cargo-sccache-build-bug

$ cargo check
$ cargo clean && cargo build
$ cargo build # unexpected rebuild of all packages

$ unset RUSTC_WRAPPER
$ cargo clean && cargo build
$ cargo build # does not rebuild all dependencies

$ export RUSTC_WRAPPER=sccache
$ cargo clean && cargo build
$ cargo build # rebuild again all dependencies
```

#### Logs 

`CARGO_LOG=trace cargo build &> log.log`

[log.log.gz](https://github.com/mozilla/sccache/files/3315968/log.log.gz)

(Notice all those `fingerprint error`)

**Comment by theduke** [comment]
This was fixed for me in  #441.

You can install from git with `cargo install --force --git=https://github.com/mozilla/sccache`.

A new release would be very welcome.

**Comment by lzutao** [comment]
@apiraino, If you are using, can you provide result of `whereis sccache`.

**Comment by apiraino** [comment]
@theduke confirmed that installing from master branch delivers a fixed version :+1:  And, yes, a release would be highly appreciated. Feel free to close this issue if it's not useful anymore.

@lzutao I can consistently reproduce the issue with the 0.2.8 installed with `cargo install sccache`:
```
$ whereis sccache
sccache: /home/$USER/.cargo/bin/sccache
$ sccache -V
sccache 0.2.8
```

By the way, updating from 0.2.8 > 0.2.9 seems to break the cache: I need to delete all cache before running these two versions.

**Comment by lzutao** [comment]
Okay then. You could close this issue. None of us has right (permission) to close it.

**Comment by apiraino** [comment]
Dupe of https://github.com/mozilla/sccache/issues/436

**Comment by froydnj** [comment]
> @theduke confirmed that installing from master branch delivers a fixed version +1 And, yes, a release would be highly appreciated. Feel free to close this issue if it's not useful anymore.

@chmanchester , are you up for attempting to walk through the release process?

> By the way, updating from 0.2.8 > 0.2.9 seems to break the cache: I need to delete all cache before running these two versions.

@apiraino Can you file a bug on this?  Even better if you can bisect it down to the offending commit.

**Comment by chmanchester** [comment]
> > @theduke confirmed that installing from master branch delivers a fixed version +1 And, yes, a release would be highly appreciated. Feel free to close this issue if it's not useful anymore.
> 
> @chmanchester , are you up for attempting to walk through the release process?

Sure, I'll take a look. I was hoping to get the `patch` sections removed but don't think that's going to happen soon.

**Comment by apiraino** [comment]
> @apiraino Can you file a bug on this? Even better if you can bisect it down to the offending commit.

I'm not familiar with the codebase but I'll gladly give a try :+1:
