### ISSUE TITLE
(Rust) Updating sccache from 0.2.8 to 0.2.9@806ce30 breaks reading cache files

### ISSUE THREAD

**Issue by apiraino** [mozilla/sccache#464]
sccache version: 0.2.9 806ce303cf63ce89ef36cfe06389e7179baec31f
OS: Linux 5.0.0-17-generic #18-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
cargo version; 1.37.0-nightly (545f35425 2019-05-23)
rustc version: 1.37.0-nightly (4edff843d 2019-06-16)

### How to reproduce

```
# get 0.2.8
$ cargo install sccache 
$ git clone https://github.com/apiraino/cargo-sccache-build-bug
$ cargo clean && cargo build
# all good
# now compile sccache from commit master@806ce30
$ cargo clean && cargo build
# build breaks
```

According to a `git bisect`, the culprit is commit 806ce303cf63ce89ef36cfe06389e7179baec31f

Attached log file

[log2.log.gz](https://github.com/mozilla/sccache/files/3322419/log2.log.gz)

**Comment by chmanchester** [comment]
Ah, it looks like we should have updated `CACHE_VERSION` as a part of that change, I didn't know about that at the time. Thank you for the detailed report!

**Comment by chmanchester** [comment]
@apiraino can you test with that fix if you have an opportunity? I wasn't able to reproduce the issue, but I'm pretty sure that will fix things.

**Comment by apiraino** [comment]
>  I wasn't able to reproduce the issue, but I'm pretty sure that will fix things.

One step I forgot to mention is to delete the local cache before starting the workflow I described above, sorry about that.

Anyway that "big" patch fixes the issue :-) now I can move from versions without issues.

Thank you so much for taking care of this in no time. Really appreciated! :+1:
