### ISSUE TITLE
sccache: cause: Too many open files (os error 24)

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/sccache#468]
When building Firefox with sccache I got:

```
Compiling style v0.0.1 (/Users/zbraniecki/projects/mozilla-unified/servo/components/style)
1:46.91 dom/debugger
1:56.44 dom/encoding
2:18.57 sccache: encountered fatal error
2:18.57 sccache: error : Failed to open file for hashing: "/Users/zbraniecki/projects/mozilla-unified/servo/components/style/values/specified/ui.rs"
2:18.57 sccache: cause: Failed to open file for hashing: "/Users/zbraniecki/projects/mozilla-unified/servo/components/style/values/specified/ui.rs"
2:18.57 sccache: cause: Too many open files (os error 24)
2:18.78 error: Could not compile `style`.
```

Here's a larger log: https://paste.mozilla.org/hZw6ETan

I'm on MBP 2017 with 4 cores, and was compiling opt/release.

**Comment by chmanchester** [comment]
I was finally able to reproduce this. It only happens for me when make (in the firefox build system) ends up spawning the sccache server so it sees its jobserver with a large number of jobs specified. It pops up here and there, but usually the root is when the server goes to hash files for `style`. I noticed `style` has over 200 dependent sources that get hashed. Looking at the structure of the code here: https://github.com/mozilla/sccache/blob/e516d90a804e41a27b9342f9c43bfa76171f4b42/src/util.rs#L47 we open each file (it seems on the main thread...) and pass a handle to a worker thread. This seems like we could end up opening a bunch of files up front before the worker thread has a chance to close any, and the file handle is specified with a `'static` lifetime as passed to `Digest::reader`, which I guess might be making things worse.

As a workaround I'm testing a change to just open and read each file on the worker thread, which is going well so far, although it reproduces only under certain circumstances for me so it might be good to have someone else verify...

**Comment by luser** [comment]
FWIW the `'static` lifetime is just a trait bound, it's to ensure that you can't pass like something borrowed like `&File` that wouldn't live long enough. In this case the code is passing an owned `File` so that's not an issue, but your initial diagnosis (all the files get opened on the main thread) sounds correct.
