### ISSUE TITLE
Send environment variables from client to server for compiler invocations

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#48]
@alexcrichton noted that sccache breaks an assumption that the Rust build system has about invoking MSVC, namely that it can set environment variables like `INCLUDE` and `LIB` on a per-compile basis to avoid having to have them set in the shell. Currently sccache uses the environment that the server process was invoked with as the environment for running all compiler processes, but that doesn't have to be the case. We can send the environment over with the compile request and use it for invoking the compiler.

We might need to add certain environment variables to the hash key to make this work, I'd have to look into it. `INCLUDE` should only affect the preprocessor, and that output is already included in the hash key. Looking at the other [CL environment variables](https://msdn.microsoft.com/en-us/library/kezkeayy.aspx), it doesn't look like there's anything else that would cause problems.

**Comment by alexcrichton** [comment]
My thinking for not needing to include it in the hash key also stemmed from the fact that for any `cl.exe` binary there's basically just one set of working environment variables (e.g. there's no variance within that one binary) so it should be fine to ignore. I guess it can't hurt to throw it in though!
