### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by posix4e** [mozilla/sccache#49]
I actually did this. I am happy to pull it down but I got sick of checking out the github in scripts.

```
diff --git a/Cargo.toml b/Cargo.toml
index b985929..8193bd1 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -2,6 +2,10 @@
 name = "sccache"
 version = "0.1.0"
 authors = ["Ted Mielczarek <ted@mielczarek.org>"]
+license = "Apache-2.0"
+description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
+repository = "https://github.com/mozilla/sccache/"
+
 
 [dependencies]
 app_dirs = "1.1.1"
```

Was all I needed. Now I can cargo install sccache

**Comment by luser** [comment]
This was planned, but I was sorting out a few remaining issues before I recommended it for wider use. Primarily I've been working on making it so that building Firefox with sccache locally works out-of-the-box.
