### ISSUE TITLE
Concurrency-limit automatic toolchain packaging

### ISSUE THREAD

**Issue by chmanchester** [mozilla/sccache#519]
I noticed in a distributed firefox build that if we reach the rust part of the build and the client needs to package a new toolchain the process can get kicked off multiple times, which bogs down the client for a while. I'm not sure the best way to achieve this, but we should limit cases like these.

**Comment by luser** [comment]
I thought I remembered (and it's still there) a global lock for toolchain creation:
https://github.com/mozilla/sccache/blob/6e3295a22283d6143859c8838f583cb37c176e03/src/dist/cache.rs#L159

**Comment by chmanchester** [comment]
It looks like that lock is acquired a little too late, if I move it earlier everything goes fine. Thanks for the pointer!
