### ISSUE TITLE
Preprocessor handling

### ISSUE THREAD

**Issue by sigiesec** [mozilla/sccache#521]
Compared to what I know from the use of icecream/icecc, I find the handling of preprocessing by sccache less optimal.

With icecream/icecc, this worked transparently. The compiler output was the same, regardless of whether the compilation was done locally or remotely.

When using sccache, the compiler output is hardly useful in case of warnings or errors, because the compilation is done on the preprocessed source code, and all macro usages have been rolled out. If the code having warnings/errors uses macros heavily, this is virtually unreadable. In addition, this yields a lot additional meaningless warnings that only occur because the compiler only sees the result of the preprocessor (such as loop executed only once, e.g.). Also, the console coloring is not applied (but this wouldn't be helpful anyway in the cases mentioned before).

I am not sure if this is true also for compilation that goes through sccache but it actually done locally, or if this only applies to compilation done remotely.

In the former case, this issue might be mitigated to some extent, by allowing to disable remote compilation for certain paths (i.e. code that the user is actively working on), or rerunning the compilation locally when remote compilation had errors.

Why does this happen? I took not of #178, which seems to imply that the behaviour was already changed to match my expectation quite some time ago, but with the current version of sccache, this still happens to me. Can this be configured?

**Comment by froydnj** [comment]
icecc does exactly the same thing as sccache as far as sending preprocessed source to remote machines for compilation, cf.

https://github.com/icecc/icecream/blob/aa9e2fc68ee045f7fb55dab853f1cf58a80d2952/client/remote.cpp#L508-L556

The alternative (running the preprocessor on the remote machine) requires setting up remote machines with exactly the same paths and exactly the same files as the local machines, which is not really doable for a lot of environments.

Maybe a more specific example would help explain the problem you're seeing.  When #178 was implemented, I believe we didn't have distributed compilation, so the strategy there doesn't apply for distributed compilation.

**Comment by sigiesec** [comment]
I am seeing something like this, e.g.:
```
/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp:27100:1040: warning: code will never be executed [-Wunreachable-code]
MozExternalRefCountType FileHelper::ReadCallback::AddRef(void) { static_assert(!mozilla::IsDestructible<FileHelper::ReadCallback>::value, "Reference-counted class " "FileHelper::ReadCallback" " should not have a public destructor. " "Make this class's destructor non-public"); do { static_assert( mozilla::detail::AssertionConditionType<decltype(int32_t(mRefCnt) >= 0)>::isValid, "invalid assertion condition"); if ((__builtin_expect(!!(!(!!(int32_t(mRefCnt) >= 0))), 0))) { MOZ_ReportAssertionFailure("int32_t(mRefCnt) >= 0" " (" "illegal refcnt" ")", "/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp", 27100); AnnotateMozCrashReason("MOZ_ASSERT" "(" "int32_t(mRefCnt) >= 0" ") (" "illegal refcnt" ")"); do { *((volatile int*)__null) = 27100; ::abort(); } while (false); } } while (false); do { static_assert( mozilla::detail::AssertionConditionType<decltype("FileHelper::ReadCallback" != nullptr)>::isValid, "invalid assertion condition"); if ((__builtin_expect(!!(!(!!("FileHelper::ReadCallback" != nullptr))), 0))) { MOZ_ReportAssertionFailure("\"FileHelper::ReadCallback\" != nullptr" " (" "Must specify a name" ")", "/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp", 27100); AnnotateMozCrashReason("MOZ_ASSERT" "(" "\"FileHelper::ReadCallback\" != nullptr" ") (" "Must specify a name" ")"); do { *((volatile int*)__null) = 27100; ::abort(); } while (false); } } while (false); if (!mRefCnt.isThreadSafe) this->_mOwningThread.AssertOwnership("FileHelper::ReadCallback" " not thread-safe"); nsrefcnt count = ++mRefCnt; NS_LogAddRef((this), (count), ("FileHelper::ReadCallback"), (uint32_t)(sizeof(*this))); return count; };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is a warning that wouldn't be present originally. Turning of -Wunreachable-code (and similar ones) is not a doable option, since this would also turn it off for non-preprocessing-related code locations.

Similarly, if I introduce an error on purpose, I get something like this (for some reason twice):
```
/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp:25735:95: error: expression is not assignable
        do { static_assert( mozilla::detail::AssertionConditionType<decltype(mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse)>::isValid, "invalid assertion condition"); if ((__builtin_expect(!!(!(!!(mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse))), 0))) { MOZ_ReportAssertionFailure("mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse", "/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp", 25736); AnnotateMozCrashReason("MOZ_ASSERT" "(" "mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse" ")"); do { *((volatile int*)__null) = 25736; ::abort(); } while (false); } } while (false);
                                                                             ~~~~~~~~~~~~~~~~ ^
/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp:25735:241: error: expression is not assignable
        do { static_assert( mozilla::detail::AssertionConditionType<decltype(mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse)>::isValid, "invalid assertion condition"); if ((__builtin_expect(!!(!(!!(mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse))), 0))) { MOZ_ReportAssertionFailure("mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse", "/home/osboxes/work/mozilla-unified/dom/indexedDB/ActorsParent.cpp", 25736); AnnotateMozCrashReason("MOZ_ASSERT" "(" "mResponse.type() = CursorResponse::TArrayOfObjectStoreKeyCursorResponse" ")"); do { *((volatile int*)__null) = 25736; ::abort(); } while (false); } } while (false);
```

While in this simple case, I can actually figure out the problem from the message, it is already very hard to read. And in more complex cases (imagine involving templates), it will be even much harder.

> The alternative (running the preprocessor on the remote machine) requires setting up remote machines with exactly the same paths and exactly the same files as the local machines, which is not really doable for a lot of environments.

Doesn't icecream do exactly that automatically, i.e. package the whole environment and transport it to the remote machine, where it is cached? As I wrote above, I never saw these kind of warnings with icecream.

I didn't notice that #178 applied to local compilation only, but the problem solved by #178 (which is essentially what I reported here) applies to the remote case as well.

**Comment by froydnj** [comment]
> Doesn't icecream do exactly that automatically, i.e. package the whole environment and transport it to the remote machine, where it is cached? As I wrote above, I never saw these kind of warnings with icecream.

icecream packages the environment for the toolchain, not your entire compilation environment (since, in general, your entire compilation environment is not automatically discoverable by icecream).

I see that icecream has a bunch of logic for extra flags to add on the server side:

https://github.com/icecc/icecream/blob/aa9e2fc68ee045f7fb55dab853f1cf58a80d2952/daemon/workit.cpp#L264-L315

Maybe we should be adding `-fpreprocessed` in this case?  Are you using clang or gcc with sccache?  With icecream?  And are you sure you're using identical versions of the compiler in both cases?

**Comment by sigiesec** [comment]
> icecream packages the environment for the toolchain, not your entire compilation environment (since, in general, your entire compilation environment is not automatically discoverable by icecream).

Makes sense... wasn't thinking about that to much, I was just happy that it worked ;)

> Maybe we should be adding -fpreprocessed in this case?

Sounds plausible, however icecream appears to add this only in the case of gcc based on the fragment you shared, but maybe the other options also influence the behaviour. -fpreprocessed is also implicit for certain file endings such as .i/.ii

> Are you using clang or gcc with sccache? With icecream?

clang 8 in either case.

> And are you sure you're using identical versions of the compiler in both cases?

No, I am not sure. Alll I can say is that it worked. I was relying on that icecream ensures this (and I understood from the documentation that it does that at least on Linux).

**Comment by sigiesec** [comment]
Ah, another thing, what about adding `-fdirectives-only` (for GCC) and `-frewrite-includes` (for Clang) when preprocessing locally? I found this under https://ccache.dev/manual/latest.html (run_second_cpp).

**Comment by sigiesec** [comment]
I would like to test the arguments mentioned in https://github.com/mozilla/sccache/issues/521#issuecomment-534044848, but I am somewhat lost in the source code where to add this. Possibly any hints on this?

**Comment by chmanchester** [comment]
@sigiesec Adding something around here: https://github.com/mozilla/sccache/blob/a7611fda57c325109c56fbf69d6a3b1ce6b421ae/src/compiler/gcc.rs#L445-L460 looks like it should work for a test.

**Comment by luser** [comment]
I think if you're going to use either of those arguments you'd have to also change the `generate_compile_commands` implementation to pass the preprocessor arguments to the compiler as well. (Currently they do not get passed.)

**Comment by sigiesec** [comment]
Hm, I wanted to test this but if I try to do a distributed build, I always get 
```
DEBUG 2019-10-16T08:33:16Z: sccache::commands: Server sent UnhandledCompile
```

Can I somehow see why the server (I think this means my local server) cannot handle the compile?

**Comment by luser** [comment]
Yes, you should be able to run `sccache --show-stats` to see details on compile requests it could not handle with specifics.

**Comment by sigiesec** [comment]
Ah, stupid mistake. It said `non-compilation request`, and that was right, I wasn't aware I need to do a compilation only call to have it cacheable.

Now it works as expected:
```
[simon@sigibln sccache]$ target/debug/sccache ~/.mozbuild/clang/bin/clang++ -c test.cpp -Wall -Wextra -Wunreachable-code
[simon@sigibln sccache]$ killall sccache
[simon@sigibln sccache]$ ~/.cargo/bin/sccache ~/.mozbuild/clang/bin/clang++ -c test.cpp -Wall -Wextra -Wunreachable-code
test.cpp:53:62: warning: self-comparison always evaluates to true [-Wtautological-compare]
int main() { !(((google_breakpad::LogStream::SEVERITY_ERROR) >= (google_breakpad::LogStream::SEVERITY_ERROR))) ? (void)0 : google_breakpad::LogMessageVoidify() & (std::cout) << "UTF16ToUTF8 found low surrogate "; }
                                                             ^
test.cpp:53:120: warning: code will never be executed [-Wunreachable-code]
int main() { !(((google_breakpad::LogStream::SEVERITY_ERROR) >= (google_breakpad::LogStream::SEVERITY_ERROR))) ? (void)0 : google_breakpad::LogMessageVoidify() & (std::cout) << "UTF16ToUTF8 found low surrogate "; }
                                                                                                                       ^
2 warnings generated.
```

First is my ad-hoc modified version (no warning), second is the upstream version (warning from expanded macro).
