### ISSUE TITLE
Optimize our scheduling algorithm for sccache-dist

### ISSUE THREAD

**Issue by chmanchester** [mozilla/sccache#523]
Multiple users of sccache-dist have reported scheduling that's odd enough that they're not sure the system if functioning properly at all. The scenario in each is the same: on a cluster with two build servers one server produces an error and the other gets assigned all subsequent jobs as a result while the first server mostly sits idle. This is because we allow a large multiple of a server's available cores (10 I believe) to be assigned to a server as a matter of "normal" operation before trying a server with a recent error. This setup assumes we have lots of servers to choose from and errors are infrequent, which isn't always the case.

**Comment by froydnj** [comment]
This could also be happening because of the symptoms seen in #608 where there's clock skew between the scheduler and the build server(s).

**Comment by chmanchester** [comment]
Oh, yes, I think I fixed something else that brought the error rate down far enough that this isn't an issue anymore.
