### ISSUE TITLE
Failed to mount overlay FS

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sccache#531]
> WARN 2019-10-08T12:17:04Z: sccache::dist::http::server: Res 50 error: run build failed, caused by: Compilation execution failed, caused by: Failed to mount overlay FS, caused by: overlayfs "/home/sccache/build/toolchains/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e",upperdir="/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/upper",workdir="/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/work" -> "/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/target": No such device (os error 19) ("/home/sccache/build/toolchains/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e": exists, upperdir: exists, workdir: exists, same-fs, target: exists, superuser)
> TRACE 2019-10-08T12:17:04Z: sccache::dist::http::server: Res 50: Response { status_code: 500, WARN 2019-10-08T12:17:04Z: sccache::dist::http::server: Res 50 error: run build failed, caused by: Compilation execution failed, caused by: Failed to mount overlay FS, caused by: overlayfs "/home/sccache/build/toolchains/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e",upperdir="/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/upper",workdir="/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/work" -> "/home/sccache/build/builds/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e-17/target": No such device (os error 19) ("/home/sccache/build/toolchains/2114f9f754b173aae4335ae577941802de3acf852706facaf1380e1d86c133812b0425b46c5f9587df4723d1302c726f1e96579137edd5332ead7a6cc24e4c8e": exists, upperdir: exists, workdir: exists, same-fs, target: exists, superuser)
TRACE 2019-10-08T12:17:04Z: sccache::dist::http::server: Res 50: Response { status_code: 500, headers: [("Content-Type", "application/json")] }
headers: [("Content-Type", "application/json")] }
>

**Comment by chmanchester** [comment]
@mozfreddyb Can you provide the kernel version running on this server? Also, is there another layer of isolation in use before the server runs? From what I found from a quick search it seems this can happen if the overlay is running in an overlay, or inside of docker.

**Comment by mozfreddyb** [comment]
kernel is 5.2.9-arch1-1-ARCH
I started the server directly from a root shell.

I'm happy to help you track this down and collect more info if you can give me a tiny patch that adds more logging (or a tiny script/command) that shouldn't fail :)

**Comment by cr** [comment]
The problem persists with sccache 0.2.13-alpha.0.

/home is ext4. It failed with the same error on a subdirectory in /tmp, which is tmpfs.Thinking about trying with a btrfs volume the server hosts, but I don't think that's going to help with the overlayfs error.

**Comment by froydnj** [comment]
> Preliminary analysis shows the overlayfs error was on our side.

Given this, I'm going to close this issue; feel free to open new ones.
