### ISSUE TITLE
Q: can sccache be used from within a Dockerfile?

### ISSUE THREAD

**Issue by naseemkullah** [mozilla/sccache#547]
Problem: trying to use a remote ccache within Dockerfile builds that will update the ccache after a build and re upload to remote location, however there is no way to mount a volume during a `docker build`.

Would it be possible to run `sccache` within the Dockerfile and have it retrieve, use and then re upload the ccache folder with the new content?

**Comment by parisholley** [comment]
this would be great, the documentation says that if the server is not launched, the daemon is launched automatically, but using `RUSTC_WRAPPER=sccache` appears to be a no-op...

**Comment by benmarten** [comment]
I think you can use Docker [Buildkit](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md):

```
# syntax = docker/dockerfile:experimental
[...]
RUN --mount=type=cache,target=/root/.cache/sccache \
	cargo build --release
```

Don't forget to set `set -x DOCKER_BUILDKIT 1` env var ;)

**Comment by sanmai-NL** [comment]
Answered above and in #687, #1160 and #1475. Can you close this @naseemkullah?
