### ISSUE TITLE
Missing response in scheduler

### ISSUE THREAD

**Issue by Kiwi-MethodPark** [mozilla/sccache#561]
Currently my first try in distributed compilation with sccache is just on my machine with HTTP and no reverse proxy. Here are the relevant parts of my scheduler.conf:
`public_addr = "0.0.0.0:10600"
[server_auth]
type = "DANGEROUSLY_INSECURE"`
server.conf:
`
public_addr = "127.0.0.1:10502"
scheduler_url = "127.0.0.1:10600"
[scheduler_auth]
type = "DANGEROUSLY_INSECURE"
`
The connection between server and scheduler works fine according to the log files. It look like the server even responds to assign_job with 200 but the answer never reaches the scheduler (timeout). 

server.log

> Oct 24 16:34:56 kiwi-ThinkPad-T480s sccache-buildserver[9721]: Req 0 (127.0.0.1:54682): Request { method: "POST", url: "/api/v1/distserver/assign_job/0", headers: [("authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqb2JfaWQiOjB9.MRnkLV0CH4Dw582ErdwxABQlZwMEjNWy0bNQcGjpHaI"), ("content-type", "application/octet-stream"), ("content-length", "136"), ("user-agent", "reqwest/0.9.22"), ("accept", "*/*"), ("accept-encoding", "gzip"), ("host", "127.0.0.1:10502")], https: false, remote_addr: V4(127.0.0.1:54682) }
Oct 24 16:34:56 kiwi-ThinkPad-T480s sccache-buildserver[9721]: Req 0: assign_job(0): Toolchain { archive_id: "6d637ba3c500362b806be3df7322e2b04466abbf03bfdd68cf6b2341fcf83832395c1682c0629948fdeae624e3fc87aaab08b616e3cb31dc5c2f12a8fa160af2" }
Oct 24 16:34:56 kiwi-ThinkPad-T480s sccache-buildserver[9721]: Res 0: Response { status_code: 200, headers: [("Content-Type", "application/octet-stream")] }

scheduler.log

> TRACE 2019-10-24T14:34:56Z: sccache::dist::http::server: Req 4 (127.0.0.1:38568): Request { method: "POST", url: "/api/v1/scheduler/alloc_job", headers: [("authorization", "Bearer token"), ("content-type", "application/octet-stream"), ("content-length", "136"), ("user-agent", "reqwest/0.9.22"), ("accept", "*/*"), ("accept-encoding", "gzip"), ("host", "localhost:10600")], https: false, remote_addr: V4(127.0.0.1:38568) }
TRACE 2019-10-24T14:34:56Z: sccache::dist::http::server: Req 4: alloc_job: Toolchain { archive_id: "6d637ba3c500362b806be3df7322e2b04466abbf03bfdd68cf6b2341fcf83832395c1682c0629948fdeae624e3fc87aaab08b616e3cb31dc5c2f12a8fa160af2" }
TRACE 2019-10-24T14:34:56Z: sccache_dist: Selected ServerId(V4(127.0.0.1:10502)) as the server with the best load
 INFO 2019-10-24T14:34:56Z: sccache_dist: Job 0 created and will be assigned to server ServerId(V4(127.0.0.1:10502))
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: hyper::client::pool: checkout waiting for idle connection: "https://127.0.0.1:10502"
TRACE 2019-10-24T14:34:56Z: hyper::client::connect::http: Http::connect; scheme=https, host=127.0.0.1, port=Some(10502)
DEBUG 2019-10-24T14:34:56Z: hyper::client::connect::http: connecting to 127.0.0.1:10502
DEBUG 2019-10-24T14:34:56Z: tokio_reactor: adding I/O source: 0
TRACE 2019-10-24T14:34:56Z: mio::poll: registering with poller
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Write for: 0
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Writable Token(0)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2019-10-24T14:34:56Z: hyper::client::connect::http: connected to Some(V4(127.0.0.1:10502))
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Read for: 0
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Read for: 0
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 0 events, 0.000s
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable | Writable Token(0)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: hyper::client::conn: client handshake HTTP/1
TRACE 2019-10-24T14:34:56Z: hyper::client: handshake complete, spawning background dispatcher task
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Read for: 0
TRACE 2019-10-24T14:34:56Z: want: signal: Want
TRACE 2019-10-24T14:34:56Z: want: signal found waiting giver, notifying
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: want: poll_want: taker wants!
TRACE 2019-10-24T14:34:56Z: hyper::client::pool: checkout dropped for "https://127.0.0.1:10502"
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable | Writable Token(0)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 2 events, 0.000s
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Read for: 0
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::role: Client::encode method=POST, body=Some(Known(136))
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::io: detected no usage of vectored write, flattening
DEBUG 2019-10-24T14:34:56Z: hyper::proto::h1::io: flushed 318 bytes
DEBUG 2019-10-24T14:34:56Z: hyper::proto::h1::io: flushed 136 bytes
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable | Writable Token(0)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::conn: Conn::read_head
DEBUG 2019-10-24T14:34:56Z: tokio_reactor::registration: scheduling Read for: 0
TRACE 2019-10-24T14:34:56Z: hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
TRACE 2019-10-24T14:34:56Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:34:56Z: tokio_reactor: loop process - 0 events, 0.000s
TRACE 2019-10-24T14:35:10Z: sccache::dist::http::server: Req 5 (127.0.0.1:38554): Request { method: "POST", url: "/api/v1/scheduler/heartbeat_server", headers: [("authorization", "Bearer 127.0.0.1:10502 dangerously_insecure_server"), ("content-type", "application/octet-stream"), ("content-length", "1109"), ("user-agent", "reqwest/0.9.22"), ("accept", "*/*"), ("accept-encoding", "gzip"), ("host", "127.0.0.1:10600")], https: false, remote_addr: V4(127.0.0.1:38554) }
TRACE 2019-10-24T14:35:10Z: sccache::dist::http::server: Req 5: heartbeat_server: HeartbeatServerHttpRequest { jwt_key: [149, 251, 215, 75, 60, 235, 97, 1, 63, 244, 78, 101, 199, 66, 228, 83, 244, 197, 192, 172, 20, 189, 128, 99, 236, 216, 114, 37, 205, 244, 205, 157], num_cpus: 8, server_nonce: ServerNonce(13201835503347839301), cert_digest: [216, 255, 226, 218, 161, 15, 100, 173, 242, 106, 161, 152, 134, 231, 226, 149, 182, 152, 112, 110], cert_pem: [...1017 bytes...] }
TRACE 2019-10-24T14:35:10Z: sccache::dist::http::server: Res 5: Response { status_code: 200, headers: [("Content-Type", "application/octet-stream")] }
TRACE 2019-10-24T14:35:26Z: tokio_reactor: event Readable Token(4194303)
TRACE 2019-10-24T14:35:26Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2019-10-24T14:35:26Z: reqwest::client: response receiver is canceled
 WARN 2019-10-24T14:35:26Z: sccache::dist::http::server: Res 4 error: assign job failed, job un-assigned from the server, caused by: POST to scheduler assign_job failed, caused by: timed out

**Comment by Kiwi-MethodPark** [comment]
The problem was a combination of the latest release and static compiled openssl. I compiled from source in a docker container without static Openssl all works now.

**Comment by jigpu** [comment]
In my case, the timeout seems to have been caused by a deadlock in tiny-http that has been worked around on master, but not in the 0.2.12 release.
