### ISSUE TITLE
Use .aws/config

### ISSUE THREAD

**Issue by Spenser309** [mozilla/sccache#576]
I'm using the excellent aws-google-auth tool from  https://github.com/cevoaustralia/aws-google-auth .  I'm having trouble using sccache with this tool because it won't go to my .aws/config to learn how to authenticate.  Is there maybe an undocumented way to make these things work together?

**Comment by Xuanwo** [comment]
SHould be fixed by https://github.com/mozilla/sccache/issues/1404. Now sccache will read `.aws/config`
