### ISSUE TITLE
bwrap: execvp /bin/clang++: No such file or directory

### ISSUE THREAD

**Issue by nornagon** [mozilla/sccache#580]
When sending a toolchain for crosscompile with sccache-dist, I'm getting the following error:

```
bwrap: execvp /bin/clang++: No such file or directory
```

`bin/clang++` is certainly the path to the compiler within my toolchain archive. It's unclear to me why the compiler can't be executed.

Is this perhaps some bad interaction between the versions of kernel / overlayfs / bwrap / sccache that I'm using? Has anyone seen this error before?

Thanks!

**Comment by chmanchester** [comment]
This usually means there's something going wrong with the paths in your client config, or the toolchain archive was made in some way that causes problems on the build machine. Can you post a bit more of your client config and/or how you acquired your toolchain archive?

**Comment by nornagon** [comment]
My toolchain archive is https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-373424-64a362e7-1.tgz, and my client config has this:

```
[[dist.toolchains]]
type = "path_override"
compiler_executable = "/Users/nornagon/work/electron-bootstrap/src/out/Testing/../../third_party/llvm-build/Release+Asserts/bin/clang++"
archive = "/Users/nornagon/work/toolchains/clang-373424-64a362e7-1.tgz"
archive_compiler_executable = "/bin/clang++"
```

**Comment by chmanchester** [comment]
That archive seems to be missing `libgcc_s.so` compared to a known good archive I have locally. sccache has a helper comment `sccache --package-toolchain` that will create a self-sufficient archive.

**Comment by nornagon** [comment]
hm, indeed, i see this:
```
$ ldd /tmp/build/toolchains/8d534d4743cabde984282e18060d3725f8e8f16c375d4861f810a8460b76e684242fbc6d0bed41de0c169ec27b2a1f0d619bfc37ae97c2e6456e0955fe737b77/bin/clang
	linux-vdso.so.1 (0x00007ffc56d43000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f14b1a29000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f14b180c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f14b1604000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f14b1400000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f14b1062000)
	libstdc++.so.6 => /tmp/build/toolchains/8d534d4743cabde984282e18060d3725f8e8f16c375d4861f810a8460b76e684242fbc6d0bed41de0c169ec27b2a1f0d619bfc37ae97c2e6456e0955fe737b77/bin/../lib/libstdc++.so.6 (0x00007f14b0ce8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f14b0ad0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14b06df000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f14b1c48000)
```

so looks like there are a few libs it's expecting from the system. i'm surprised to see the error "No such file or directory" though..?

**Comment by luser** [comment]
The build server executes builds inside a new mount namespace (effectively a chroot), so the compiler binary won't see any files from the host system. Any libraries that aren't in the toolchain package won't be available.

**Comment by nornagon** [comment]
Ohh, so the 'no such file or directory' is coming from the dynamic linker? I assumed it was having trouble finding the `clang++` binary, which is definitely there (well, it's a symlink, but i tried with just `clang` as well which isn't, and got the same message)

**Comment by sylvestre** [comment]
Afaik, it isn't happening anymore
