### ISSUE TITLE
Support for C++ files ending in '.C'?

### ISSUE THREAD

**Issue by razeh** [mozilla/sccache#586]
I am working in a code base where the C++ filename extension is '.C'. It looks like that extension isn't supported in src/compiler/c.rs

I tried adding support for '.C' extensions with this modification on line c.rs:111:

    -           Some("cc") | Some("cpp") | Some("cxx") => Some(Language::Cxx),
    +           Some("C") | Some("cc") | Some("cpp") | Some("cxx") => Some(Language::Cxx),

But when I try:
    sccache gcc -c foo.C 

I'm still seeing the unknown source language increment. What do I need to do to get filenames that end in .C cached?

**Comment by emilio** [comment]
That should be enough, and it works for me with that local change

**Comment by emilio** [comment]
(Maybe you were running an outdated daemon? Did you run `sccache --stop-server` after rebuilding?)

**Comment by razeh** [comment]
I was doing an install of sccache rather than using --path.
Thanks!

**Comment by razeh** [comment]
I created a pull request for this: #595

**Comment by razeh** [comment]
Merged.
