### ISSUE TITLE
Running sccache-dist server inside an unprivileged docker container

### ISSUE THREAD

**Issue by razeh** [mozilla/sccache#592]
Is it possible to run sccache-dist server from inside an unprivileged docker container? I'm getting all sorts of errors along the lines of:

 WARN 2019-11-11T21:30:24Z: sccache::dist::http::server: Res 9 error: run build failed, caused by: Compilation execution failed, caused by: Failed to enter a new Linux namespace, caused by: Operation not permitted

**Comment by razeh** [comment]
Even outside of docker I get:

` WARN 2019-11-11T22:25:49Z: sccache::dist::http::server: Res 6267 error: run build failed, caused by: Compilation execution failed, caused by: Failed to mount overlay FS, caused by: overlayfs "/tmp/build/toolchains/7c5bf67ef1fc8875e6f228eb903b0107afc10e2e9d35a95eb0dea966f1cbc626924bde1d599a80a8ca165673d39003b3322a7aa70c7e1c9967c7288a139b4cba",upperdir="/tmp/build/builds/7c5bf67ef1fc8875e6f228eb903b0107afc10e2e9d35a95eb0dea966f1cbc626924bde1d599a80a8ca165673d39003b3322a7aa70c7e1c9967c7288a139b4cba-3134/upper",workdir="/tmp/build/builds/7c5bf67ef1fc8875e6f228eb903b0107afc10e2e9d35a95eb0dea966f1cbc626924bde1d599a80a8ca165673d39003b3322a7aa70c7e1c9967c7288a139b4cba-3134/work" -> "/tmp/build/builds/7c5bf67ef1fc8875e6f228eb903b0107afc10e2e9d35a95eb0dea966f1cbc626924bde1d599a80a8ca165673d39003b3322a7aa70c7e1c9967c7288a139b4cba-3134/target": Invalid path ("/tmp/build/toolchains/7c5bf67ef1fc8875e6f228eb903b0107afc10e2e9d35a95eb0dea966f1cbc626924bde1d599a80a8ca165673d39003b3322a7aa70c7e1c9967c7288a139b4cba": exists, upperdir: exists, workdir: exists, same-fs, target: exists, superuser)
`

**Comment by razeh** [comment]
I think this is a duplicate of #584

**Comment by iTrooz** [comment]
The second error is, but the first one (related to privileges to create a mount namespace) is more related to https://github.com/mozilla/sccache/issues/326

**Comment by iTrooz** [comment]
Note that in this scenario (running sccache-dist inside a container), I think `bwrap` may also fail even if creating overlayfs didn't, because bwrap creates a mount namespace in order to pivot_root , which isn't (?) possible in containers
