### ISSUE TITLE
MacOS Sccache v.0.2.8 and greater broken when using Redis cache

### ISSUE THREAD

**Issue by timdaman** [mozilla/sccache#598]
I have discovered a regression in sccache on Mac OS. Starting with sccache v. `0.2.8`
My environment is a freshly installed fully patch Mac OS Mojave, v10.14.6
We use a Redis Based cache supplied by AWS ElasticCache

On an affected version when I run 
  ./sccache-0.2.8-x86_64-apple-darwin/sccache -s
I see the following output
  error: failed to get stats from server
  caused by: Failed to send data to or receive data from server
  caused by: Failed to read response header
  caused by: failed to fill whole buffer

Here is debug logging from the server when the error occurs

  $ SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 RUST_LOG=trace ./sccache-0.2.8-x86_64-apple-darwin/sccache
  TRACE 2019-11-13T04:39:00Z: sccache::cmdline: parse
  DEBUG 2019-11-13T04:39:00Z: sccache::config: Attempting to read config file at "/Users/teamcity/Library/Preferences/Mozilla.sccache/config"
  DEBUG 2019-11-13T04:39:00Z: sccache::config: Couldn't open config file: No such file or directory (os error 2)
  TRACE 2019-11-13T04:39:00Z: sccache::commands: Command::InternalStartServer
  INFO 2019-11-13T04:39:00Z: sccache::server: start_server: port: 4226
  INFO 2019-11-13T04:39:00Z: jobserver::imp: created a jobserver: Client { read: File { fd: 3, read: true, write: false }, write: File { fd: 4, read: false, write: true } }
  TRACE 2019-11-13T04:39:00Z: mio::sys::unix::kqueue: registering; token=Token(18446744073709551615); interests=Readable
  TRACE 2019-11-13T04:39:00Z: mio::poll: registering with poller
  DEBUG 2019-11-13T04:39:00Z: sccache::cache::cache: Trying Redis(redis://REDACTED.cache.amazonaws.com:6379)
  TRACE 2019-11-13T04:39:00Z: sccache::cache::cache: Using Redis: redis://REDACTED.cache.amazonaws.com:6379
  INFO 2019-11-13T04:39:00Z: sccache::server: server started, listening on port 4226
  TRACE 2019-11-13T04:39:00Z: mio::poll: registering with poller
  TRACE 2019-11-13T04:39:00Z: mio::sys::unix::kqueue: registering; token=Token(0); interests=Readable | Writable | Error | Hup
  TRACE 2019-11-13T04:39:00Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:00Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:00Z: tokio_reactor: loop process - 0 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(0)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: sccache::server: incoming connection
  TRACE 2019-11-13T04:39:05Z: mio::poll: registering with poller
  TRACE 2019-11-13T04:39:05Z: mio::sys::unix::kqueue: registering; token=Token(4194305); interests=Readable | Writable | Error | Hup
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable | Writable Token(4194305)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 2 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_io::framed_read: attempting to decode a frame
  TRACE 2019-11-13T04:39:05Z: tokio_io::framed_read: frame decoded from buffer
  TRACE 2019-11-13T04:39:05Z: sccache::server: handle_client
  DEBUG 2019-11-13T04:39:05Z: sccache::server: handle_client: get_stats
  TRACE 2019-11-13T04:39:05Z: mio::poll: registering with poller
  TRACE 2019-11-13T04:39:05Z: mio::sys::unix::kqueue: registering; token=Token(8388610); interests=Readable | Writable | Error | Hup
  TRACE 2019-11-13T04:39:05Z: mio::poll: registering with poller
  TRACE 2019-11-13T04:39:05Z: mio::sys::unix::kqueue: registering; token=Token(12582915); interests=Readable | Writable | Error | Hup
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 0 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Writable Token(8388610)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 0 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Writable Token(12582915)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 0 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Writable Token(8388610)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable | Writable Token(12582915)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 2 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: mio::poll: deregistering handle with poller
  DEBUG 2019-11-13T04:39:05Z: tokio_reactor: dropping I/O source: 3
  TRACE 2019-11-13T04:39:05Z: mio::poll: deregistering handle with poller
  DEBUG 2019-11-13T04:39:05Z: tokio_reactor: dropping I/O source: 2
  ERROR 2019-11-13T04:39:05Z: sccache::server: An error was signalled by the server: unknown command 'CONFIG'
  TRACE 2019-11-13T04:39:05Z: mio::poll: deregistering handle with poller
  DEBUG 2019-11-13T04:39:05Z: tokio_reactor: dropping I/O source: 1
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: event Readable Token(4194303)
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 1 events, 0.000s
  TRACE 2019-11-13T04:39:05Z: tokio_reactor: loop process - 0 events, 0.000s

When I use the default local filesystem caching I don't see any such problems.

**Comment by flxo** [comment]
The redis module runs a `CONFIG GET maxmemory` which seems to be unsupported by aws. Could also be a permission problem. The Redis code in `sccache` could be easily changed to return `None` in case the `CONFIG get maxmemory` in `Storage::max_size` fails, but I don't know if this is mandatory or not.

**Comment by timdaman** [comment]
I did some light poking and it looks like all `CONFIG` commands are unsupported. https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html

**Comment by AJIOB** [comment]
Hi @timdaman,

Is this issue still actual?

**Comment by timdaman** [comment]
I am not sure the bug still exists. The project I was working on ended (or rather was acquired) so I don't have the infrastructure at hand to test anymore. Sorry.

**Comment by Xuanwo** [comment]
Please feel free to open a new issue if anyone else encounters the same problem. Closing this now. Thanks, everyone, for the discussion.
