### ISSUE TITLE
Precompiled binary for ARM?

### ISSUE THREAD

**Issue by syrusakbary** [mozilla/sccache#609]
Currently `sccache` provides useful precompiled binaries for various platforms/chipsets.
Example: https://github.com/mozilla/sccache/releases/tag/0.2.12

We are using it in our `x86_64` servers, and would love to start using it in our `aarch64` ones.

Could be possibe to put a `aarch64` precompiled binary in the Github Release as well?

Thanks!

**Comment by ryankurte** [comment]
Same request but for `armhf` ^_^ `sccache` is super useful for targets like the raspberry pi, but, takes almost literally forever to build on em, so a precompiled binary would be amazing.

**Comment by black-puppydog** [comment]
Bumping this while I'm waiting for sccache to install on my old-but-new-for-me armv7l debian (novena).
Had to do the same the other day on my pinephone. 
Would love to just use a precompiled binary once my MNT Reform arrives. :stuck_out_tongue:

**Comment by ryankurte** [comment]
this appears to only be AARCH64, not armv7 etc.?

**Comment by glandium** [comment]
We can't cater to all niches out of the box. Shipping prebuilt binaries for aarch64 linux is already a stretch, but I figured that since aarch64 is picking up on e.g. AWS, that could be useful. Armv7 is more niche-y. You should be able to cross-compile for armv7 from a more powerful machine. It's worth noting that Rpi3 and newer are aarch64 and are almost 5 years old now.

**Comment by ryankurte** [comment]
> We can't cater to all niches out of the box

yeah this is absolutely a fair tradeoff to make, though i would suggest users of the RPi (and _almost_ any other embedded SBC, though there's still a bit of armv6 around) is a pretty large demographic! (and one disproportionately impacted by loong compile times / that stands to benefit from this in a big way).

it's no huge deal for someone to fork this and run the required CI under their account, or to cross build for themselves, but, it's certainly a better experience if we don't have to ^_^

> It's worth noting that Rpi3 and newer are aarch64 and are almost 5 years old now.

while this is true, raspbian (the standard OS for RPis) is not 64-bit, and the 64-bit OS builds are really _only just_ becoming useable. super hopeful that the state of this is improved by further ARM adoption.
