### ISSUE TITLE
stop unpacking toolchains for every build job

### ISSUE THREAD

**Issue by froydnj** [mozilla/sccache#613]
...unless we're doing this for security reasons, it seems like we ought to be able to unpack the toolchain once, and then mount it into our overlay.  Or does that not work very well with the docker-based builder?

**Comment by chmanchester** [comment]
@froydnj where are you seeing this happen? As far as I can tell we've been re-using unpacked toolchains on disk. Or is this specific to docker?

**Comment by froydnj** [comment]
Oh, indeed.  I was getting confused looking at the code, I think.
