### ISSUE TITLE
Enable local and remote caching

### ISSUE THREAD

**Issue by Githubber2021** [mozilla/sccache#623]
Hi, this is rather a question or feature request and not a bug. I hope it's still fine to post here. Does `sccache` support multilevel caching? Means, first use the local cache and use the remote cache on a cache miss.

I was even thinking about using `ccache` and `sccache` but I think it;s not necessary to explain why this is a "slow" idea. :-)

Thanks for any help!

**Comment by froydnj** [comment]
> Does `sccache` support multilevel caching? Means, first use the local cache and use the remote cache on a cache miss.

There's no support for that right now.  A hybrid cache like you describe would be an interesting addition to `src/cache/*.rs`, though!

**Comment by saschanaz** [comment]
I think this is a good idea; as we are in the COVID crisis I have no access to my office and I'm building Windows - that means I have no cache. This feature will definitely help my WFH.

**Comment by glandium** [comment]
You can use sccache locally. That's the default if you don't configure a remote backend.

**Comment by glandium** [comment]
Duplicate of #30 .
