### ISSUE TITLE
It's cumbersome to update servers to new versions of mozilla sccache

### ISSUE THREAD

**Issue by mstange** [mozilla/sccache#625]
Needing to run `mach bootstrap` requires a source tree on the build machine, or it requires manually copying sccache. This is a barrier to having up-to-date build machines.

For example, Jeff's machine in the Toronto office is one that does not have a source tree, so it's now running an outdated version of sccache because it's too much of a burden to update.

**Comment by froydnj** [comment]
I'm assuming that checking out sccache upstream from the revision that m-c uses is too much as well?

I'm not sure what the ask here is.  `sccache --compile-a-new-version-for-me`?

**Comment by jrmuizel** [comment]
Building sccache upstream hasn't worked for me in the past because of https://github.com/mozilla/sccache/issues/506. Fixing that would be a sufficient solution.

Mach bootstrap is presumably downloading binaries from somewhere. Having a stable url for those would be another decent solution.

**Comment by froydnj** [comment]
OpenSSL mismatches causing problems would be pretty worrisome, but I don't know if your problem was exactly #506 or something else.

Figuring out where `mach bootstrap` gets its binaries is:

1. Find a recent linux64 (non-shippable) job on treeherder.
2. Inspect the task (e.g. https://firefox-ci-tc.services.mozilla.com/tasks/GSKxVIytTF-wob8iCn0Ogw )
3. Click on "See More" for the Task Details.
4. Click on the `toolchain-linux64-sccache` link.
5. Click on "Artifacts" in the Task Run 0 pane.
6. Download the `public/build/sccache.tar.xz` file.

I think there might be some taskcluster magic for getting the sccache toolchain task to get a more stable URL, but you'd have to talk to taskcluster folks about that.

**Comment by chmanchester** [comment]
I'm going to look into the clock skew thing to see if it helps #506. The other part to would be getting the server packaged as a part of releases, which is blocked on removing our `[patch]` section.

**Comment by froydnj** [comment]
> The other part to this would be getting the server packaged as a part of releases, which is blocked on removing our `[patch]` section.

Why is this?  We obviously make releases with `[patch]`; why is building the server dependent on not doing `[patch]`?

**Comment by glandium** [comment]
There are executables on github for each release: https://github.com/mozilla/sccache/releases

**Comment by chmanchester** [comment]
> > The other part to this would be getting the server packaged as a part of releases, which is blocked on removing our `[patch]` section.
> 
> Why is this? We obviously make releases with `[patch]`; why is building the server dependent on not doing `[patch]`?

Entirely non-obviously, we make a workaround branch for each release removing the `[patch]` section because `cargo publish` prohibits it and we only need it for dist things.

**Comment by froydnj** [comment]
> Mach bootstrap is presumably downloading binaries from somewhere. Having a stable url for those would be another decent solution.

You can't do exactly what `mach bootstrap` does, but @glandium notes that you can use https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-sccache.latest/artifacts/public/build/sccache.tar.xz as a stable url to download, which is statically linked with openssl, though not built with musl.

**Comment by froydnj** [comment]
> > 
> 
> Entirely non-obviously, we make a workaround branch for each release removing the `[patch]` section because `cargo publish` prohibits it and we only need it for dist things.

To be clear, this only affects publishing to crates.io, right?  We can still build the server for the prebuilt binaries that we put up here on github, right?
