### ISSUE TITLE
sccache crashes

### ISSUE THREAD

**Issue by nierob** [mozilla/sccache#63]
Sccache is crashing during compilation, back-trace and full log is in the attachment.

It is reproducable by running sccache:
```
env RUST_BACKTRACE=1 SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 SCCACHE_BUCKET=foo SCCACHE_LOG_LEVEL=trace SCCACHE_ENDPOINT=127.0.0.1 ./sccache
```
and compiling Qt5 (dev), the first compilation error is caused by:
```
g++ -c -pipe -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -O3 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Werror -Wno-error=cpp -Wno-error=deprecated-declarations -Wno-error=strict-overflow -D_REENTRANT -fPIC -DQT_NO_LIBINPUT -DQT_NO_TSLIB -DQT_NO_USING_NAMESPACE -DQT_NO_FOREACH -DQT_USE_COMBINED_ALLOCATOR=1 -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DQT_USE_ICU -DQT_HAVE_POLL -DQT_HAVE_PPOLL -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -I/home/nierob/dev/qtbase/src/corelib -I. -Iglobal -I/home/nierob/dev/qtbase/src/3rdparty/harfbuzz/src -I/home/nierob/dev/qtbase/src/3rdparty/md5 -I/home/nierob/dev/qtbase/src/3rdparty/md4 -I/home/nierob/dev/qtbase/src/3rdparty/sha3 -I/home/nierob/dev/qtbase/src/3rdparty/double-conversion/include -I/home/nierob/dev/qtbase/src/3rdparty/double-conversion/include/double-conversion -I/home/nierob/dev/qtbase/src/3rdparty/forkfd -I../../include -I../../include/QtCore -I../../include/QtCore/5.8.0 -I../../include/QtCore/5.8.0/QtCore -I.moc -I/home/nierob/dev/qtbase/mkspecs/linux-g++ -o .obj/qglobal.o /home/nierob/dev/qtbase/src/corelib/global/qglobal.cpp
```

sha1: 8c083dfccc9a6574b60aef964b8212f76ee39bfb
rustc 1.14.0 (e8a012324 2016-12-16)
Linux, Debian 64

[sccache.log.gz](https://github.com/mozilla/sccache/files/734695/sccache.log.gz)

**Comment by luser** [comment]
Thanks for the bug report! It took a bit of poring over the log and the code to find the problem, but I think I found it. Somewhere something is running `sccache --stop-server`:
```
[2017-01-26][15:21:41][DEBUG] handle_client: shutdown
[2017-01-26][15:21:41][TRACE] initiate_shutdown
```

So the server begins to shut down. While that's happening another client request occurs, but there's a logic bug in the ready function:
https://github.com/mozilla/sccache/blob/8c083dfccc9a6574b60aef964b8212f76ee39bfb/src/server.rs#L808
 Since `self.shutting_down` is true, we fall into the else block and fail because `self.token` is not an entry in `self.conns`. Oops!

**Comment by nierob** [comment]
Thanks for the quick answer. Yes, actually I see that the server is switching off itself from time to time, especially if a compilation error occurs. I field to create steps to reproduce that :(. I definitely see 
```make -j 60``` is more fragile then ```make -j1```. I'm using a wrapper to call sccache:
```
#!/usr/bin/env sh
nice -n 20 ~/dev/sccache/target/release/sccache /usr/bin/g++ $@
```

**Comment by luser** [comment]
That change should fix the crash, at least. If something is sending the server shutdown then it's not clear that your build will work reliably! It's possible there's another bug lurking here.

**Comment by nierob** [comment]
Ok, thanks! I'm going to check the new version. How can I see what is sending shutdown signal?

**Comment by luser** [comment]
If an sccache execution hits the `--stop-server` command-handling code it should print "Stopping sccache server...":
https://github.com/mozilla/sccache/blob/bb3ba4a5b18544072e1b4c03fbd26d838529b040/src/commands.rs#L477

If that shows up anywhere in the logs that'd be a red flag. If not, it's possible there's a bug with the network protocol somehow.

**Comment by nierob** [comment]
It doesn't show up.
[sccache.log.gz](https://github.com/mozilla/sccache/files/735158/sccache.log.gz)

**Comment by nierob** [comment]
Ok, I managed to reduce it, but it looks very odd. It seems that icecream is influencing sccache. So I used wrapper only to wrap g++ calls, but I ignored gcc calls which were still redirected through icecream.

after running server: 
```
nice -n 20 env RUST_BACKTRACE=1 SCCACHE_BUCKET=foo SCCACHE_LOG_LEVEL=trace SCCACHE_ENDPOINT=127.0.0.1 ./sccache --start-server
```
It is enough to call: ```/usr/lib/icecc/bin/gcc --blah``` to shutdown the server
