### ISSUE TITLE
building locally on windows spawns window for every cl.exe invocation

### ISSUE THREAD

**Issue by wanderview** [mozilla/sccache#67]
I am trying to use sccache2 on my local windows 10 machine.  I put this in my mozconfig:

```
ac_add_options --with-ccache=sccache.exe
export _DEPEND_CFLAGS='-deps$(MDDEPDIR)/$(@F).pp'
mk_add_options "export CC_WRAPPER="
mk_add_options "export CXX_WRAPPER="
mk_add_options "export COMPILE_PDB_FLAG="
mk_add_options "export HOST_PDB_FLAG="
mk_add_options "export MOZ_DEBUG_FLAGS=-Z7"
```

It seems to be working, but there is a major usability problem.  Every invocation of `cl.exe` spawns a new window.  These appear and disappear rapidly changing the focus constantly.  This makes the machine pretty useless until the compile ends.

**Comment by flxo** [comment]
Build `sccache` with `--features=unstable`. This will make `sccache` spawn the compilation in the background.

**Comment by luser** [comment]
Note that you need to do that with a nightly Rust compiler currently. When Rust 1.16 ships [the feature we're using for that will be stable](https://github.com/rust-lang/rust/issues/37827) and we can just require Rust 1.16 and use it by default.

**Comment by luser** [comment]
Also FYI, [I have a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1318370) to make simply `--with-ccache=path/to/sccache` work in the Firefox build system.

**Comment by wanderview** [comment]
Thanks!  Nice to see this getting some investment.
