### ISSUE TITLE
GCS storage doesn't seem to work

### ISSUE THREAD

**Issue by augustblack** [mozilla/sccache#670]
I do:

export SCCACHE_GCS_BUCKET="<my_bucket>"
export SCCACHE_GCS_KEY_PATH=/path/to/gstorage/json/that/works/with/other/gstorage/apis
export SCCACHE_GCS_RW_MODE=READ_WRITE

I then do:

RUST_LOG=sccache=trace SCCACHE_ERROR_LOG=./sccache_log sccache clang++ test.cpp -c -o test.o

At that point, I don't get any real debugging info on the console from the sccache frontend. I also don't see anything from the sccache server in ./sccache_log.  In fact, nothing is written into sccache_log

And see that I have write errors:

sccache --show-stats                                                                        
Compile requests                      1
Compile requests executed             1
Cache hits                            0
Cache misses                          1
Cache misses (C/C++)                  1
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    1
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.331 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  GCS, bucket: Bucket(<my_bucket>)

I've tried with a 'brew install sccache' on Mac OSX as well as a 'cargo build --features=gcs' on Ubuntu linux.

in both cases, 'sccache --help' says I am using version 0.2.12

I can also confirm that my gstorage json key works with GCS .  I can read and write to GCS with that key using the node npm package.

**Comment by Jake-Shadle** [comment]
GCS was broken during the 0.2.12 release (my fault), it was fixed in #578 so you can try updating to the new 0.2.13 that was just released to see if that fixes GCS for you.

**Comment by augustblack** [comment]
great!  seems to be working now

**Comment by tylerhawkes** [comment]
I just upgraded to 0.2.13 and now gcs is broken for me. It works on 0.2.12. I haven't touched the json file that gcs provided and I'm getting the `invalid RSA key` error. Any ideas why 0.2.12 works for me but 0.2.13 doesn't?

**Comment by Jake-Shadle** [comment]
That's extremely weird, it should be the opposite. You can try getting a log dump via the instructions in the README, or debug the key loading/authentication in src/cache/gcs.rs, to give me a better idea of what could be going wrong, because the version of the code has been working for us for a long time.

**Comment by tylerhawkes** [comment]
I just downloaded a new key and it is working now. I got the other one from a colleague who must have changed it so it would work with 0.2.12. Thanks for the quick response!
