### ISSUE TITLE
Running tests with --target-dir still builds something in the current directory

### ISSUE THREAD

**Issue by glandium** [mozilla/sccache#673]
If I run `cargo test --target-dir /tmp/sccache`, everything is built in `/tmp/sccache`, but when it comes to running the `sccache_cargo` test, somehow it run `cargo build` and that builds in the current directory. 

That seems to be happening on the call to:
```
let sccache = assert_cmd::cargo::main_binary_path().unwrap();
```

**Comment by glandium** [comment]
This could be a bug in `assert_cmd`, but sccache being behind...

**Comment by luser** [comment]
`assert_cmd` uses `escargot` under the hood and it literally does `cargo build` and then looks for the resulting binary path:
https://github.com/assert-rs/assert_cmd/blob/v0.9.1/src/cargo.rs#L183

**Comment by glandium** [comment]
What I meant is that the latest version of assert_cmd doesn't even have this function anymore, and I didn't look what changed.

**Comment by glandium** [comment]
This doesn't happen anymore, so I assume #775 fixed it.
