### ISSUE TITLE
Update to new Cargo.lock format when minimum Rust version is >= 1.41

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#690]
Rust 1.41 shipped with support for [a newer Cargo.lock format](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#less-conflict-prone-cargolock-format) that's less prone to merge conflicts--it omits version numbers from `dependencies` entries, putting them in the individual `package` sections (unless there are multiple versions of a crate present and it needs to disambiguate) and also gets rid of the `metadata` section in favor of putting checksums directly in each `package` section. I updated our in-tree lockfile for our codebase at work and it has made things a bit smoother.

The `cargo lock` subcommand [has a `translate`](https://docs.rs/cargo-lock/4.0.1/cargo_lock/#translate-convert-cargolock-files-between-the-v1-and-v2-formats) feature that can convert an existing lock file, that's what I used.

**Comment by drahnr** [comment]
Just got merged as part of #713
