### ISSUE TITLE
how to package rust toolchain from mac?

### ISSUE THREAD

**Issue by zzl88** [mozilla/sccache#694]
I was trying to play with `sccache-dist` to create a compilation farm for rust. Majority of the users of this farm will be on Mac. I have gone through a lot of documents, but still didn't find how to package rust toolchain on mac to make it work.

I basically `cd ~; tar czvf rust.tar.gz .cargo/bin`, then in  `~/Library/Preferences/Mozilla.sccache/config`, I added this section:
```
[[dist.toolchains]]
type = "path_override"
compiler_executable = "/Users/xxx/.cargo/bin/rustc"
archive = "/Users/xxx/rust.tar.gz"
archive_compiler_executable = "/bin/rustc"
```

However, from sccache server log, I got 
```
TRACE 2020-03-10T12:34:37Z: sccache_dist::build: compile_output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "bwrap: execvp /bin/rustc: No such file or directory\n" }
```

@luser or  any other can help? thanks very much.

**Comment by drahnr** [comment]
The issue here is that you would need to package a cross toolchain from Linux to Mac, since the server currently only supports Linux as OS (namespaces for bubblewrap i.e. cause this).

**Comment by zzl88** [comment]
thanks to @luser , the wrong step above is that i tried to package a mac rust toolchain and run it on Linux. So I packaged a toolchain on Linux, using `sccache --package-toolchain ~/.cargo/bin/rustc rust_toolchain.tar.gz`, then shipped it back to Mac and updated `dist.toolchains`. After restarting sccache on mac, I can find compilation jobs are distributed, although there are some compilation errors...

**Comment by drahnr** [comment]
But don't you need a cross toolchain from Linux to Mac to make this work?

**Comment by zzl88** [comment]
@drahnr how to make a cross toolchain from Linux? Now I got some weird compilation errors, said cannot find crate std... I have tried the `rustc` in my `rust_toolchain.tar.gz`, it can compile helloworld.rs at least.

**Comment by drahnr** [comment]
For once, std is precompiled, as such you would need the std precompiled for OS X to be part of your `rust_toolchain.tar.gz` - I am not sure how to achieve that.
Generally speaking, rustc can have multiple targets, so rustc in itself is a cross compiler. If you depedency has dependencies to any native source you also need to have C/C++ cross compiler handy. 
I recommend reading the full readme of https://github.com/japaric/rust-cross

The first step is to ssh into that linux machine and get cross compilation working to the point where you can execute the remaining executables on your local OS X machine.
Only then I'd suggest you move on to integrating that toolchain with sccache.

Could you also post the exact error messages you see here?

**Comment by zzl88** [comment]
here you go
`
TRACE 2020-03-12T01:10:27Z: sccache_dist::build: compile_output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "{\"message\":\"can\'t find crate for `core`\",\"code\":{\"code\":\"E0463\",\"explanation\":\"\\nA plugin/crate was declared but cannot be   found. Erroneous code example:\\n\\n```compile_fail,E0463\\n#![feature(plugin)]\\n#![plugin(cookie_monster)] // error: can\'t find crate for `cookie_monster`\\nextern crate cake_is_a_lie; // error: can\'t find crate for `cake_is_a_lie`\\n```\\n\\nYou need to link your    code to the relevant crate in order to be able to use it\\n(through Cargo or the `-L` option of rustc example). Plugins are crates as\\nwell, and you link to them the same way.\\n\"},\"level\":\"error\",\"spans\":[{\"file_name\":\"/Users/xxx/.cargo/registry/src/  github.com-1ecc6299db9ec823/fake-simd-0.1.2/src/lib.rs\",\"byte_start\":0,\"byte_end\":0,\"line_start\":1,\"line_end\":1,\"column_start\":1,\"column_end\":1,\"is_primary\":true,\"text\":[{\"text\":\"#![no_std]\",\"highlight_start\":1,\"highlight_end\":1}],\"label\":      \"can\'t find crate\",\"suggested_replacement\":null,\"suggestion_applicability\":null,\"expansion\":null}],\"children\":[{\"message\":\"the `x86_64-apple-darwin` target may not be installed\",\"code\":null,\"level\":\"note\",\"spans\":[],\"children\":[],\"rendered\":    null}],\"rendered\":\"\\u001b[0m\\u001b[1m\\u001b[38;5;9merror[E0463]\\u001b[0m\\u001b[0m\\u001b[1m: can\'t find crate for `core`\\u001b[0m\\n\\u001b[0m  \\u001b[0m\\u001b[0m\\u001b[1m\\u001b[38;5;12m|\\u001b[0m\\n\\u001b[0m  \\u001b[0m\\u001b[0m\\u001b[1m\\u001b[38;5;   12m= \\u001b[0m\\u001b[0m\\u001b[1mnote\\u001b[0m\\u001b[0m: the `x86_64-apple-darwin` target may not be installed\\u001b[0m\\n\\n\"}\n{\"message\":\"aborting due to previous error\",\"code\":null,\"level\":\"error\",\"spans\":[],\"children\":[],\"rendered\":             \"\\u001b[0m\\u001b[1m\\u001b[38;5;9merror\\u001b[0m\\u001b[0m\\u001b[1m: aborting due to previous error\\u001b[0m\\n\\n\"}\n{\"message\":\"For more information about this error, try `rustc --explain E0463`.\",\"code\":null,\"level\":\"failure-note\",\"spans\":[],        \"children\":[],\"rendered\":\"\\u001b[0m\\u001b[1mFor more information about this error, try `rustc --explain E0463`.\\u001b[0m\\n\"}\n" }
`

**Comment by drahnr** [comment]
`thex 86_64-apple-darwin target may not be installed` jumps to my eye, did you install the target with rustup before packaging the toolchain?

**Comment by zzl88** [comment]
nope, will try later. Thanks for your help.

**Comment by zzl88** [comment]
@drahnr after installing `86_64-apple-darwin` target, and re-package rust toolchain. It works perfectly. thanks very much.
