### ISSUE TITLE
How to use sccache to build qt?

### ISSUE THREAD

**Issue by brupelo** [mozilla/sccache#716]
Hi, let's start by saying this looks like an amazing project! ccache's windows ports have always given me problem so this feels like a proper solution.

Here's the thing, I'm on windows and a cold build of https://github.com/qt/qtbase using vs2017 is taking me 25min. How can I use sccache to improve the build times?

And yeah, I've already read the basic usage section ;)

**Comment by timdaman** [comment]
It has been a couple years since I had to handle this problem but I took a quick peek at my old code and I think the trick was to set up QMAKE_CC and QMAKE_CXX in my environment to include sccache. Something like this

```
QMAKE_CC = "/usr/localbin/sccache /bin/clang"
QMAKE_CXX = "/usr/localbin/sccache  /bin/clang++"
```

**Comment by sylvestre** [comment]
Not an issue
