### ISSUE TITLE
No cache hits using vs2017?

### ISSUE THREAD

**Issue by brupelo** [mozilla/sccache#717]
Conside below session:

```
D:\qt\foo>cat foo.c
#include <stdio.h>

void main() {
    printf("hello world");
}

D:\qt\foo>sccache cl foo.c && sccache -s
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

foo.c
Microsoft (R) Incremental Linker Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:foo.exe
foo.obj
Compile requests                      5
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 5
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Local disk: "C:\\Users\\KneDa\\AppData\\Local\\Mozilla\\sccache\\cache"
Cache size                            0 bytes
Max cache size                       10 GiB

D:\qt\foo>sccache cl foo.c && sccache -s
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

foo.c
Microsoft (R) Incremental Linker Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:foo.exe
foo.obj
Compile requests                      6
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 6
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Local disk: "C:\\Users\\KneDa\\AppData\\Local\\Mozilla\\sccache\\cache"
Cache size                            0 bytes
Max cache size                       10 GiB
```

Why are the cache hits 0?

On the other hand, If I do `sccache cl -c foo.c && sccache -s` the cache will be hit... is this intended behaviour?

**Comment by froydnj** [comment]
Yes, this is the intended behavior.  `sccache` doesn’t cache calls that do linking, only calls that do compilation.  The intent is that you will have many `cl -c ...` invocations that can be cached, and one final link step that cannot be cached.

**Comment by brupelo** [comment]
@froydnj Thanks for the confirmation... let me abuse a bit this thread ;) . How can I clear sccache's cache? 

Is there any freenode channel or other place where I can make these type of user questions? Or is it fine to ask here?

Thanks.

**Comment by froydnj** [comment]
> @froydnj Thanks for the confirmation... let me abuse a bit this thread ;) . How can I clear sccache's cache?

The documentation on [local cache storage](https://github.com/mozilla/sccache#local) tells you where the default locations are on various operating systems.  You can just remove the relevant directory.  For other kinds of storage, you'll have to consult the documentation on those storage kinds.

> Is there any freenode channel or other place where I can make these type of user questions? Or is it fine to ask here?

I created `#sccache` on Mozilla's Matrix/Riot instance if you want to ask questions there, but issues here are fine too.

**Comment by brupelo** [comment]
@froydnj Alright, clear as water, awesome. 

Btw... today I've been looking for some sort of utility so I can monitor sccache's stats (similar to unix watch) but unfortunately i haven't found anything yet... I've decided to create my own python utility but the main problem is when I use `cls` it flickers a lot... so If I want to improve that I'll probably need to figure out how use double buffering through win32 api or so. In any case, before going through that whole hazzle, maybe you know something cool so I can monitor in realtime sccache's stats? 

Actually... now I think off... would it be difficult/possible to have an additional argument so you could monitor it using sccache's directly? ie:

- `sccache -s 0.5` would monitor with an interval of 0.5s 
- `sccache -s` will just work as it is right now.

**Comment by brupelo** [comment]
About my previous question... msys' watch plays nicely with sccache. But yeah, the drawback is you still forcing the user to have deps such as msys/cygwin et al... I still think extending `-s` to accept an interval would be pretty cool
