### ISSUE TITLE
File handle to root dir left open

### ISSUE THREAD

**Issue by gilescope** [mozilla/sccache#722]
For my sins I'm building rust in a conda environment. That environment's directory is renamed at the end of the build.

But fails to be renamed as sscache has an open handle to the dir in question: 
C:\conda-bld\my-proj_1586446013252\work

It would be really great if it didn't keep file handles open. You can see it in process explorer that it's kept a handle on the build dir open.

**Comment by glandium** [comment]
Can you check whether https://github.com/glandium/sccache/commit/77c04b847e98a0ccef2041dfd19e67f1a4a5dc95 fixes your issue?
