### ISSUE TITLE
No mention of where you can get pre-built binaries on the readme

### ISSUE THREAD

**Issue by gilescope** [mozilla/sccache#727]
It would be great if we didn't need to build every rust tool from source every time (to reduce global warming as well as to save time and have things just work more of the time).

Could the readme point to where the tool is already binary packaged?

**Comment by glandium** [comment]
https://github.com/mozilla/sccache/releases
I don't know why there aren't Windows binaries for the latest version like for the version before.
@froydnj , do you know?

**Comment by gilescope** [comment]
Sorry for some reason didn't think to look at https://github.com/mozilla/sccache/releases . D'oh! 
- it's also seems to be distributed in a few other places like https://snapcraft.io/sccache for example.

**Comment by froydnj** [comment]
> I don't know why there aren't Windows binaries for the latest version like for the version before.
> @froydnj , do you know?

Windows CI was busted when that release was made.

**Comment by luser** [comment]
Putting a link to the releases page in [the installation section](https://github.com/mozilla/sccache#installation) of the README would be a great idea, I'm not sure why we never did that! Looking it over now I'd probably rearrange the README so Installation is the first section after the intro followed by the Build / Build Requirements sections. Anecdotally many other software READMEs will list installation options with the last one being "you can also build from source by following these directions".
