### ISSUE TITLE
Clarify which Rust version is required

### ISSUE THREAD

**Issue by est31** [mozilla/sccache#73]
In `.travis.yml` I see that testing is done on Rust 1.13, while the README says that Rust 1.12 is required.

So there are two possible cases now:

* README is wrong, and indeed Rust 1.13 is required. Then it should be changed.
* README is correct, and Rust 1.12 suffices. Then however testing should be done on 1.12 to make sure nothing regresses.

**Comment by luser** [comment]
We do require 1.13 since the tokio refactor landed (it added usage of the `?` operator). We just missed updating the readme, apparently. Thanks for noticing!

**Comment by est31** [comment]
Thanks for the quick fix!
