### ISSUE TITLE
Rust 1.43 provides a handy way to get the binary path for tests

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#730]
I saw this bit in [the Rust 1.43 release notes](https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html#new-cargo-environment-variable-for-tests):

> This is easiest to explain by example: let's say we're working on a command line project, simply named "cli". If we're writing an integration test, we want to invoke that cli binary and see what it does. When running tests and benchmarks, Cargo will set an environment variable named `CARGO_BIN_EXE_cli`, and I can use it inside my test:
> ```rust
> let exe = env!("CARGO_BIN_EXE_cli");
> ```
> This makes it easier to invoke `cli`, as we now have a path to it directly.

The integration tests currently use `escargot` to invoke sccache:
https://github.com/mozilla/sccache/blob/06584b66069f3a8c50fb5cceca05e7fdc2c28a39/tests/sccache_cargo.rs#L33
https://github.com/mozilla/sccache/blob/master/tests/harness/mod.rs#L121-L156

I think it'd be straightforward to swap that out for this much simpler piece. A simple strategy to get some benefit without requiring Rust 1.43 right away would be to simply use the environment variable if it's set and fall back to the current implementation. When 1.43 becomes the minimum supported Rust version in the future you could drop the `escargot` dependency and just rely on the env var.

**Comment by nnethercote** [comment]
Did #775 fix this? It removed the use of `escargot`.

**Comment by glandium** [comment]
I think as far as we're concerned, we're good here now.
