### ISSUE TITLE
Request: fallback to compile

### ISSUE THREAD

**Issue by LuisAyuso** [mozilla/sccache#737]
First of all, I would like to say that this is a great project, I enjoy it very much.

I was wondering if it would be possible to add an option to compile the code in case the cache server is not available.

I have little experience with rust, and I could attempt to implement this feature, but I may need some directions on what to look for. 

Cheers!

**Comment by glandium** [comment]
Can you describe your problem, because it should fallback to compile already. But maybe some backend don't work well when the backend doesn't respond at all rather than responds that there is nothing available?

**Comment by glandium** [comment]
I'll close this for now, as without feedback, it's not actionable. Please feel free to reopen if you have more information to provide.

**Comment by Kinrany** [comment]
My use case: falling back to using local cache when connection to Redis fails.

Not sure if that's what OP meant, but found this issue while searching for similar ones 🙂
