### ISSUE TITLE
Dynamically adding version info to the binary in a cache friendly way

### ISSUE THREAD

**Issue by therealbnut** [mozilla/sccache#740]
Hey,

Thanks for such a great tool! I've just started using sccache, and I'm wondering what is the most sccache friendly way to bake version information into my rust binary?

While I've got your attention: How do I debug what sccache is doing?

--- 

This is part of an automated build so I'd prefer to continue to automatically get the latest version info as described below.

Details:
 * I currently use a custom `env!("GIT_SHORT_REF")` to supplement my binary's version information.
 * This is generated dynamically by `build.rs` file, and changes with every commit.
 * Your documentation leads me to believe that this may not change the cache hash.
 * I'm happy to pass an argument to cargo, or have a data file and use `std::include!(..)`.
 * Only `main.rs` directly depends on this environment variable.
 * I would prefer not to have to modify a checked-in source file to get this behaviour.
 * I'm not very familiar with ccache, and couldn't get anything working looking at its documentation.
 * I'm not sure how to debug when sccache has a cache miss.

---

The ccache docs say that pch files are expanded and their output is used to generate the hash. Do you use [cargo-expand](https://github.com/dtolnay/cargo-expand) or similar to check for changed macros in a similar way? Perhaps macro hygiene make that too expensive to be worth it.

My issue seemed related to these, but perhaps I have fewer constraints:
 * add ability to skip caching/distributing for certain files https://github.com/mozilla/sccache/issues/675
 * [dist] failure when build.rs or procmacro depend on externalities https://github.com/mozilla/sccache/issues/676

Thank you!

**Comment by froydnj** [comment]
> Thanks for such a great tool! I've just started using sccache, and I'm wondering what is the most sccache friendly way to bake version information into my rust binary?

The best way is to make sure that your `env!("GIT_SHORT_REF")` macro lives in the crate for the program itself and not in any dependent crates, since `sccache` doesn't cache compilations that produce binaries.  It sounds like you're doing that already?

**Comment by therealbnut** [comment]
@froydnj thanks for the reply!

Yes I am doing that, I just wasn’t sure whether I could rely on `env!` changes being reliably picked up by sccache. It sounds like it will be though?

**Comment by froydnj** [comment]
> @froydnj thanks for the reply!
> 
> > make sure that your env!("GIT_SHORT_REF") macro lives in the crate for the program itself
> 
> Yes I am doing that, I just wasn’t sure whether I could rely on `env!` changes being reliably picked up by sccache. It sounds like it will be though?

They won't in general, cf:

https://github.com/mozilla/sccache/blob/5da0707c0596e990d99470ce45af3dbb1018495f/src/compiler/rust.rs#L1354-L1375

But since the process is:

1. Determine crate type to determine whether we can cache:

https://github.com/mozilla/sccache/blob/5da0707c0596e990d99470ce45af3dbb1018495f/src/compiler/rust.rs#L1051-L1065

1a. If we cannot cache, then compile every time.
2. Determine hash of input for caching (the above bit about environment variables)
3. Retrieve from cache or compile fresh.

compiling a binary's crate always hits step 1a above, and so you don't have to worry about the incomplete determination of what environment variables apply to the compilation in step 2.

**Comment by therealbnut** [comment]
@froydnj awesome, thank you for such a detailed and well referenced reply! I’m happy to close this issue.
