### ISSUE TITLE
Indicate which artifacts were fetched from cache when running cargo build

### ISSUE THREAD

**Issue by Veetaha** [mozilla/sccache#746]
This is a feature request.
It would be awesome to see during the compilation which particular artifacts were fetched from cache. Ideally, it would be cool to inject it right in the cargo output like so:
```log
$ cargo build
   Compiling unicode-xid v0.2.0 (using cache)
   Compiling proc-macro2 v1.0.12
   Compiling cfg-if v0.1.10
   Compiling syn v1.0.19 (using cache)
   Compiling libc v0.2.69 (using cache)
   Compiling autocfg v1.0.0 (using cache)
   Compiling lazy_static v1.4.0
   Compiling serde v1.0.106
``` 
where the artifacts which were fetched from cache are marked with `(using cache)`.

I believe this would be super-hard/impossible to implement so a more realistic approach is 
to print the overall statistic in percentage (`short`) with an optional list of artifacts that were fetched from the cache (`full`).
This behavior can be controlled by some env variable like `SCCACHE_DUMP_STATS=short|full`.

Thanks for your contribution to the community!

**Comment by luser** [comment]
I don't believe this is possible, unfortunately, since sccache simply gets invoked as a compiler wrapper by cargo and doesn't have any way to interface to cargo beyond producing stdout/stderr like rustc does.

**Comment by froydnj** [comment]
Echoing @luser, I don't think this is possible without deeper integration between `sccache` and `cargo`.  If you wanted to engage the `cargo` team about what an interface for producing extra output from a compiler wrapper would look like, that would be the first step towards doing this.

**Comment by glandium** [comment]
I'll close this, because it's not actionable in sccache.
