### ISSUE TITLE
handle panics in the (local) server by failing the compilation rather than hanging

### ISSUE THREAD

**Issue by froydnj** [mozilla/sccache#756]
I only found #755 because I had a server running in a separate window.  If I hadn't been running the server in a place I could see its output, I would just have seen `sccache` hang.  It would be better to somehow return an error that was visible to the user.

**Comment by luser** [comment]
I'm not sure there's a straightforward way to do this given the extensive use of futures. If it was a single-threaded computation you could wrap the whole thing in `std::panic::catch_unwind`. I'd suggest instead auditing the codebase for usage of `unwrap` / `expect` and removing any that snuck in.
