### ISSUE TITLE
Consider moving log configuration to a dedicated env var

### ISSUE THREAD

**Issue by Nemo157** [mozilla/sccache#810]
Currently when running `RUST_LOG=debug cargo run` to get debug output from the target executable you also receive extra log info from `sccache`. Cargo and rustc avoid this by using custom `CARGO_LOG` and `RUSTC_LOG` variables respectively. It would be useful if `sccache` also moved to something like `SCCACHE_LOG` to avoid interference with projects using the `env_logger` default variable.

**Comment by froydnj** [comment]
I'm not sure what the use case is here; are you saying that when you `RUSTC_WRAPPER=/path/to/sccache RUST_LOG=debug cargo run` and things need to be rebuilt, you're getting debug logging from `sccache` as well?

Is `RUST_LOG=${TARGET_EXE_NAME}=debug` not sufficient for this purpose?

**Comment by Nemo157** [comment]
> [...] you're getting debug logging from sccache as well?
Exactly.

`RUST_LOG=${TARGET_EXE_NAME}=debug` will only print debug information from the module-tree `${TARGET_EXE_NAME}`. If for example I'm debugging something Tokio related in my application I would use `RUST_LOG=tokio=debug`, but since `sccache` also uses `tokio` that will still print debug output from `sccache` as well.

**Comment by froydnj** [comment]
> `RUST_LOG=${TARGET_EXE_NAME}=debug` will only print debug information from the module-tree `${TARGET_EXE_NAME}`. If for example I'm debugging something Tokio related in my application I would use `RUST_LOG=tokio=debug`, but since `sccache` also uses `tokio` that will still print debug output from `sccache` as well.

Thanks for the explanation!  I agree this would be useful.
