### ISSUE TITLE
README has wrong RUSTC_WRAPPER instructions?

### ISSUE THREAD

**Issue by ecton** [mozilla/sccache#812]
In the README, there's a section that reads:

> Alternatively you can use the environment variable `RUSTC_WRAPPER`:
> 
> ```bash
> RUSTC_WRAPPER=/path/to/sccache cargo build
> ```

A few lines above, it shows that the rustic wrapper within Cargo.toml is just the path to the executable. Additionally, [The Cargo Book's section "Build Cache"](https://doc.rust-lang.org/cargo/guide/build-cache.html) mentions the environment variable only containing the path to the sccache executable.

Is this just a typo or is there a reason to try to include cargo build in that environment variable? For what it's worth, I had to just specify the path to cache, and not include "cargo build" in the environment variable. I'm assuming this is just a documentation issue, but I didn't want to submit a PR due to this just being the first time I've used the tool -- and it's possible I just didn't understand something here!

**Comment by froydnj** [comment]
The intent of the documentation is that `RUSTC_WRAPPER=/path/to/sccache`, `cargo`, and `build` are all separate tokens on the command line; if the intent was that `RUSTC_WRAPPER` was the actual string `/path/to/sccache cargo build`, it would have been written `RUSTC_WRAPPER="/path/to/sccache cargo build"`.

I can see how the documentation could be clarified, perhaps by saying, "Alternatively, you can use the environment variable `RUSTC_WRAPPER` when you invoke `cargo build`".  Do you think that would be clearer?  If so, could you please submit a patch to that effect?

**Comment by ecton** [comment]
This is what I get for trying to tweak my CI processes before my first cup of coffee. I was in env-file and env-parameters mode so much I didn't think that the example shown was of a command invocation not of an example of what you'd place in an env file.

Honestly, I think I should have known the difference. However, if we assume other people might make the same mistake as me, I think your revised language might have helped me break out of my mindset I was in when reading that example.

Thank you for the explanation and suggestion!

**Comment by glandium** [comment]
I split the command in the README in 2832187ae75a6fe3a076b866ffa43cdb30073a7e. Hopefully, this clarifies things.
