### ISSUE TITLE
Build still takes a long time even with sccache

### ISSUE THREAD

**Issue by Timmmm** [mozilla/sccache#814]
I have a program that takes about 1 minute to build. With `sccache` it still takes around 40 seconds even if I don't change anything. Is that expected? Here is the timing report, clean and then cached. It does seem to cache a lot of things, but not `serde-regex`, or two of my crates (`file-loaders` and `backend`).

![empty_cache](https://user-images.githubusercontent.com/376842/88171834-ed8d5c80-cc17-11ea-8120-70191a6a7705.png)
![full_cache](https://user-images.githubusercontent.com/376842/88171859-f7af5b00-cc17-11ea-9914-5d0f2c97b686.png)

I filtered out <1.5s crates in the first one and and <1s in the second.

Here are the stats after one cached build:

```
$ sccache --show-stats
Compile requests                    357
Compile requests executed           244
Cache hits                           67
Cache hits (Rust)                    67
Cache misses                        177
Cache misses (Rust)                 177
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 113
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           1.324 s
Average cache read hit            0.019 s
Failed distributed compilations       0

Non-cacheable reasons:
crate-type                          102
-                                     7
incremental                           4

Cache location                  Local disk: "/Users/timh/Library/Caches/Mozilla.sccache"
Cache size                          112 MiB
Max cache size                       10 GiB
```

This is all in debug mode. Weirdly, in release mode `file_loaders` does get cached:

![release_cached](https://user-images.githubusercontent.com/376842/88173338-4c53d580-cc1a-11ea-8341-5e202f914932.png)

How can I figure out why these crates aren't being cached? Is there some kind of log file?

**Comment by Timmmm** [comment]
Ah I found the logging options in the readme, and with `RUST_LOG=debug` it tells me this for `file_loaders` in debug mode:

    DEBUG 2020-07-22T12:01:18Z: sccache::server: parse_arguments: CannotCache(incremental): ["--crate-name", "file_loaders", "--edition=2018" ...

`backend` cannot be cached because it is a `bin` crate, and `serde_derive` can't be cached because it is a proc macro. That sucks. :-/

**Comment by luser** [comment]
> It does. :( It's possible we could give `sccache` some deep knowledge of how things were linked and speed things up (after all, you are probably compiling with the same toolchain all the time), but I think that might be more complexity than it's worth.

There's [a proposed Rust feature](https://github.com/rust-lang/rust/issues/64191) that could make this better.

**Comment by Timmmm** [comment]
> I do like the graphs, though; what did you use to generate them?

You just run `cargo build -Z timings` (I can't remember but it might need nightly) and it generates an html file.

**Comment by Timmmm** [comment]
By the way, regarding the system linker, would it help if Rust used LLVM's LLD linker?
