### ISSUE TITLE
cannot see s3 debug info

### ISSUE THREAD

**Issue by ltamaster** [mozilla/sccache#832]
I cannot see S3 debug info.
I got `Cache write errors` data using `sccache --show-stats` but I cannot see any log related with the failure.
I tried with `RUST_LOG=sccache=trace`

I am using the following env vars:
```
RUSTC_WRAPPER = "/usr/local/cargo/bin/sccache"
RUST_LOG="sccache=info"
SCCACHE_BUCKET="tmp"
SCCACHE_S3_USE_SSL="true"
```
Thanks

**Comment by Dushistov** [comment]
I suppose you need SCCACHE_LOG: https://github.com/mozilla/sccache/commit/182c59ed6039fdbad3522b211d90c76acf8baa6f if you are using master.

**Comment by ltamaster** [comment]
I tried that without luck
I am using this version `sccache 0.2.13` working with a docker container (`rust` image)

Thanks

**Comment by Xuanwo** [comment]
Please try the latest version sccache (v0.4.0-beta.6), we will report errors if s3 setup incorrectly.
