### ISSUE TITLE
Feature: Add Wasabi Bucket as Cache Option

### ISSUE THREAD

**Issue by BenD0G** [mozilla/sccache#838]
Hi 😄

I would like to add [Wasabi](https://wasabi.com/) buckets as a storage option.

Their buckets are fully-S3 compliant, and so I believe Wasabi buckets should function here exactly as S3 buckets currently do.

I'm happy to do the work and open a PR, but would like to get your opinion on whether this should be added as a totally separate cache type (either copy-pasting or importing some of the `simples3` stuff), or by shoehorning it in to the existing S3 code.

(I've had a dig through the code but am no expert, so happy for any other guidance!)

**Comment by froydnj** [comment]
> I'm happy to do the work and open a PR, but would like to get your opinion on whether this should be added as a totally separate cache type (either copy-pasting or importing some of the `simples3` stuff), or by shoehorning it in to the existing S3 code.

I think it'd be better to expose it as a separate cache type.

**Comment by Zulgrib** [comment]
If you're still working on it, having it added as a s3 compatible backend next to the actual S3 would be great
This would allow any S3 compatible storage to be used and reduce costs for lot of organizations.

**Comment by BenD0G** [comment]
I'm aiming to work on this over the next few days - unfortunately I became quite busy after initially proposing to do this!
I agree with you, @Zulgrib, and will design accordingly 😄

**Comment by BenD0G** [comment]
After playing around, I discovered that the latest release (0.2.13) actually already supports S3-compliant backends. I was able to upload to a Wasabi storage bucket by setting the following variables (yours may differ) and restarting the server:
```
export AWS_ACCESS_KEY_ID=<key generated from Wasabi console>
export AWS_SECRET_ACCESS_KEY=<key generated from Wasabi console>
export SCCACHE_BUCKET=<name of wasabi bucket, e.g. bend0g-test-bucket>
export SCCACHE_ENDPOINT=s3.eu-central-1.wasabisys.com
# Not sure the next one is necessary
export SCCACHE_S3_USE_SSL=true
```
I'm going to close this issue, but happy to reopen if anyone feels the S3-compliance is somehow incomplete!
