### ISSUE TITLE
-fsanitize-blacklist does not work correctly with relative paths

### ISSUE THREAD

**Issue by luca020400** [mozilla/sccache#843]
I'm trying to replace ccache with sccache in the AOSP build system but I'm facing a few errors
This is the first issue that stems from using the `-c` flag of clang enabling the use of the integrated clang assembler

```
cat foo.cpp              
#include <stdlib.h>
void bad_foo() {
  int *a = (int*)malloc(40);
  a[10] = 1;
}
int main() { bad_foo(); }
```

```
cat blacklist.txt 
# Ignore reports from bad_foo function.
fun:bad_foo
```

```
sccache clang++ -c -fsanitize=address -fsanitize-blacklist=blacklist.txt foo.cpp
sccache: encountered fatal error
sccache: error : Failed to open file for hashing: "blacklist.txt"
sccache:  cause: Failed to open file for hashing: "blacklist.txt"
sccache:  cause: No such file or directory (os error 2)
```

The same command without `-c` works properly
```
sccache clang++ -fsanitize=address -fsanitize-blacklist=blacklist.txt foo.cpp
```

**Comment by froydnj** [comment]
Are you attempting to use `sccache-dist`?

**Comment by luca020400** [comment]
I'm using `sccache` as a local cache, if that's what you're asking

**Comment by froydnj** [comment]
That wasn't, but I think your answer tells me what I need to know.  The temporary workaround is to pass an absolute path for `-fsanitize-blacklist=`.
