### ISSUE TITLE
Distributed compilation jobs fail because scheduler thinks that assign_job request times out

### ISSUE THREAD

**Issue by mstange** [mozilla/sccache#846]
I am trying to set up a fresh Ubuntu machine to use as an sccache scheduler and server, at home. The sccache client is running macOS.

However, my distributed compilations fail.

Configs and logs: https://gist.github.com/mstange/87ce61bb334b5d058f7370bb65d19c72

The most important line seems to be this one, from the scheduler:

```
 WARN 2020-09-12T01:07:05Z: sccache::dist::http::server: Res 2 error: assign job failed, job un-assigned from the server, caused by: POST to scheduler assign_job failed, caused by: https://192.168.2.146:10500/api/v1/distserver/assign_job/0: timed out
```

This is surprising to me because, on the server side, we have this:

```
TRACE 2020-09-12T01:06:35Z: sccache::dist::http::server: Req 0 (192.168.2.146:60808): Request { method: "POST", url: "/api/v1/distserver/assign_job/0", headers: [("authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqb2JfaWQiOjB9.O2mnEyB-wd-i4dsa2BT-prgjjmlaO5OcA-CviOsElb4"), ("content-type", "application/octet-stream"), ("content-length", "72"), ("user-agent", "reqwest/0.9.24"), ("accept", "*/*"), ("accept-encoding", "gzip"), ("host", "192.168.2.146:10500")], https: false, remote_addr: V4(192.168.2.146:60808) }
TRACE 2020-09-12T01:06:35Z: sccache::dist::http::server: Req 0: assign_job(0): Toolchain { archive_id: "4b786bb365a81ea2336a3e197ac04b278c783131fc50f6060a53ccaf27d5daa3" }
TRACE 2020-09-12T01:06:35Z: sccache::dist::http::server: Res 0: Response { status_code: 200, headers: [("Content-Type", "application/octet-stream")] }
```

which indicates to me that the server is replying (or at least attempting to reply) with status 200.

What should I do next in order to debug this?

**Comment by denschub** [comment]
Note that this seems to be something introduced "recently". While I cannot exactly say when it broke, I had a previously working setup and am now running into the same issue.

**Comment by froydnj** [comment]
> Note that this seems to be something introduced "recently". While I cannot exactly say when it broke, I had a previously working setup and am now running into the same issue.

If you revert bdaa65aead6053ff707b1c20320e213d29d4bb55, do things start working again?

**Comment by mstange** [comment]
I'm giving this a try now.

**Comment by mstange** [comment]
I can confirm that this issue does not occur on 182c59ed6039fdbad3522b211d90c76acf8baa6f, the changeset before the tiny-http update.

**Comment by dholbert** [comment]
Seems like we should get @philn's attention here, then (and consider rolling back that update for now, I guess?)

**Comment by dholbert** [comment]
Note: I ran into this on Ubuntu as well (version 20.04 in my case), and it happens for me even in the relatively-straightforward configuration of scheduler/server/client all running on the same machine.

**Comment by philn** [comment]
Can you rollback the update please? I won't have time to work on this, my apologies.

**Comment by mstange** [comment]
Fixed by #852. Thanks!

**Comment by dholbert** [comment]
I've started hitting this issue again, starting with the release of 0.2.14 (using Ubuntu server & builders & clients, which were working fine before getting the update via mach bootstrap today). 

I wonder if it's due to https://github.com/mozilla/sccache/commit/a6a8becb842198e2d04302bfdacdf1c66740a7b0 which removed a `patch` section that had been restored in the pull request that had fixed this bug?  (A `patch` section that cherrypicked a particular tiny-http revision, I think...)

**Comment by dholbert** [comment]
CC @glandium

**Comment by glandium** [comment]
The releases to crates.io have to unpatch tiny-http because that's not allowed on crates.io, unfortunately. #912 will have to fix this.
