### ISSUE TITLE
New release timing, and future ownership of the project after events at Mozilla Corporation

### ISSUE THREAD

**Issue by baybal** [mozilla/sccache#848]
Hello,

What is going on with the next release? What is the ownership status of the project? Are any of the past paid sccache devs departing from the project? How much Mozilla can commit to sccache development in the future?

**Comment by glandium** [comment]
All the people involved in sccache have left Mozilla except for myself (to clarify: they were not laid off). They are mostly inactive in terms of development, although you'll sometimes see some of them comment here and there. As for myself, I was busy with a large number of other things.
Mozilla is still using sccache as a shared cache, and is still interested in making sccache-dist a viable option for its developers. New people are joining the project,  but it'll take some time to get up to speed.
In the meantime, I've gone through all PRs and recent issues, picked what I felt needed to be merged/addressed for a release and cut the 0.2.14 this morning. I'll do another sweep for another release, but the top priority now is to switch CI off Travis, which should come soon.
Hope this helps.
