### ISSUE TITLE
Support arbitrary rustc drivers

### ISSUE THREAD

**Issue by bjorn3** [mozilla/sccache#861]
Currently rustc and clippy-driver are hardcoded. It would be nice if arbitrary rustc drivers would be supported. This includes [`cargo-miri rustc`](https://github.com/rust-lang/miri), [`cg_clif`](https://github.com/bjorn3/rustc_codegen_cranelift) and any other program that has a rustc compatible command line interface. One way would be to first check for a C compiler and if the output is `error: Unrecognized option: 'E'` instead attempt to detect a rustc compiler.

cc https://github.com/bjorn3/rustc_codegen_cranelift/issues/1091

**Comment by bjorn3** [comment]
FYI https://github.com/bjorn3/rustc_codegen_cranelift/pull/1225 made this issue obsolete for cg_clif. Sccache doesn't fully work with cg_clif yet due to `--sysroot` not being allowed. I think this issue should be kept open for other rustc drivers.

**Comment by bjorn3** [comment]
Flowistry also hit this: https://github.com/willcrichton/flowistry/issues/18 Flowistry is a rust analysis tool which has an executable exposing a commandline interface identical to rustc.

**Comment by drahnr** [comment]
I think having an environment as a shortcut until it makes it as hardcoded variant into the sccache code base, might make sense

`SCCACHE_ALT_IMPL="cranelift=rustc;miri=gcc"`

**Comment by bjorn3** [comment]
That would be perfect! Tools could set/extend that env var unconditionally as it doesn't do anything anyway when sccache isn't used.
