### ISSUE TITLE
Please document how to setup SCCACHE_GCS_CREDENTIALS_URL

### ISSUE THREAD

**Issue by nehaljwani** [mozilla/sccache#870]
Mozilla uses it like this:

```
export SCCACHE_GCS_CREDENTIALS_URL=http://taskcluster/auth/v1/gcp/credentials/$SCCACHE_GCS_PROJECT/${bucket}@$SCCACHE_GCS_PROJECT.iam.gserviceaccount.com
```

How does one setup this end point for themselves? An example would be nice! :)

**Comment by sylvestre** [comment]
I think it has been fixed with
https://github.com/mozilla/sccache/pull/1108/files
