### ISSUE TITLE
create a new release

### ISSUE THREAD

**Issue by drahnr** [mozilla/sccache#876]
A lot of features and bugfixes went in since February / v0.2.13 - it would be about time to create a new release. 

I've encountered 3 issues that were opened, just because the latest release does not include #666

**Comment by TriplEight** [comment]
Yes, please, there are a number of reasons we have to build `sccache` from master instead of just installing it.

**Comment by drahnr** [comment]
Currently consolidating a lot of PRs in https://github.com/paritytech/sccache

**Comment by Firstyear** [comment]
To be clear @drahnr is this because the mozilla/sccache repo is "un-maintained" or is this a fork?

**Comment by drahnr** [comment]
The goal would be to upstream all changes eventually, but given the current state of sccache development activity and communication, I am a bit doubtful. Time will tell. If the situation does not change, it will become a fork.

**Comment by glandium** [comment]
0.2.14 was released moments ago.
