### ISSUE TITLE
Support Rust compilations that link against native libraries

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#88]
I'm punting on this for now by returning `CompilerArguments::CannotCache` for any compilation containing `-l`, so it shouldn't break anything, sccache will just refuse to cache any compilations that would link native libraries.

The complicated part is that we would have to replicate the linker's search strategy to fix this. If we can get rustc to tell us what linker it would use, maybe the best way to do that would be to interrogate it as to what its search paths are?

**Comment by alexcrichton** [comment]
I think this may actually be relatively easy in practice. If we assume that sccache isn't handling linker invocations yet (e.g. creation of dylibs, cdylib, executables, etc), then all we're left with is rlibs. Rlibs in general don't process `-l` flags except for `-l static=foo`, and those have a pretty naive lookup strategy (easy to reimplement).

Punting for now seems good regardless.

**Comment by Dushistov** [comment]
It would be great to have caching of code that link againts with native.

For example if I rebuild my code twice with sccache enabled, the second time I got:

 Finished release [optimized + debuginfo] target(s) in 480.33 secs

So source code not changed, it already build once and sccache cache all compiler invocation,
but still it takes 480 seconds, stats:
```sh
evgeniy@localhost ~ $ sccache -s
Compile requests                217
Compile requests executed       136
Cache hits                      110
Cache misses                     26
Cache timeouts                    0
Forced recaches                   0
Cache write errors                0
Compilation failures              0
Cache errors                      0
Non-cacheable compilations        0
Non-cacheable calls              16
Non-compilation calls            65
Unsupported compiler calls        0
Average cache write           0.003 s
Average cache read miss      44.699 s
Average cache read hit        0.001 s
Cache location             Local disk: "/home/evgeniy/.cache/sccache"
Cache size                      924 MiB
Max cache size                   10 GiB
```

clang-sys, rusqlite and others require a lot of cpu power.

**Comment by luser** [comment]
> I think this may actually be relatively easy in practice. If we assume that sccache isn't handling linker invocations yet (e.g. creation of dylibs, cdylib, executables, etc), then all we're left with is rlibs. Rlibs in general don't process -l flags except for -l static=foo, and those have a pretty naive lookup strategy (easy to reimplement).

I don't think I read this carefully at the time, but I think supporting just `-l static=foo` as a first pass would be a good step.

**Comment by alexcrichton** [comment]
Ah yeah so to clarify, if you're only caching rlibs (which I think is correct for now) then you should be able to cache all `-l` flags. Most of them only get encoded into the metadata (none of them acted on) *except* the `static` kind. That means you'll need to hash the set of flags (and the order they show up in) but you won't need to do anything else except for `static` kind libs. For that I'll comment on https://github.com/mozilla/sccache/issues/123

**Comment by luser** [comment]
We do not have anything to prevent caching non-rlib compilations, so I filed https://github.com/mozilla/sccache/issues/124 .
