### ISSUE TITLE
dist-client does not print directory path when cache dir creation fails.

### ISSUE THREAD

**Issue by Firstyear** [mozilla/sccache#885]
```
ERROR 2020-11-19T01:17:29Z: sccache::server: Error: failure during dist client creation
Caused by: failed to initialise client toolchains
Caused by: failed to create top level toolchain cache dir
Caused by: Permission denied (os error 13)
```

This menas I don't know where to correct to fix up to allow the toolchain dir to be created.

It would also be good to highlight in the quickstart that the cache_dir parameter is able to influence this.

**Comment by drahnr** [comment]
You might want to checkout paritytech/sccache

**Comment by drahnr** [comment]
Or particularly https://github.com/paritytech/sccache/pulls/10
