### ISSUE TITLE
sccache v0.2.13 fails when `-Z unstable-options` are specified

### ISSUE THREAD

**Issue by SomeoneToIgnore** [mozilla/sccache#889]
Minimal example:
* use nightly rustc: `docker run -it --rm rustlang/rust:nightly bash`
* install sccache: `rustup toolchain install 1.47.0 && cargo +1.47.0 install sccache` (I have to use 1.47 due to https://github.com/mozilla/sccache/issues/887)
* create a dummy project: `USER=test-user cargo new --bin test-project && cd test-project`
* run `cargo clean && cargo clippy -Z unstable-options` it works
* run `cargo clean && RUSTC_WRAPPER="/usr/local/cargo/bin/sccache" cargo clippy -Z unstable-options`

Expected: it works too.
Actual: error,

```
error: failed to execute compile
caused by: Compiler not supported: "error: Unrecognized option: \'E\'\n\n"
error: could not compile `test-project`
```

**Comment by SomeoneToIgnore** [comment]
Seems to work on current master

**Comment by glandium** [comment]
Closing per https://github.com/mozilla/sccache/issues/889#issuecomment-732821720
