### ISSUE TITLE
sccache server shutting down even after using SCCACHE_IDLE_TIMEOUT=0

### ISSUE THREAD

**Issue by jaglinux** [mozilla/sccache#904]
In our project build, there is a stage where sccache linked compiler is not used for over 30 minutes. During this time, sccache server shuts down. After the delay, when the sccache linked compiler is invoked, compilation fails with sccache errors.
SCCACHE_IDLE_TIMEOUT=0 is used and sccache version is 0.2.6.
sccache: error : failed to spawn
signature : sccache: cause: No such file or directory

The sccache stop server is called after the whole build is finished. But "INFO:sccache::server: ok, fully shutting down now
" appears during the build stage where its idle.

**Comment by glandium** [comment]
0.2.6 is rather old. Can you try with the latest version or, even better, current master?

**Comment by jaglinux** [comment]
Sure, I will try with latest version.

**Comment by luser** [comment]
> Should I be using SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 so that sccache is in foreground and alive always ?

This is pretty much never what you want, but you could try making your CI do something like:

```
# terminate any existing sccache instance
sccache --stop-server
SCCACHE_IDLE_TIMEOUT=0 sccache --start-server
```

To ensure that you're starting a fresh server invocation with the right settings.

**Comment by glandium** [comment]
I'll close, assuming this works with newer versions. Please feel free to reopen if you can reproduce with the latest.

**Comment by 3h4x** [comment]
> > Should I be using SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 so that sccache is in foreground and alive always ?
> 
> This is pretty much never what you want, but you could try making your CI do something like:
> 
> ```
> # terminate any existing sccache instance
> sccache --stop-server
> SCCACHE_IDLE_TIMEOUT=0 sccache --start-server
> ```
> 
> To ensure that you're starting a fresh server invocation with the right settings.

Why running a caching service in foreground is not what you want?
