### ISSUE TITLE
Publish sccache-dist artifacts in releases

### ISSUE THREAD

**Issue by glandium** [mozilla/sccache#912]
#902 mostly covered this, but a) was missing a bit that made the artifact not actually published and b) forgot about the fact we remove the `[patch]` for tiny-http during the release process, which would have produced broken binaries.

**Comment by luser** [comment]
> forgot about the fact we remove the `[patch]` for tiny-http during the release process

I guess if upstream is not going to fix that issue you ought to either fork it, vendor a copy, or find a replacement.

**Comment by glandium** [comment]
The issue is fixed, and released, but we're not using tiny-http directly, rouille is, and rouille hasn't been updated in more than a year.
