### ISSUE TITLE
lru_disk_cache crate is a huge footgun

### ISSUE THREAD

**Issue by piegamesde** [mozilla/sccache#916]
I just tried out the `lru_disk_cache` crate because it sounds like it does what I want. However, one can easily corrupt files with it, but this behavior is not documented at all and the type system does not enforce anything.

First of all [`insert_file`](https://docs.rs/lru-disk-cache/0.4.1/lru_disk_cache/struct.LruDiskCache.html#method.insert_file) silently *moves* that file into the cache. In other words, it **deletes the original**. And the documentation does not spare one word on it.

The second issue is, that when using an absolute path as key, it will silently overwrite random files on the file system (outside of the cache). The content of the keys is never checked nor enforced. And I couldn't find any documentation on this either.

**Comment by glandium** [comment]
Absolute paths are not meant to be used as keys. Clearly, we're missing some normalization for the cache file path.

**Comment by luser** [comment]
Given that I wound up forking `lru_disk_cache` from the original, maybe vendoring it into the sccache codebase instead of publishing it as a separate crate would be better? I wrote the API to fit the needs of sccache and didn't put the level of care into it that it would need to be more broadly usable.

**Comment by piegamesde** [comment]
I'd really appreciate it having an own repository, yes. Making issues on the `sccache` repository just feels weird.

**Comment by glandium** [comment]
> Given that I wound up forking `lru_disk_cache` from the original, maybe vendoring it into the sccache codebase instead of publishing it as a separate crate would be better? I wrote the API to fit the needs of sccache and didn't put the level of care into it that it would need to be more broadly usable.

You _created_ lru_disk_cache, what you forked is lru_cache, which is vendored in lru_disk_cache.

**Comment by luser** [comment]
Oh right. I had originally written it as a refactor of `lru_cache` but it was really invasive and either I didn't submit it upstream or it wasn't accepted. In any event, there's no real need for it to be published as a standalone crate.

**Comment by piegamesde** [comment]
What does this mean for <https://docs.rs/lru-disk-cache/0.4.1/lru_disk_cache/>?

**Comment by glandium** [comment]
That it will be the last release and it becomes unmaintained. We can't remove it because of the already published versions of sccache using the already available versions.
If someone wants to take on the crate development, I guess we can discuss transfer of ownership.
Note that currently, there is no public crate depending on lru-disk-cache other than sccache: https://crates.io/crates/lru-disk-cache/reverse_dependencies.

**Comment by piegamesde** [comment]
> Note that currently, there is no public crate depending on lru-disk-cache other than sccache: https://crates.io/crates/lru-disk-cache/reverse_dependencies.

(And at least one non-published ^^) That's good to know. lib.rs was showing this as top #⁠5 in Caching so this gave me the false impression that it was a popular crate.

> That it will be the last release and it becomes unmaintained.

Please document this as good as possible so that nobody who accidentally stumbles upon this accidentally uses it. (Is there some official procedure for discontinuing crates on crates.io?)

**Comment by glandium** [comment]
I yanked all versions from crates.io.

**Comment by glandium** [comment]
Aaand I had to unyank 0.4.1 for now...

**Comment by piegamesde** [comment]
I've had a look what the ecosystem suggests to do for things like this. First of all, one can set the maintenance-status to "deprecated" in the [badges section of the manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section). There also seems to be some separate tracking in the [advisory-db](https://internals.rust-lang.org/t/tracking-unmaintained-crates-using-rustsec/10884), which is used by `cargo-deny`.

**Comment by luser** [comment]
Once you publish a new version of sccache that doesn't have the dependency you should be able to yank the newest version of lru-disk-cache to avoid people relying on it. You could also branch from the old rev and publish one last version with the deprecated  badge, and the README and crate-level docs updated with a warning.

Sorry to have made all this work for you by making a bad decision in the first place. ☹️

**Comment by xvello** [comment]
Heya folks! Sad to see this yanked as there is no other crate filling my use case (bounded size disk cache of blobs retrieved from a rate-limited API), but I understand the reasons.
I'll vendor it in my project for now, but I'd be happy to help make it an independent crate if others express interest in it.

**Comment by piegamesde** [comment]
This has definitely opened a gap my library needs as well. The question is, whether some crate can be made from the existing code, or if we'd rather build on top of something else (cacache maybe?) or if it's best to start from scratch.

I can't speak about the implementation, but the API was very much tailored to the needs of sccache and would definitely need a major overhaul.

**Comment by xvello** [comment]
I agree that the API would need an overhaul, for example `insert_file` has to go, or be renamed `move_file`. For my simple use case, I'll only be using `insert_bytes` and `get` (as I'll be retrieving file by http requests and serving them to TCP clients), so I might not be in the best place to design a new API surface.

I just pushed https://github.com/xvello/lru-disk-cache with full history until before https://github.com/mozilla/sccache/pull/923 and removing the other files. It builds as a standalone crate, and I'll import it in my project via the git URL for now.

I'll be adding a README tonight with a "here be dragons" warning and a to link to this issue, then we'll se what the future holds.

**Comment by luser** [comment]
I don't think anyone here is opposed to an interested party forking the crate to maintain it. Given that sccache has now vendored a private copy, I am open to adding you as an owner on crates.io if you go forward with this plan. I agree that it's useful functionality (which is why I implemented it in the first place) that could be more broadly useful if some work was done on the API.
