### ISSUE TITLE
Config file location on macOS changed in 0.2.14 and needs to be documented

### ISSUE THREAD

**Issue by mstange** [mozilla/sccache#919]
185c6ba4b0d360e6be8daf15a9fb80899c030df5 updated the `directories` dependency from 2 to 3. This contained a breaking change for the location of the config dir on macOS: https://github.com/dirs-dev/directories-rs#3

As a result, the config file location on macOS changed from `~/Library/Preferences/Mozilla.sccache/config` to `~/Library/Application Support/Mozilla.sccache/config`.

The documentation needs to be updated to reflect that. Ideally, if there are sccache release notes somewhere, this should be mentioned there, too.

**Comment by glandium** [comment]
We should also support the old config path.
