### ISSUE TITLE
Use serde's OsStr and OsString impls

### ISSUE THREAD

**Issue by dtolnay** [mozilla/sccache#93]
Following up on https://github.com/mozilla/sccache/pull/85#discussion_r108140271:

> **\<@luser>** as a follow-up, we could now just use OsStr or OsString all the way for the values from the client commandline.
> **\<@alexcrichton>** Yeah I tried to do that but Serialize/Deserialize wasn't implemented for one of them :(
> Actually... I'll send a PR!
> Ok this is now tracked at serde-rs/serde#823

I published Serde 0.9.12 containing Alex's impls for OsStr and OsString.

**Comment by luser** [comment]
Thanks!
