### ISSUE TITLE
Redis support with auth works with 0.2.13 but not >= 0.2.14

### ISSUE THREAD

**Issue by deimosfr** [mozilla/sccache#970]
Hi,

I'm using sccache 0.2.13 for several weeks without any issues with Redis as a backend and authentication works like a charm. However, with 0.2.14 and 0.2.15, it doesn't work anymore.
```
set -x SCCACHE_REDIS redis://login:pass@127.0.0.1:6379 ; pkill sccache ; sccache -s
error: failed to get stats from server
caused by: Failed to send data to or receive data from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
```

Any idea?

**Comment by Nereuxofficial** [comment]
you have to write : before the password so: `redis://:login:pass@127.0.0.1:6379`
I don't know why that is but it worked for me

**Comment by Xuanwo** [comment]
SHould be fixedby https://github.com/mozilla/sccache/issues/1404
