### ISSUE TITLE
Enable color output in rustc when it normally would be

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#99]
@jrmuizel was testing sccache for local Rust compilation and he noted that it made rustc's errors lose their normal color formatting. This is because rustc defaults to `--color auto`, which checks if stdout is a tty. Since sccache sends rustc's stdout/stderr to pipes, it doesn't output in color. We could append `--color always` to our rustc invocations if `--color` isn't already present on the commandline. Ideally we'd check if the sccache client's stdout is a tty and only do so in that case. That would present an edge case where we could cache color rustc output, then someone could run another compilation and pipe the output, and we'd use the cached output with the colors, but it doesn't seem to be likely to be a big problem in practice. The only colorful output rustc produces in successful compilations is warnings, AFAIK. We could make that edge case work by stripping ANSI color codes from the output when stdout is not a tty. If we did that, then we could just unIlaterally pass `--color always` to rustc and strip out the color codes when they're not wanted.

**Comment by theduke** [comment]
Big plus one for this.

You get a very noticable speedup when working on many crates, and always setting/unsetting RUSTC_WRAPPER is annoying.

**Comment by versusvoid** [comment]
Also `--color` argument mustn't trigger recompilation, so I see better approach in unconditionally passing (or overriding to) `--color=always` and stripping color codes when necessary.
Analogous logic should be implemented for gcc's and clang's `-fdiagnostics-color`.

For now adding `rustflags = ["--color=always"]` to `.cargo/config` mitigates the problem.

**Comment by luser** [comment]
>  Analogous logic should be implemented for gcc's and clang's -fdiagnostics-color.

Just to clarify: I did not implement support for this for gcc/clang. All the pieces necessary should be there, it'd just be a matter of adding the commandline parsing and such in the code that handles C compilation.
